/* The merge catalogue.
 *
 * One line per item: 'id|Name|shape|material[/accent][+deco,deco]'
 *   shape     — a primitive from src/artgen.ts (SHAPE_NAMES)
 *   material  — a palette entry from src/artgen.ts (MAT_NAMES); the whole
 *               lighting ramp is derived from it, so one word is a full look
 *   deco      — optional: glow, ring, crest, motes
 *
 * A chain is [key, Name, world, unlockAtWorldLevel, ...items]. Tier is the
 * position in the chain; sell price and XP come off the tier curve. Nothing
 * here is code — add a line, get an item.
 */

export const CHAINS = [
  /* ============================================================ SUNNY MEADOW */
  ['wood', 'Woodworks', 'earth', 1,
    'twig|Twig|twig|wood',
    'branch|Branch|vine|bark/leaf',
    'log|Log|log|wood',
    'lumber|Lumber Pile|plank|wood/straw',
    'cart|Timber Crate|crate|wood/iron',
    'workshop|Toolchest|chest|bark/gold',
    'treehouse|Great Oak|tree|bark/leaf+crest'],

  ['stone', 'Rock Quarry', 'earth', 1,
    'pebble|Pebble|pebble|stone',
    'rock|Rock|rock|stone',
    'geode|Geode|geode|slate/amethyst',
    'gem|Gemstone|gem|amethyst',
    'statue|Stone Idol|totem|stone/moss',
    'obelisk|Obelisk|prism|slate/moon',
    'monument|Monument|arch|stone/gold+crest'],

  ['berry', 'Berry Kitchen', 'earth', 2,
    'berry|Berry|berry|berry',
    'berries|Berry Bunch|berrycluster|berry/leaf',
    'jam|Jar of Jam|jar|glass/berry',
    'pie|Berry Pie|pie|dough/berry',
    'cake|Berry Cake|cake|cream/berry',
    'feast|Harvest Feast|basket|straw/cherry+crest'],

  ['water', 'Waterworks', 'earth', 2,
    'dew|Dewdrop|droplet|water',
    'puddle|Puddle|bubble|water',
    'jug|Water Jug|jar|glass/water',
    'barrel|Rain Barrel|barrel|wood/water',
    'fountain|Fountain|pot|stone/water',
    'aqueduct|Aqueduct|arch|stone/water+crest'],

  ['grass', 'Hay Meadow', 'earth', 3,
    'grass|Grass Tuft|fern|grass',
    'hay|Hay Bundle|grain|straw',
    'bale|Hay Bale|barrel|straw/rope',
    'hat|Straw Hat|basket|straw/cloth',
    'scarecrow|Scarecrow|totem|cloth/straw',
    'harvest|Golden Harvest|crate|straw/gold+crest'],

  ['flower', 'Flower Beds', 'earth', 3,
    'bulbseed|Flower Seed|seed|moss',
    'sprig|Green Sprig|sprout|leaf',
    'bloombud|Bud|bud|rose',
    'bouquet|Bouquet|flower|rose/leaf',
    'garland|Garland|blossom|lilac/gold',
    'flowercrown|Flower Crown|crown|rose/gold+crest'],

  ['honey', 'Honeyworks', 'earth', 4,
    'nectar|Nectar Drop|droplet|honey',
    'honeydrop|Honey Bead|bubble|honey',
    'honeycomb|Honeycomb|honey|honey',
    'honeypot|Honey Pot|pot|clay/honey',
    'beehive|Beehive|sack|honey/straw',
    'royaljelly|Royal Jelly|orb|honey/gold+glow,crest'],

  ['mush', 'Forest Floor', 'earth', 4,
    'caplet|Tiny Cap|bud|spore',
    'toadstool|Toadstool|mushroom|ruby/cream',
    'mushring|Cap Cluster|berrycluster|fungus/cream',
    'fairyring|Fairy Ring|flower|spore/glow',
    'mossheart|Moss Heart|orb|moss/glow+crest'],

  ['cloth', 'The Weavery', 'earth', 5,
    'fibre|Plant Fibre|rope|straw',
    'thread|Spool of Thread|spiral|cloth',
    'yarn|Ball of Yarn|orb|rose/cloth',
    'clothbolt|Bolt of Cloth|cloth|cloth',
    'quilt|Patch Quilt|cloth|lilac/mint',
    'tapestry|Tapestry|scroll|rose/gold+crest'],

  ['feather', 'The Nesting', 'earth', 5,
    'down|Down Tuft|cloud|cream',
    'plume|Feather|feather|dusk/silver',
    'nest|Twig Nest|basket|bark/straw',
    'speckegg|Speckled Egg|egg|cream/rose',
    'songbird|Songbird|bird|sapphire/gold',
    'aviary|Aviary|house|glass/leaf+crest'],

  ['clay', 'The Pottery', 'earth', 6,
    'mud|Clay Daub|pebble|clay',
    'claylump|Clay Lump|rock|clay',
    'claypot|Clay Pot|pot|clay',
    'urn|Painted Urn|jar|clay/rose',
    'kiln|Kiln|house|clay/flame',
    'porcelain|Porcelain Vase|pot|cream/sapphire+crest'],

  ['garden', 'Meadow Wilds', 'earth', 7,
    'grub|Grub|cocoon|cream/moss',
    'chrysalis|Chrysalis|cocoon|jade/gold',
    'flutter|Flutterwing|butterfly|lilac/topaz',
    'swarm|Bloom Swarm|butterfly|rose/gold+glow',
    'meadowheart|Meadow Heart|orb|leaf/glow+glow,crest'],

  /* ============================================================= CRATER CAMP */
  ['moon', 'Moon Rocks', 'luna', 1,
    'mrock|Moon Rock|pebble|moon',
    'mcrystal|Moon Shard|crystal|moon/frost',
    'mcore|Moon Core|gem|dusk/moon',
    'mstar|Moon Star|star|moon/star',
    'moonorb|Moon Orb|planet|moon/star+glow',
    'moonstatue|Moon Idol|mask|moon/silver+crest'],

  ['glow', 'Glow Garden', 'luna', 1,
    'spore|Glow Spore|seed|spore',
    'bulb|Glow Bulb|bud|glow',
    'glowflower|Glow Flower|flower|glow/spore',
    'starbloom|Star Bloom|blossom|star/glow',
    'glowtree|Glow Tree|tree|spore/glow+glow',
    'glowgrove|Glow Grove|house|spore/glow+crest'],

  ['dust', 'Dust Flats', 'luna', 2,
    'dustpinch|Dust Pinch|pebble|sand',
    'dustclump|Dust Clump|rock|sand/slate',
    'regolith|Regolith Brick|plank|slate/sand',
    'moonbrick|Moon Brick|crate|slate/moon',
    'moonwall|Moon Wall|arch|slate/moon+crest'],

  ['ice', 'Ice Fields', 'luna', 2,
    'frostchip|Frost Chip|ice|frost',
    'iceshard|Ice Shard|crystal|ice',
    'icecore|Ice Core|gem|ice/frost',
    'snowstar|Snow Star|snowflake|frost/ice',
    'glacier|Glacier Block|crate|ice/deepsea',
    'icecastle|Ice Castle|tower|ice/frost+crest'],

  ['crystal', 'Crystal Vein', 'luna', 3,
    'shardlet|Crystal Chip|pebble|crystal',
    'prismlet|Prism Shard|crystal|crystal',
    'prismcore|Prism Core|prism|crystal/aurora',
    'prismheart|Prism Heart|planet|crystal/aurora+glow',
    'prismtower|Prism Spire|tower|crystal/aurora+crest'],

  ['lantern', 'Lanternworks', 'luna', 4,
    'wick|Wick|rope|cloth',
    'lampglass|Lamp Glass|jar|glass',
    'moonlamp|Moon Lantern|lantern|gold/glow',
    'beacon|Beacon|lantern|copper/flame+glow',
    'lighthouse|Lighthouse|tower|cream/flame+crest'],

  ['silver', 'Silver Lode', 'luna', 4,
    'silverore|Silver Ore|ore|silver',
    'silvernug|Silver Nugget|pebble|silver',
    'silveringot|Silver Ingot|ingot|silver',
    'silvercup|Silver Chalice|pot|silver/amethyst',
    'silvercrown|Silver Crown|crown|silver/moon+crest'],

  ['comet', 'Comet Trail', 'luna', 5,
    'cometdust|Comet Dust|pebble|dusk',
    'cometice|Comet Ice|ice|frost/dusk',
    'cometcore|Comet Core|comet|star/gold',
    'cometstone|Comet Stone|boulder|dusk/star+glow',
    'cometheart|Comet Heart|planet|star/aurora+glow,crest'],

  ['lunamoth', 'Crater Wings', 'luna', 6,
    'mothegg|Moth Egg|egg|moon/spore',
    'mothcocoon|Silk Cocoon|cocoon|cream/moon',
    'lunamothi|Luna Moth|butterfly|mint/moon',
    'moonmoth|Moon Moth|butterfly|aurora/star+glow',
    'craterheart|Crater Heart|planet|moon/glow+glow,crest'],

  /* ============================================================ EMBER HOLLOW */
  ['magma', 'Magma Works', 'cindra', 1,
    'ember|Ember|ember|ember',
    'cinder|Cinder|coal|smoke/ember',
    'lavablob|Lava Blob|slime|magma/flame',
    'fireopal|Fire Opal|gem|flame/gold',
    'suncore|Sun Core|orb|flame/gold+glow',
    'sunforge|Sun Forge|anvil|obsidian/flame+crest'],

  ['shroom', 'Ash Garden', 'cindra', 1,
    'sporecap|Ash Spore|seed|smoke',
    'ashroom|Ash Shroom|mushroom|smoke/ember',
    'bigshroom|Great Shroom|mushroom|fungus/flame',
    'glowcap|Glow Cap|mushroom|ember/glow+glow',
    'shroomtree|Shroom Tree|tree|fungus/ember',
    'shroomcity|Shroom Hollow|house|fungus/glow+crest'],

  ['iron', 'Iron Forge', 'cindra', 2,
    'ironore|Iron Ore|ore|iron',
    'ironnug|Iron Nugget|pebble|iron',
    'ironingot|Iron Ingot|ingot|iron',
    'ironanvil|Anvil|anvil|steel/iron',
    'ironcrown|Iron Crown|crown|steel/rust+crest'],

  ['obsid', 'Obsidian Cut', 'cindra', 2,
    'obchip|Obsidian Chip|pebble|obsidian',
    'obshard|Obsidian Shard|crystal|obsidian/dusk',
    'obblade|Obsidian Blade|prism|obsidian/ember',
    'obmirror|Dark Mirror|ring|obsidian/silver+glow',
    'obthrone|Obsidian Throne|arch|obsidian/gold+crest'],

  ['glassw', 'Glassworks', 'cindra', 3,
    'sandpinch|Hot Sand|pebble|sand',
    'moltenglass|Molten Glass|slime|glass/flame',
    'glassbead|Glass Bead|pearl|glass/aurora',
    'glassvase|Glass Vase|bottle|glass/mint',
    'glasslily|Glass Lily|flower|glass/aurora+crest'],

  ['forge', 'The Smithy', 'cindra', 4,
    'coallump|Coal Lump|coal|coal',
    'coalbrick|Coal Brick|plank|coal/smoke',
    'forgefire|Forge Fire|flame|flame/ember+glow',
    'bellows|Bellows|sack|bark/copper',
    'greatforge|Great Forge|house|iron/flame+crest'],

  ['spice', 'Spice Kiln', 'cindra', 4,
    'pepperpod|Pepper Pod|seed|rust',
    'spicepouch|Spice Pouch|sack|clay/flame',
    'spicejar|Spice Jar|jar|glass/rust',
    'spicecrate|Spice Crate|crate|wood/flame',
    'spicefeast|Ember Feast|soup|clay/flame+crest'],

  ['copper', 'Copper Seam', 'cindra', 5,
    'copperore|Copper Ore|ore|copper',
    'coppernug|Copper Nugget|pebble|copper',
    'copperingot|Copper Ingot|ingot|copper',
    'copperbell|Copper Bell|bell|copper/gold',
    'coppercog|Great Cog|cog|copper/gold+crest'],

  ['phoenix', 'Ashfall Wings', 'cindra', 6,
    'ashfeather|Ash Feather|feather|smoke/ember',
    'emberegg|Ember Egg|egg|ember/gold',
    'firebird|Firebird|bird|flame/gold+glow',
    'phoenix|Phoenix|bird|gold/aurora+glow,crest',
    'hollowheart|Hollow Heart|orb|flame/glow+glow,crest'],

  /* ========================================================= TIDAL SHALLOWS */
  ['shellc', 'Shell Bed', 'nerith', 1,
    'shellchip|Shell Chip|pebble|shell',
    'seashell|Sea Shell|shell|shell',
    'bigshell|Great Shell|shell|coral/cream',
    'nautilus|Nautilus|spiral|cream/coral',
    'shellhorn|Shell Horn|bell|shell/gold',
    'shellthrone|Shell Throne|arch|pearl/coral+crest'],

  ['kelp', 'Kelp Forest', 'nerith', 1,
    'kelpleaf|Kelp Leaf|leaf|kelp',
    'kelpfrond|Kelp Frond|fern|kelp',
    'kelpcoil|Kelp Coil|rope|kelp/jade',
    'kelpbale|Kelp Bale|basket|kelp/moss',
    'kelpgrove|Kelp Grove|tree|kelp/jade',
    'kelpheart|Tide Grove|house|kelp/glow+crest'],

  ['pearlc', 'Pearl Diving', 'nerith', 2,
    'grit|Grain of Grit|pebble|sand',
    'seedpearl|Seed Pearl|pearl|cream',
    'pearl|Pearl|pearl|pearl+glow',
    'pearlstrand|Pearl Strand|berrycluster|pearl/silver',
    'pearlcrown|Pearl Crown|crown|pearl/silver+crest'],

  ['coralc', 'Coral Reef', 'nerith', 2,
    'coralbud|Coral Bud|bud|coral',
    'coralsprig|Coral Sprig|coral|coral',
    'coralfan|Coral Fan|coral|rose/coral',
    'coralcrown|Coral Crown|crown|coral/gold',
    'coralpalace|Coral Palace|tower|rose/pearl+crest'],

  ['fishc', 'Fish Market', 'nerith', 3,
    'minnow|Minnow|fish|mint',
    'silverfish|Silverfin|fish|silver/sapphire',
    'bigfish|Big Catch|fish|sapphire/gold',
    'fishcatch|Full Net|basket|rope/sapphire',
    'fishfeast|Tide Feast|soup|shell/mint+crest'],

  ['tide', 'Tide Pools', 'nerith', 3,
    'bubblet|Sea Bubble|bubble|water',
    'seafoam|Sea Foam|cloud|frost/water',
    'tidewave|Tide Swell|wave|deepsea/frost',
    'tidalorb|Tidal Orb|planet|deepsea/aurora+glow',
    'tidalheart|Tidal Heart|orb|sapphire/glow+glow,crest'],

  ['salt', 'Salt Pans', 'nerith', 4,
    'saltgrain|Salt Grain|pebble|cream',
    'saltcake|Salt Cake|ingot|cream/frost',
    'saltbrick|Salt Brick|crate|cream/ice',
    'saltpillar|Salt Pillar|crystal|cream/frost',
    'salttemple|Salt Temple|tower|cream/aurora+crest'],

  ['sunkn', 'Sunken Finds', 'nerith', 5,
    'driftbit|Driftwood Bit|twig|bone/kelp',
    'driftwood|Driftwood|log|bone/kelp',
    'driftboat|Beached Skiff|boat|bark/cloth',
    'sunkenchest|Sunken Chest|chest|bark/gold+glow',
    'sunkenidol|Drowned Idol|mask|jade/gold+crest'],

  ['lumin', 'Deep Lights', 'nerith', 6,
    'glowplankton|Plankton Mote|pearl|spore+glow',
    'jellybell|Jelly Bell|bell|lilac/glow+glow',
    'deeplantern|Deep Lantern|lantern|deepsea/glow+glow',
    'abyssorb|Abyss Orb|planet|deepsea/aurora+glow',
    'shallowheart|Shallow Heart|orb|mint/glow+glow,crest'],

  /* =========================================================== AURORA REACH */
  ['cloudc', 'Cloud Bank', 'vela', 1,
    'wisp|Wisp|cloud|cream',
    'cloudlet|Cloudlet|cloud|frost',
    'cloudpuff|Cloud Puff|cloud|cloud',
    'thundercloud|Thunderhead|cloud|dusk/topaz+glow',
    'cloudcastle|Cloud Castle|tower|cloud/aurora+crest'],

  ['aurorac', 'Aurora Weave', 'vela', 1,
    'aurorathread|Aurora Thread|spiral|aurora',
    'aurorasilk|Aurora Silk|cloth|aurora/mint',
    'auroraveil|Aurora Veil|wave|aurora/lilac+glow',
    'auroracloak|Aurora Cloak|cloth|lilac/aurora+glow',
    'auroracrown|Aurora Crown|crown|aurora/star+crest'],

  ['starc', 'Star Nursery', 'vela', 2,
    'stardust|Stardust|pebble|star',
    'starspark|Star Spark|gem|star/gold',
    'starlet|Starlet|star|star',
    'starcluster|Star Cluster|berrycluster|star/gold+glow',
    'starforge|Star Forge|anvil|dusk/star+crest'],

  ['wind', 'Wind Currents', 'vela', 2,
    'breeze|Breeze|feather|mint',
    'gust|Gust|wave|frost/mint',
    'windcoil|Wind Coil|spiral|frost/aurora',
    'windvane|Wind Vane|compass|silver/mint',
    'stormeye|Storm Eye|planet|dusk/aurora+glow,crest'],

  ['skyfruit', 'Sky Orchard', 'vela', 3,
    'skyseed|Sky Seed|seed|mint',
    'skybud|Sky Bud|blossom|mint/aurora',
    'skyfruit|Sky Fruit|fruit|topaz/mint',
    'skybasket|Sky Basket|basket|straw/topaz',
    'skyfeast|Cloud Feast|cake|cloud/topaz+crest'],

  ['chime', 'Chime Tower', 'vela', 3,
    'chimebit|Chime Shard|crystal|silver',
    'chimebell|Chime Bell|bell|silver/mint',
    'chimeset|Chime Ring|ring|silver/aurora',
    'chimetower|Chime Tower|tower|silver/aurora',
    'skybell|Sky Bell|bell|gold/aurora+glow,crest'],

  ['prismv', 'Prism Array', 'vela', 4,
    'lightmote|Light Mote|pearl|glow',
    'lightbeam|Light Beam|prism|glow/aurora',
    'prismlens|Prism Lens|gem|glass/aurora',
    'prismarray|Prism Array|snowflake|crystal/aurora+glow',
    'sunsprism|Sun Prism|prism|gold/aurora+glow,crest'],

  ['skynest', 'Sky Nest', 'vela', 5,
    'skydown|Sky Down|cloud|cream/mint',
    'skyfeather|Sky Feather|feather|aurora/silver',
    'skyplume|Sky Plume|feather|star/gold',
    'skynestn|Sky Nest|shell|cloud/gold',
    'skyegg|Dawn Egg|egg|aurora/gold+glow,crest'],

  ['balloonc', 'Drift Yards', 'vela', 6,
    'silkscrap|Silk Scrap|cloth|rose',
    'silkbag|Silk Envelope|sack|rose/cream',
    'driftballoon|Drift Balloon|balloon|rose/gold',
    'skyship|Sky Ship|boat|bark/aurora+glow',
    'reachheart|Reach Heart|orb|aurora/glow+glow,crest'],

  /* ============================================================ EVERY WORLD */
  ['star', 'Meteor Finds', 'any', 1,
    'scrap|Star Scrap|ore|steel/star',
    'starcore|Star Core|star|star/gold+glow'],

  ['relic', 'Relics', 'any', 1,
    'relic1|Sun Amber|gem|honey/gold+glow',
    'relic2|Prism Hearth|prism|flame/aurora+glow',
    'relic3|Tide Compass|compass|sapphire/gold+glow',
    'relic4|Grove Sigil|totem|jade/glow+glow,crest',
    'relic5|Vault Key|key|gold/aurora+glow,crest'],

  ['bloom', 'Bloom Essence', 'any', 1,
    'bloomspark|Bloom Spark|seed|glow+glow',
    'bloommote|Bloom Mote|pearl|glow/aurora+glow',
    'bloomcore|Bloom Core|orb|jade/glow+glow',
    'bloomheart|Bloom Heart|orb|aurora/glow+glow,crest'],

  ['wild', 'Wildcards', 'any', 1,
    'rainbow|Wildcard|orb|aurora/glow+glow,motes'],

  /* ================================================================= ROCKET */
  ['hull', 'Rocket: Hull', 'ship', 1,
    'bolt|Bolt|cog|steel',
    'boltpack|Bolt Pack|crate|steel/iron',
    'hullplate|Hull Plate|plank|steel/silver+crest'],
  ['engine', 'Rocket: Engine', 'ship', 1,
    'spring|Spring|spiral|copper',
    'coil|Coil|spiral|copper/gold',
    'enginecore|Engine Core|cog|iron/flame+crest'],
  ['nav', 'Rocket: Nav Dish', 'ship', 1,
    'wire|Wire|rope|copper',
    'circuit|Circuit|plank|jade/gold',
    'navdish|Nav Dish|compass|silver/sapphire+crest'],
  ['tank', 'Rocket: Fuel Tank', 'ship', 1,
    'glass|Glass Pane|ice|glass',
    'tankglass|Tank Glass|crate|glass/steel',
    'fueltank|Fuel Tank|barrel|steel/glow+crest'],
  ['fuel', 'Rocket Fuel', 'ship', 1,
    'fuelore|Fuel Ore|ore|glow/jade',
    'fuelcan|Fuel Canister|bottle|jade/glow',
    'rocketfuel|Rocket Fuel|flask|glow/aurora+glow,crest'],
];

/* Items whose completion does something special. */
export const SPECIAL = {
  hullplate: { part: 'hull' }, enginecore: { part: 'engine' },
  navdish: { part: 'nav' }, fueltank: { part: 'tank' },
  rocketfuel: { fuel: true },
};
