/* The merge catalogue.
 *
 * One line per item: 'id|Name|shape|material[/accent][+deco,deco]|description'
 *   shape       — a primitive from src/artgen.ts (SHAPE_NAMES), used only for
 *                 the generated stand-in drawing until a painted sprite lands
 *   material    — a palette entry from src/artgen.ts (MAT_NAMES); the whole
 *                 lighting ramp is derived from it, so one word is a full look
 *   deco        — optional: glow, motes
 *   description — what the thing actually is, in a painter's words. It never
 *                 reaches the game: it goes into the art prompt only
 *                 (art/notes.json -> art/manifest.csv). Say what makes its
 *                 silhouette different from the step below it.
 *
 * A chain is [key, Name, world, unlockAtWorldLevel, ...items]. Tier is the
 * position in the chain; sell price and XP come off the tier curve. Chains run
 * from 4 to 8 steps — short ones are quick wins, long ones are the grind worth
 * showing off. Nothing here is code — add a line, get an item.
 */

export const CHAINS = [
  /* ============================================================ SUNNY MEADOW
     Home: an Earth that looks like a summer countryside, with the first
     hints that the sky is full of other worlds. */
  ['wood', 'Meteor Metal', 'earth', 1,
    'twig|Meteor Chip|twig|wood|a curly purple twig with one glowing blue knot',
    'branch|Hot Meteor|vine|bark/leaf|a branch with three glowing blue leaves',
    'log|Metal Ingot|log|wood|a log with spiral star rings on its end',
    'lumber|Metal Plates|plank|wood/straw|purple planks tied with a glowing vine',
    'cart|Cargo Crate|crate|wood/iron|a wooden crate stamped with a ringed planet',
    'workshop|Tool Chest|chest|bark/gold|an open toolchest with little ray-gun tools',
    'treehouse|Hover Sled|tree|bark/leaf|a great purple alien tree with a round pod-house',
    'woodrocket|Little Shuttle|tower|wood/gold+glow|a hand-built wooden rocket with Gloop in the porthole'],

  ['stone', 'Starstone Quarry', 'earth', 1,
    'pebble|Star Pebble|pebble|stone|a pebble with golden star freckles',
    'rock|Crystal Rock|rock|stone|a lumpy rock with crystals sprouting',
    'geode|Glow Geode|geode|slate/amethyst|a geode full of glowing teal crystals',
    'gem|Star Gem|gem|amethyst|a star-cut rainbow gem',
    'statue|Three-Eyed Idol|totem|stone/moss|a three-eyed alien stone idol',
    'obelisk|Orbit Obelisk|prism|slate/moon|an obelisk with floating stone rings',
    'monument|Crystal Arch|arch|stone/gold|a floating rock arch covered in crystals'],

  ['berry', 'Space Snacks', 'earth', 2,
    'berry|Star Cookie|berry|berry|one plump red berry with a little leaf',
    'berries|Snack Cube|berrycluster|berry/leaf|a bunch of five berries on a sprig',
    'jam|Food Tube|jar|glass/berry|a glass jar of red jam with a gingham cloth lid',
    'pie|Ration Tray|pie|dough/berry|a round lattice-top berry pie in a dish',
    'cake|Jelly Dome|cake|cream/berry|a two-tier cream cake topped with berries',
    'feast|Snack Pod|basket|straw/cherry|a picnic hamper overflowing with pies, jam and fruit',
    'jamfactory|Rocket Diner|house|cream/berry+glow|a cute cottage kitchen with a giant jam pot bubbling on the roof'],

  ['water', 'Moonwater', 'earth', 2,
    'dew|Water Drop|droplet|water|a glowing teal dewdrop',
    'puddle|Crater Puddle|bubble|water|a puddle reflecting two moons',
    'jug|Water Canister|jar|glass/water|a moon-painted jug of bubbling glow-water',
    'barrel|Water Tank|barrel|wood/water|a barrel with a round glowing porthole',
    'fountain|Orb Fountain|pot|stone/water|a fountain with floating water orbs',
    'aqueduct|Hydro Tower|arch|stone/water|a floating aqueduct',
    'watertower|Ice Comet|tower|wood/water+glow|a water tower shaped like a UFO'],

  ['grass', 'Solar Power', 'earth', 3,
    'grass|Solar Chip|fern|grass|a tuft of blue-green star grass',
    'hay|Solar Cell|grain|straw|a bundle of silver hay',
    'bale|Solar Panel|barrel|straw/rope|a hay bale wrapped with a glowing band',
    'hat|Panel Array|basket|straw/cloth|a straw hat with two antenna bobbles',
    'scarecrow|Power Station|totem|cloth/straw|a friendly robot scarecrow',
    'harvest|Solar Satellite|crate|straw/gold|a floating harvest wagon'],

  ['flower', 'Nebula Lights', 'earth', 3,
    'bulbseed|Spark|seed|moss|a tiny striped seed',
    'sprig|Glow Bulb|sprout|leaf|a seedling with two round leaves',
    'bloombud|Space Lamp|bud|rose|a closed pink flower bud on a stem',
    'bouquet|Star Lantern|flower|rose/leaf|a hand-tied bouquet of pink flowers',
    'garland|Light String|blossom|lilac/gold|a looped garland of lilac flowers with a gold ribbon',
    'flowercrown|Orbit Lamp|crown|rose/gold|a circlet of roses woven on a thin gold band',
    'flowerarch|Light Tower|arch|rose/leaf+glow|a garden arch covered in blooming roses, petals drifting'],

  ['honey', 'Star Nectar', 'earth', 4,
    'nectar|Nectar Drop|droplet|honey|a small drop of golden nectar',
    'honeydrop|Nectar Bubble|bubble|honey|a round glossy bead of honey',
    'honeycomb|Hex Cell|honey|honey|a slab of hexagonal honeycomb dripping honey',
    'honeypot|Nectar Pot|pot|clay/honey|a round clay honey pot with a wooden dipper',
    'beehive|Buzzbot Pod|sack|honey/straw|a domed straw skep beehive with a round door',
    'royaljelly|Royal Nectar|orb|honey/gold+glow|a glowing golden orb of royal jelly on a tiny gold stand',
    'honeypalace|Nectar Palace|tower|honey/gold+glow|a tall honeycomb tower with golden domes and happy little bees'],

  ['mush', 'Eyeshrooms', 'earth', 4,
    'caplet|Shroomling|bud|spore|a tiny single mushroom button',
    'toadstool|Eyeshroom|mushroom|ruby/cream|a red-capped toadstool with cream spots',
    'mushring|Shroom Bunch|berrycluster|fungus/cream|a cluster of three mushrooms of different heights',
    'fairyring|Shroom Ring|flower|spore/glow|a ring of small glowing mushrooms around a mossy patch',
    'mossheart|Big Eyeshroom|orb|moss/glow|a heart-shaped mossy stone glowing softly green'],

  ['cloth', 'Space Suits', 'earth', 5,
    'fibre|Star Thread|rope|straw|a fluffy glowing nebula cotton puff',
    'thread|Suit Patch|spiral|cloth|a spool of shimmering thread',
    'yarn|Space Glove|orb|rose/cloth|a yarn ball with a galaxy swirl',
    'clothbolt|Space Helmet|cloth|cloth|a fabric bolt with a star pattern',
    'quilt|Moon Boots|cloth|lilac/mint|a folded quilt covered in planets',
    'tapestry|Jetpack|scroll|rose/gold|a hanging galaxy tapestry',
    'spacesuit|Spacesuit|cloth|cream/sapphire+glow|a little spacesuit on a stand'],

  ['feather', 'Jet Gear', 'earth', 5,
    'down|Fuel Puff|cloud|cream|a glowing down fluff',
    'plume|Thruster|feather|dusk/silver|an iridescent plume',
    'nest|Jet Boot|basket|bark/straw|a nest of crystal twigs',
    'speckegg|Twin Jetpack|egg|cream/rose|a star-speckled galaxy egg',
    'songbird|Hoverboard|bird|sapphire/gold|a big-eyed alien songbird',
    'aviary|Jet Bike|house|glass/leaf|a glass aviary dome with floating islands'],

  ['clay', 'Moon Goo', 'earth', 6,
    'mud|Goo Splat|pebble|clay|a blob of lilac mud',
    'claylump|Goo Lump|rock|clay|a clay lump with a three-finger print',
    'claypot|Goo Pot|pot|clay|a pot painted with planets',
    'urn|Orbit Urn|jar|clay/rose|an urn with orbit rings',
    'kiln|Rocket Kiln|house|clay/flame|a kiln shaped like a rocket engine',
    'porcelain|Nebula Vase|pot|cream/sapphire|a glowing nebula porcelain vase'],

  ['garden', 'Glowbugs', 'earth', 7,
    'grub|Glow Grub|cocoon|cream/moss|a tiny glowing grub with antennae',
    'chrysalis|Glow Cocoon|cocoon|jade/gold|a glowing chrysalis',
    'flutter|Glowbug|butterfly|lilac/topaz|a moth with planet-patterned wings',
    'swarm|Bug Jar|butterfly|rose/gold+glow|glowbugs swarming in a lantern',
    'meadowheart|Glowbug Queen|orb|leaf/glow+glow|a heart of glowbugs and flowers'],

  ['veggie', 'Hydroponics', 'earth', 8,
    'vegseed|Seed Capsule|seed|clay|a seed packet with planets on it',
    'seedling|Sprout Tube|sprout|leaf|a seedling with antenna leaves',
    'carrot|Grow Tube|fruit|peach/leaf|a twisty purple star-carrot',
    'vegbundle|Hydro Tray|grain|peach/leaf|spiky cucumber, glowing radish and friends',
    'vegcrate|Grow Rack|crate|wood/peach|a crate of alien veg',
    'vegstall|Greenhouse Dome|house|cloth/peach|a market stall with a saucer roof',
    'giantpumpkin|Hydro Tower|fruit|peach/gold+glow|a giant pumpkin with a ring like Saturn'],

  ['stargaze', 'Star Lenses', 'earth', 9,
    'lenschip|Lens Chip|ice|glass|a lens chip with a star glint',
    'lens|Star Lens|gem|glass/copper|a polished star lens',
    'spyglass|Planet Spyglass|bottle|copper/glass|a spyglass with a planet engraving',
    'telescope|Brass Telescope|lantern|copper/sapphire|a brass telescope on a tripod',
    'observatory|Observatory|house|cream/sapphire+glow|a small observatory dome',
    'planetarium|Planetarium|house|sapphire/star+glow,motes|a planetarium with a glowing starry roof'],

  ['visitor', 'Little Visitors', 'earth', 10,
    'oddegg|Odd Egg|egg|mint/star|a mint-green egg with little glowing star spots',
    'blinky|Blinky|slime|mint|a tiny round mint alien blob with one big blinking eye',
    'alienkid|Little Alien|slime|mint/lilac|a small green alien with two antennae and a big smile',
    'alienexplorer|Alien Explorer|slime|mint/steel|the little alien in a bubble helmet with a backpack',
    'saucer|Flying Saucer|planet|steel/glow+glow|a small round flying saucer with a glass dome and ring of lights',
    'alienfamily|Saucer Family|planet|silver/mint+glow|a big saucer with three little aliens waving from its dome',
    'mothership|Mothership|planet|silver/aurora+glow,motes|a huge friendly mothership, glowing rings of windows, beams of light underneath'],

  /* ------------------------------------------------ v16: more of the Meadow */
  ['bakery', 'Moon Cheese', 'earth', 10,
    'flour|Cheese Crumb|grain|cream|a little heap of soft white flour with a scoop',
    'dough|Cheese Cube|cheese|dough|a round ball of pale dough dusted with flour',
    'roll|Cheese Wedge|bread|dough/honey|a golden glazed bread roll',
    'loaf|Cheese Wheel|bread|dough/straw|a big scored country loaf on a wooden board',
    'breadbasket|Cheese Stack|basket|straw/dough|a wicker basket piled with rolls, loaves and a baguette',
    'buntower|Cheese Cart|cake|honey/cream|a tall tower of glazed buns with a cherry on top',
    'bakeryoven|Cheese Moon|house|clay/ember+glow|a round brick bakery oven with a glowing mouth and a chimney puffing'],
  ['tea', 'Zero-G Drinks', 'earth', 10,
    'tealeaf|Fizz Drop|leaf|leaf|a single bright young tea leaf',
    'teabundle|Drink Pouch|fern|leaf/rope|a bundle of tea sprigs tied with string',
    'teacup|Soda Can|pot|cream/rose|a dainty teacup with a saucer and a pink rim',
    'teapot|Fizz Bottle|pot|rose/gold|a round flowery teapot with a gold lid',
    'teaset|Drink Dispenser|basket|cream/gold|a teapot, two cups and a sugar bowl on a tray',
    'teaparty|Soda Fountain|house|rose/leaf+motes|a little round garden table set for tea under a flowery parasol'],
  ['pond', 'Slime Pool', 'earth', 10,
    'ponddrop|Slime Drop|droplet|water|a glowing pond drop with a star inside',
    'lilypad|Slime Puddle|leaf|kelp|a lily pad with a star flower',
    'lotus|Slime Jar|blossom|rose/water|a glowing lotus',
    'pondfrog|Slime Frog|slime|mint/leaf|a three-eyed frog',
    'koipair|Slime Fountain|fish|peach/water|a pair of koi with fin-wings',
    'koipond|Slime Pool|wave|water/stone|a small pond with floating lights',
    'moonbridge|Slime Volcano|arch|wood/water+glow|a moon bridge over glowing water'],
  ['toys', 'Space Toys', 'earth', 10,
    'block|Alien Block|crate|wood/cherry|a small painted wooden toy block with a star',
    'spintop|Saucer Top|gem|cherry/gold|a striped spinning top',
    'toyrobot|Toy Robot|totem|steel/sapphire|a little wind-up tin robot with a key in its back',
    'toyrocket|Toy Rocket|tower|cherry/steel|a tin wind-up rocket with fins and a key',
    'puppets|Alien Puppets|house|cherry/gold|a tiny puppet theatre with red curtains',
    'toyshop|Toy Starport|house|wood/rose+motes|a cosy toy shop stall full of toys under a striped awning'],

  /* ------------------------------------- v25: late-Meadow side chains (story) */
  ['picnic', 'Cargo', 'earth', 10,
    'crumb|Small Box|pebble|dough|a few golden bread crumbs',
    'sandwich|Parcel|bread|dough/leaf|a fat triangle sandwich with lettuce poking out',
    'picnicbasket|Cargo Crate|basket|straw/cherry|a wicker picnic basket with a gingham lid',
    'picnicblanket|Crate Stack|crate|cherry/straw|a checked blanket spread out with the basket on it',
    'lemonadeset|Container|jar|glass/honey|a jug of lemonade with glasses and fruit on a little board',
    'picnicparasol|Cargo Drone|house|rose/cream|a picnic laid out under a pink striped parasol',
    'gardenparty|Cargo Ship|house|cream/rose+motes|a round garden-party table set with cakes and flowers',
    'picnicpavilion|Space Freighter|house|gold/rose+glow,motes|a golden pavilion with bunting over a picnic feast'],
  ['pets', 'Alien Pets', 'earth', 10,
    'petegg|Spotted Egg|egg|lilac/cream|a lilac egg with purple spots',
    'hatchegg|Peeking Egg|egg|lilac/star|a cracked egg with one curious eye peeking out',
    'blobling|Blobling|slime|lilac|a tiny lilac alien blob hatchling with one big eye on a stalk',
    'blobpup|Blobbo|slime|lilac/cream|a playful three-eyed lilac alien blob wearing a little collar',
    'pupbed|Blob Bed|pot|lilac/rose|the lilac alien blob curled up asleep in a round cushion bed',
    'puphouse|Blob House|house|lilac/gold|a little dome-shaped alien pet house with a round door',
    'petpark|Pet Playground|house|mint/lilac+motes|a tiny pet playground with a slide and swings',
    'petpalace|Pet Palace|house|gold/lilac+glow,motes|a golden domed pet palace with towers and a velvet cushion'],
  ['music', 'Cosmic Tunes', 'earth', 10,
    'notepebble|Crystal Note|pebble|lilac/gold|a note-shaped crystal',
    'whistle|Rocket Whistle|gem|honey/gold|a rocket-shaped whistle',
    'ukulele|Star Ukulele|totem|wood/honey|a ukulele with a star soundhole',
    'drum|Planet Drum|barrel|cherry/gold|a drum with a planet skin',
    'jukebox|UFO Jukebox|tower|cherry/gold+glow|a jukebox with a saucer top',
    'oneband|One-Alien Band|totem|mint/gold|a green alien playing every instrument',
    'bandstand|Dome Bandstand|house|sapphire/gold+glow|a glass-dome bandstand',
    'concertshell|Ringed Stage|arch|gold/rose+glow,motes|a concert shell under a ringed planet'],
  ['parts', 'Rocket Parts', 'earth', 10,
    'hexbolt|Glow Bolt|pebble|steel|a chunky steel bolt',
    'gear|Star Gear|gem|steel/slate|a silver gear wheel',
    'fin|Rocket Fin|leaf|steel/sapphire|a curved silver rocket fin',
    'nosecone|Porthole Cone|prism|cherry/steel|a red and white rocket nose cone',
    'booster|Booster|barrel|steel/gold|a small silver booster tube',
    'fueltin|Fuel Cell|barrel|steel/ember|a round fuel canister with an orange band',
    'engineblock|Triple Engine|crate|steel/copper|a heavy engine block with a big nozzle',
    'minirocket|Mini Rocket|tower|cherry/steel+glow|a shiny little rocket on a launch stand'],
  ['weather', 'Space Weather', 'earth', 10,
    'raindrop|Swirl Drop|droplet|water|a glowing raindrop with a galaxy swirl',
    'puffcloud|Sleepy Cloud|cloud|cloud|a puff cloud with a sleepy face',
    'raincloud2|Zap Cloud|cloud|cloud/water|a rain cloud with tiny lightning',
    'rainbowcloud|Aurora Cloud|cloud|cloud/aurora|a cloud with an aurora rainbow',
    'weathervane|Rocket Vane|totem|copper/gold|a weathervane with a rocket arrow',
    'weatherstation|Dish Station|tower|steel/sapphire|a weather station with a dish',
    'cloudmachine|Cloud Machine|house|cloud/gold+glow|a machine that puffs clouds',
    'sundial|Two-Sun Dial|arch|gold/aurora+glow,motes|a sundial for two suns'],

  /* ---------------------------------------- event chains: only during events */
  ['ev_star', 'Falling Stars', 'any', 1,
    'starbit|Star Bit|star|star|a tiny glowing star fragment',
    'starbunch|Star Bunch|crystal|star/gold|three little stars stuck together',
    'starjar|Jar of Stars|jar|glass/star+glow|a glass jar full of twinkling stars',
    'cometlamp|Comet Lamp|lantern|gold/star+glow|a brass lamp with a little comet inside',
    'starthrone|Star Throne|crown|gold/star+glow|a small golden throne made of starlight'],
  ['ev_lantern', 'Comet Lanterns', 'any', 1,
    'paperlantern|Comet Lantern|lantern|rose|a small round paper lantern',
    'lanternstring|Star Lantern String|rope|rose/gold|a string of three glowing paper lanterns',
    'flowerlantern|Bloom Lantern|lantern|rose/leaf+glow|a lantern shaped like a tulip, glowing',
    'lanternarch|Crystal Lantern Arch|arch|wood/rose+glow|a wooden arch hung with glowing lanterns',
    'lanternboat|Lantern Saucer|boat|wood/gold+glow|a little boat carrying a glowing lantern',
    'skyfestival|Lantern Isle|balloon|rose/gold+motes|a cluster of sky lanterns rising into the night'],
  ['ev_candy', 'Space Candy', 'any', 1,
    'candydrop|Planet Gumdrop|candy|cherry|a single shiny round candy',
    'lollipop|Galaxy Lollipop|candy|rose/cream|a swirly lollipop on a stick',
    'candyjar|Star Candy Jar|jar|glass/cherry|a big glass jar of colourful candies',
    'cupcakes|Alien Cupcakes|cake|rose/cream|a tower of frosted cupcakes',
    'carousel|Saucer Carousel|tower|rose/gold+motes|a tiny carousel with candy horses',
    'candycastle|Rocket Candy Castle|house|rose/cream+glow|a castle made of candy and frosting'],

  /* ============================================================= CRATER CAMP
     A lilac moon: craters, crystals, robot friends and bouncy alien pets. */
  ['moon', 'Moon Rocks', 'luna', 1,
    'mrock|Moon Rock|pebble|moon|a small pale lilac moon pebble with a tiny crater',
    'mcrystal|Moon Shard|crystal|moon/frost|a single frosty moon crystal shard',
    'mcore|Moon Core|gem|dusk/moon|a round cut violet core stone',
    'mstar|Moon Star|star|moon/star|a chunky five-point star carved from moonstone',
    'moonorb|Moon Orb|planet|moon/star+glow|a small glowing moon with craters and a star ring',
    'moonstatue|Moon Idol|mask|moon/silver|a carved moonstone face with calm closed eyes and silver trim',
    'moonbase|Moon Outpost|house|silver/moon+glow|a cosy domed moon habitat with round windows and an antenna',
    'moonpalace|Lunar Palace|tower|moon/star+glow,motes|a shining lilac palace of domes and spires on a crater rim'],

  ['glow', 'Glow Pods', 'luna', 1,
    'spore|Glow Spore|seed|spore|a tiny violet spore with a soft glow',
    'bulb|Glow Pod|bud|glow|a round glowing flower bulb',
    'glowflower|Pod Cluster|flower|glow/spore|a cyan glowing flower with violet centre',
    'starbloom|Pod Lamp|blossom|star/glow|a star-shaped golden blossom',
    'glowtree|Pod Tower|tree|spore/glow+glow|a small tree with glowing round fruit',
    'glowgrove|Pod City|house|spore/glow|a greenhouse dome full of glowing plants'],

  ['dust', 'Dust Flats', 'luna', 2,
    'dustpinch|Dust Pinch|pebble|sand|a small heap of grey-lilac moon dust',
    'dustclump|Dust Clump|rock|sand/slate|a packed clump of moon dust',
    'regolith|Regolith Brick|plank|slate/sand|a single pressed moon-dust brick',
    'moonbrick|Moon Brick|crate|slate/moon|a neat stack of moon bricks',
    'moonwall|Moon Wall|arch|slate/moon|a curved moon-brick wall with a round doorway',
    'moontown|Dome Town|house|slate/glow+glow|a little town of moon-brick domes with warm glowing windows'],

  ['ice', 'Ice Fields', 'luna', 2,
    'frostchip|Frost Chip|ice|frost|a small chip of frost',
    'iceshard|Ice Shard|crystal|ice|a pointed pale-blue ice shard',
    'icecore|Ice Core|gem|ice/frost|a clear round ice core with a frozen bubble inside',
    'snowstar|Snow Star|snowflake|frost/ice|a big six-point snowflake',
    'glacier|Glacier Block|crate|ice/deepsea|a big cube of layered glacier ice',
    'icecastle|Ice Castle|tower|ice/frost|a small ice castle with two turrets',
    'icepalace|Frost Citadel|tower|ice/aurora+glow|a tall glittering ice citadel with aurora light inside'],

  ['crystal', 'Crystal Vein', 'luna', 3,
    'shardlet|Crystal Chip|pebble|crystal|a tiny cyan crystal chip',
    'prismlet|Prism Shard|crystal|crystal|a single long cyan crystal',
    'prismcore|Prism Core|prism|crystal/aurora|a cluster of three crystals on a rock base',
    'prismheart|Prism Heart|planet|crystal/aurora+glow|a heart-shaped crystal glowing from inside',
    'prismtower|Prism Spire|tower|crystal/aurora|a tall spire of stacked crystals',
    'prismgarden|Crystal Garden|house|crystal/aurora+glow|a whole garden of crystal spires under a glass dome',
    'prismthrone|Crystal Throne|arch|crystal/gold+glow,motes|a radiant throne of cyan crystal with gold arms'],

  ['lantern', 'Lanternworks', 'luna', 4,
    'wick|Wick|rope|cloth|a short candle wick',
    'lampglass|Lamp Glass|jar|glass|an empty glass lamp chimney',
    'moonlamp|Moon Lantern|lantern|gold/glow|a gold lantern with a glowing moon inside',
    'beacon|Beacon|lantern|copper/flame+glow|a big copper signal beacon with a bright flame',
    'lighthouse|Lighthouse|tower|cream/flame|a striped lighthouse on a crater rock',
    'starbeacon|Star Beacon|tower|gold/star+glow,motes|a golden lighthouse beaming a star-shaped light into space'],

  ['silver', 'Silver Lode', 'luna', 4,
    'silverore|Silver Ore|ore|silver|a rock with shiny silver veins',
    'silvernug|Silver Nugget|pebble|silver|a lumpy silver nugget',
    'silveringot|Silver Ingot|ingot|silver|a neat silver bar',
    'silvercup|Silver Chalice|pot|silver/amethyst|a silver goblet set with violet gems',
    'silvercrown|Silver Crown|crown|silver/moon|a silver crown with moonstone points',
    'silverthrone|Silver Throne|arch|silver/amethyst+glow|a tall silver throne with a crescent-moon back'],

  ['comet', 'Comet Trail', 'luna', 5,
    'cometdust|Comet Dust|pebble|dusk|a sparkling pinch of violet comet dust',
    'cometice|Comet Ice|ice|frost/dusk|a dirty-snowball chunk of comet ice',
    'cometcore|Comet Core|comet|star/gold|a small golden comet with a short tail',
    'cometstone|Comet Stone|boulder|dusk/star+glow|a big comet rock trailing sparkles',
    'cometheart|Comet Heart|planet|star/aurora+glow|a blazing comet heart with a long aurora tail'],

  ['lunamoth', 'Crater Wings', 'luna', 6,
    'mothegg|Moon Egg|egg|moon/spore|a small lilac egg on a leaf',
    'mothcocoon|Sleepy Cocoon|cocoon|cream/moon|a silky cream cocoon',
    'lunamothi|Fluffwing|butterfly|mint/moon|a pale green moth with long tails',
    'moonmoth|Big Fluffwing|butterfly|aurora/star+glow|a big glowing moth with star-patterned wings',
    'craterheart|Fluffwing Queen|planet|moon/glow+glow|a glowing moon-heart wrapped in moth wings, radiant'],

  ['moonpup', 'Moon Critters', 'luna', 7,
    'wobbleegg|Wobble Egg|egg|lilac/moon|a lilac egg wobbling, a tiny crack at the top',
    'blip|Blip|slime|lilac|a tiny round lilac alien critter with big eyes',
    'moonpup|Moon Pup|slime|lilac/silver|a puppy-like moon alien with floppy antenna-ears',
    'hoppup|Hopper|slime|lilac/sapphire|the moon pup mid-bounce, spring-like feet',
    'craterhound|Crater Crab|slime|moon/sapphire|a bigger six-legged moon hound with a silver collar',
    'starhound|Star Critter|slime|dusk/star+glow|a hound with a coat of twinkling stars',
    'moonguardian|Moon Guardian|slime|moon/gold+glow,motes|a majestic glowing guardian beast with a crescent-moon crest'],

  ['rover', 'Rover Yard', 'luna', 8,
    'screw|Screw|cog|steel|a single fat steel screw',
    'wheel|Rover Wheel|cog|steel/slate|a chunky treaded rover wheel',
    'axle|Wheel Axle|plank|steel/slate|two wheels joined on an axle',
    'toyrover|Little Rover|crate|steel/sapphire|a small four-wheeled rover with a camera head',
    'moonbuggy|Moon Buggy|boat|silver/sapphire|an open two-seat moon buggy with a dish on the back',
    'bigrover|Six-Wheel Rover|crate|silver/topaz|a big six-wheeled rover with solar wings and a drill arm',
    'roverbase|Rover Garage|house|silver/sapphire+glow|a domed rover garage with a buggy parked out front',
    'launchpad|Launch Pad|tower|silver/flame+glow,motes|a moon launch pad with a small rocket ready to lift off'],

  ['helium', 'Helium Wells', 'luna', 9,
    'gaswisp|Gas Wisp|cloud|glow|a small swirling wisp of glowing gas',
    'gasbubble|Gas Bubble|bubble|glow/lilac|a round bubble of glowing gas',
    'gasflask|Gas Flask|flask|glass/glow|a round flask with glowing gas inside',
    'gascan|Gas Canister|bottle|steel/glow|a stubby steel canister with a valve and gauge',
    'gastank|Helium Tank|barrel|silver/glow|a big round pressure tank with pipes and a glowing window',
    'fusioncell|Fusion Cell|orb|glow/aurora+glow,motes|a glowing sphere of plasma held in silver rings',
    'fusionreactor|Fusion Reactor|tower|silver/aurora+glow,motes|a tall silver reactor with a glowing plasma ring at its centre'],

  ['meteorite', 'Meteorite Field', 'luna', 10,
    'spacegrit|Space Grit|pebble|iron|a small dark pitted grain of meteorite',
    'meteorite|Meteorite|rock|iron/slate|a dark scorched meteorite with a melted crust',
    'ironmeteor|Iron Meteorite|ore|iron/silver|a heavy meteorite with polished silver cross-hatching',
    'pallasite|Pallasite|geode|iron/jade|a sliced meteorite slab full of green gem crystals',
    'meteorgeode|Star Geode|geode|dusk/star+glow|an opened meteorite glittering with starlight crystals',
    'starmetal|Star Metal|ingot|silver/star+glow|a glowing ingot of star metal with a sparkle',
    'meteormonument|Skyfall Stone|boulder|iron/star+glow,motes|a huge meteorite standing upright on a plinth, glowing veins'],

  ['dish', 'Signal Dishes', 'luna', 11,
    'antwire|Antenna Wire|rope|copper|a coil of copper antenna wire',
    'antenna|Antenna|key|silver/copper|a tall thin antenna with a blinking tip',
    'minidish|Mini Dish|compass|silver|a small satellite dish on a stand',
    'radar|Radar Dish|compass|silver/sapphire|a larger radar dish tilted to the sky',
    'signaltower|Signal Tower|tower|silver/sapphire+glow|a lattice tower with dishes and blinking lights',
    'deeparray|Deep Space Array|tower|silver/aurora+glow,motes|three giant dishes pointed up, beams of light between them',
    'starhorn|Listening Spire|tower|gold/aurora+glow,motes|a golden spire of dishes catching a beam of light from the stars'],

  ['moonmelon', 'Algae Farm', 'luna', 12,
    'moonseed|Algae Drop|seed|lilac|a pale lilac seed',
    'moonsprout|Algae Jar|sprout|mint/lilac|a sprout with curly lilac leaves',
    'moonmelon|Algae Tank|fruit|mint/lilac|a round pale-green melon with lilac stripes',
    'meloncrate|Algae Crate|crate|steel/mint|a steel crate full of moon melons',
    'moondome|Algae Dome|house|glass/mint+glow|a glass farm dome full of melon vines',
    'moonfarm|Algae Farm|house|mint/lilac+glow,motes|a whole crater of farm domes, melon patches and a little windmill'],

  /* ============================================================ EMBER HOLLOW
     A volcanic world at dusk: magma, forges, basalt and fire-loving creatures. */
  ['magma', 'Magma Works', 'cindra', 1,
    'ember|Ember|ember|ember|a small glowing ember',
    'cinder|Cinder|coal|smoke/ember|a dark cinder with orange glowing cracks',
    'lavablob|Lava Blob|slime|magma/flame|a wobbly blob of bright lava',
    'fireopal|Fire Opal|gem|flame/gold|a cut orange fire opal flickering inside',
    'suncore|Sun Core|orb|flame/gold+glow|a small blazing orb like a pocket sun',
    'sunforge|Sun Forge|anvil|obsidian/flame|an obsidian anvil with a sun blazing on it',
    'toyvolcano|Little Volcano|boulder|obsidian/magma+glow|a cute cone volcano puffing a smoke ring, lava down one side',
    'sunengine|Sun Engine|cog|gold/flame+glow,motes|a golden engine of gears with a blazing sun at its heart'],

  ['shroom', 'Ash Shrooms', 'cindra', 1,
    'sporecap|Ash Spore|seed|smoke|a small grey spore',
    'ashroom|Ash Shroom|mushroom|smoke/ember|a grey mushroom with ember-orange gills',
    'bigshroom|Great Shroom|mushroom|fungus/flame|a tall salmon mushroom with a wide cap',
    'glowcap|Glow Cap|mushroom|ember/glow+glow|a mushroom glowing warm orange',
    'shroomtree|Shroom Tower|tree|fungus/ember|a tree made of stacked mushroom caps',
    'shroomcity|Shroom Hollow|house|fungus/glow|a mushroom house with round windows and a chimney',
    'shroomcastle|Shroom Castle|tower|fungus/ember+glow|a castle of giant glowing mushroom towers'],

  ['iron', 'Iron Forge', 'cindra', 2,
    'ironore|Iron Ore|ore|iron|a rock with rusty iron veins',
    'ironnug|Iron Nugget|pebble|iron|a dull iron nugget',
    'ironingot|Iron Ingot|ingot|iron|a neat iron bar',
    'ironanvil|Anvil|anvil|steel/iron|a classic steel anvil',
    'ironcrown|Iron Crown|crown|steel/rust|a heavy iron crown with rivets',
    'ironbot|Iron Bot|totem|iron/flame|a small boxy iron robot with an ember glowing in its chest',
    'ironmech|Great Mech|totem|steel/flame+glow|a big friendly walking mech with furnace eyes'],

  ['obsid', 'Obsidian Cut', 'cindra', 2,
    'obchip|Obsidian Chip|pebble|obsidian|a small glossy black-purple chip',
    'obshard|Obsidian Shard|crystal|obsidian/dusk|a sharp glossy obsidian shard',
    'obblade|Obsidian Blade|prism|obsidian/ember|a polished obsidian blade with an ember edge',
    'obmirror|Dark Mirror|ring|obsidian/silver+glow|a round obsidian mirror in a silver frame',
    'obthrone|Obsidian Throne|arch|obsidian/gold|a glossy obsidian throne with gold trim',
    'obcitadel|Obsidian Citadel|tower|obsidian/ember+glow,motes|a tall black-glass citadel with ember light in every window'],

  ['glassw', 'Glassworks', 'cindra', 3,
    'sandpinch|Hot Sand|pebble|sand|a small heap of hot orange sand',
    'moltenglass|Molten Glass|slime|glass/flame|a glowing gob of molten glass',
    'glassbead|Glass Bead|pearl|glass/aurora|a round swirled glass bead',
    'glassvase|Glass Vase|bottle|glass/mint|a tall green glass vase',
    'glasslily|Glass Lily|flower|glass/aurora|a delicate glass lily',
    'glassdome|Glass Dome|house|glass/aurora+glow|a blown-glass dome with a tiny garden inside',
    'glasspalace|Glass Palace|tower|glass/aurora+glow,motes|a crystal-clear palace of blown glass throwing rainbows'],

  ['forge', 'Star Forge', 'cindra', 4,
    'coallump|Star Coal|coal|coal|a lump of coal',
    'coalbrick|Coal Brick|plank|coal/smoke|a pressed coal brick',
    'forgefire|Forge Flame|flame|flame/ember+glow|a crackling fire in a small stone hearth',
    'bellows|Bellows|sack|bark/copper|a leather bellows with copper nozzle',
    'greatforge|Great Forge|house|iron/flame|an iron forge building with a glowing furnace door',
    'foundry|Star Foundry|house|iron/star+glow,motes|a huge foundry pouring a glowing river of star metal'],

  ['spice', 'Fire Gel', 'cindra', 4,
    'pepperpod|Fire Drop|seed|rust|a small red hot pepper',
    'spicepouch|Gel Pouch|sack|clay/flame|a tied pouch of red spice',
    'spicejar|Gel Jar|jar|glass/rust|a glass jar of layered spices',
    'spicecrate|Gel Crate|crate|wood/flame|a crate of spice sacks and jars',
    'spicefeast|Gel Barrel|soup|clay/flame|a steaming pot of fiery stew',
    'spicebazaar|Gel Refinery|house|cloth/flame+glow|a tented market stall hung with spice sacks and lanterns'],

  ['copper', 'Copper Seam', 'cindra', 5,
    'copperore|Copper Ore|ore|copper|a rock with copper-orange veins',
    'coppernug|Copper Nugget|pebble|copper|a shiny copper nugget',
    'copperingot|Copper Ingot|ingot|copper|a copper bar',
    'copperbell|Copper Bell|bell|copper/gold|a copper hand bell',
    'coppercog|Great Cog|cog|copper/gold|a large copper cog wheel',
    'copperclock|Copper Clock|compass|copper/gold+glow|a round copper clock with visible gears',
    'automaton|Copper Automaton|totem|copper/gold+glow,motes|a graceful copper clockwork figure with a wind-up key',
    'clocktower|Clockwork Tower|tower|copper/gold+glow,motes|a tall copper clock tower full of turning gears'],

  ['phoenix', 'Flame Wings', 'cindra', 6,
    'ashfeather|Ember Feather|feather|smoke/ember|a grey feather with an ember tip',
    'emberegg|Ember Egg|egg|ember/gold|an orange egg with glowing cracks',
    'firebird|Flamelet|bird|flame/gold+glow|a round little bird made of flame',
    'phoenix|Flame Flyer|bird|gold/aurora+glow|a grand phoenix with sweeping flame wings',
    'hollowheart|Firebird|orb|flame/glow+glow|a burning heart-shaped core, radiant'],

  ['salamander', 'Fire Critters', 'cindra', 7,
    'warmegg|Warm Egg|egg|ember|a small orange egg giving off heat shimmer',
    'newt|Flame Blob|fish|ember/flame|a tiny orange newt with a flickering flame tail',
    'salamander|Fire Critter|fish|flame/magma|a chunky salamander with fire along its back',
    'lavalizard|Lava Critter|fish|magma/obsidian|a bigger lizard with obsidian scales and glowing spots',
    'magmadrake|Magma Dragonlet|bird|magma/gold+glow|a small friendly dragon of lava with gold horns',
    'emberwyrm|Ember Dragon|bird|flame/gold+glow,motes|a great gentle fire dragon curled around a volcano peak'],

  ['basalt', 'Basalt Columns', 'cindra', 8,
    'basaltchip|Basalt Chip|pebble|slate|a small dark basalt chip',
    'basaltblock|Basalt Block|rock|slate/obsidian|a squared basalt block',
    'hexcolumn|Hex Column|prism|slate/obsidian|a single six-sided basalt column',
    'columnstack|Column Stack|prism|slate/ember|three hex columns of different heights',
    'basaltarch|Basalt Gate|arch|slate/ember+glow|a gate made of hex columns with lava glowing underneath',
    'causeway|Giant\'s Steps|tower|slate/flame+glow|a towering staircase of hex columns glowing at the seams',
    'basaltcrown|Basalt Crown|crown|obsidian/gold+glow,motes|a crown of hex columns with lava glowing between them'],

  ['sulfur', 'Sulfur Springs', 'cindra', 9,
    'sulfurdust|Sulfur Dust|pebble|topaz|a small heap of bright yellow sulfur dust',
    'sulfurcrystal|Sulfur Crystal|crystal|topaz|a single yellow sulfur crystal',
    'sulfurcluster|Sulfur Cluster|geode|topaz/obsidian|a spiky cluster of yellow crystals on dark rock',
    'brimstone|Brimstone Heart|gem|topaz/flame+glow|a glowing yellow brimstone gem with fire inside'],

  ['steam', 'Steamworks', 'cindra', 10,
    'steampuff|Steam Puff|cloud|smoke|a small white puff of steam',
    'steampipe|Steam Pipe|plank|copper/smoke|a bent copper pipe with a puff at the end',
    'valve|Pressure Valve|cog|copper/ruby|a copper valve wheel with a red handle',
    'boiler|Boiler|barrel|copper/flame|a round copper boiler with a gauge and a firebox',
    'steamengine|Steam Engine|cog|iron/copper|a chugging steam engine with pistons and a flywheel',
    'geoplant|Geothermal Plant|house|iron/flame+glow|a small power station on a vent, pipes and steam towers',
    'steamtitan|Steam Titan|totem|copper/flame+glow,motes|a giant brass robot puffing steam from its shoulders'],

  ['emberfruit', 'Lava Lamps', 'cindra', 11,
    'charseed|Lava Drop|seed|coal/ember|a black seed with an ember glow',
    'embersprout|Lava Bulb|sprout|ember|a sprout with orange flame-shaped leaves',
    'firefruit|Lava Lamp|fruit|flame/magma|a round fruit with flame-coloured skin',
    'fruitbasket|Big Lava Lamp|basket|straw/flame|a basket of glowing fire fruit',
    'embertree|Lamp Stand|tree|obsidian/flame+glow|a black-barked tree heavy with glowing fire fruit',
    'embergrove|Lava Light Tower|tree|flame/gold+glow,motes|a ring of glowing fire-fruit trees around a warm lava pool'],

  ['rubyc', 'Ruby Caves', 'cindra', 12,
    'redchip|Red Chip|pebble|ruby|a tiny red stone chip',
    'rubyshard|Ruby Shard|crystal|ruby|a single raw ruby crystal',
    'cutruby|Cut Ruby|gem|ruby|a brilliant cut ruby',
    'rubyring|Ruby Ring|ring|gold/ruby|a gold ring set with a ruby',
    'rubyscepter|Ruby Sceptre|key|gold/ruby+glow|a gold sceptre topped with a big ruby',
    'rubycrown|Ruby Crown|crown|gold/ruby+glow|a tall gold crown studded with rubies',
    'rubyidol|Ruby Idol|mask|ruby/gold+glow,motes|a giant glowing ruby carved into a smiling face, gold base'],

  /* ========================================================= TIDAL SHALLOWS
     An ocean planet of bright shallows, reefs, sunken cities and sea aliens. */
  ['shellc', 'Shell Bed', 'nerith', 1,
    'shellchip|Shell Chip|pebble|shell|a small pink shell fragment',
    'seashell|Sea Shell|shell|shell|a single pink scallop shell',
    'bigshell|Great Shell|shell|coral/cream|a big spiral conch',
    'nautilus|Nautilus|spiral|cream/coral|a striped nautilus shell',
    'shellhorn|Shell Horn|bell|shell/gold|a conch horn with a gold mouthpiece',
    'shellthrone|Shell Throne|arch|pearl/coral|a throne made of a giant scallop shell',
    'shellpalace|Shell Palace|tower|pearl/coral+glow,motes|a palace built of giant spiral shells on a pink sandbar'],

  ['kelp', 'Bubble Tech', 'nerith', 1,
    'kelpleaf|Bubble|leaf|kelp|a single wavy kelp leaf',
    'kelpfrond|Bubble Cluster|fern|kelp|a tall kelp frond with air bladders',
    'kelpcoil|Bubble Jar|rope|kelp/jade|a coiled rope of kelp',
    'kelpbale|Bubble Helmet|basket|kelp/moss|a bundled bale of kelp',
    'kelpgrove|Bubble Pod|tree|kelp/jade|a tall swaying kelp tree',
    'kelpheart|Bubble Dome|house|kelp/glow|a hut woven from kelp with glowing windows',
    'kelpcathedral|Bubble City|tower|kelp/glow+glow|a towering spire of woven kelp and glowing lanterns'],

  ['pearlc', 'Pearl Diving', 'nerith', 2,
    'grit|Grain of Grit|pebble|sand|a tiny grain of sand',
    'seedpearl|Seed Pearl|pearl|cream|a tiny pearl in a small open shell',
    'pearl|Pearl|pearl|pearl+glow|a big lustrous pearl in an oyster',
    'pearlstrand|Pearl Strand|berrycluster|pearl/silver|a looped strand of pearls',
    'pearlcrown|Pearl Crown|crown|pearl/silver|a silver crown set with pearls',
    'pearlorb|Pearl Orb|orb|pearl/aurora+glow|a huge glowing pearl on a coral stand',
    'pearlpalace|Pearl Palace|tower|pearl/coral+glow,motes|a palace of pearly domes rising from the waves'],

  ['coralc', 'Coral Reef', 'nerith', 2,
    'coralbud|Coral Bud|bud|coral|a tiny coral bud',
    'coralsprig|Coral Sprig|coral|coral|a small branching coral',
    'coralfan|Coral Fan|coral|rose/coral|a wide pink sea fan',
    'coralcrown|Coral Crown|crown|coral/gold|a crown of branching coral',
    'coralpalace|Coral Palace|tower|rose/pearl|a coral tower with pearl windows',
    'coralcity|Coral City|house|coral/pearl+glow|a cluster of coral towers and domes, fish swimming around',
    'reefcrown|Reef Crown|crown|coral/pearl+glow,motes|a giant crown of living coral set with pearls, fish circling it'],

  ['fishc', 'Swimmer Critters', 'nerith', 3,
    'minnow|Bubbler|fish|mint|a tiny mint fish',
    'silverfish|Three-Eye Swimmer|fish|silver/sapphire|a sleek silver fish',
    'bigfish|Big Swimmer|fish|sapphire/gold|a big round blue fish',
    'fishcatch|Critter Tank|basket|rope/sapphire|a net bulging with fish',
    'fishfeast|Aquarium|soup|shell/mint|a steaming seafood pot',
    'fishhall|Aqua Dome|house|shell/sapphire+glow|a seaside market hall with fish-shaped weathervane and striped awnings'],

  ['tide', 'Tide Pools', 'nerith', 3,
    'bubblet|Sea Bubble|bubble|water|a single sea bubble',
    'seafoam|Sea Foam|cloud|frost/water|a puff of sea foam',
    'tidewave|Tide Swell|wave|deepsea/frost|a curling blue wave',
    'tidalorb|Tidal Orb|planet|deepsea/aurora+glow|a glowing orb of swirling seawater',
    'tidalheart|Tidal Heart|orb|sapphire/glow+glow|a blue heart-shaped gem with a tide inside'],

  ['salt', 'Sea Crystals', 'nerith', 4,
    'saltgrain|Crystal Grain|pebble|cream|a small heap of salt',
    'saltcake|Crystal Cube|ingot|cream/frost|a pressed salt cake',
    'saltbrick|Crystal Brick|crate|cream/ice|a stack of salt bricks',
    'saltpillar|Crystal Pillar|crystal|cream/frost|a tall salt crystal pillar',
    'salttemple|Crystal Temple|tower|cream/aurora|a white salt temple with a domed roof',
    'saltlight|Crystal Lighthouse|tower|cream/aurora+glow,motes|a tall white salt-crystal lighthouse beaming over the sea'],

  ['sunkn', 'Sunken Saucer', 'nerith', 5,
    'driftbit|Scrap Bit|twig|bone/kelp|a small bleached stick of driftwood',
    'driftwood|Hull Piece|log|bone/kelp|a twisted driftwood log with kelp',
    'driftboat|Porthole|boat|bark/cloth|a little wooden skiff with a patched sail',
    'sunkenchest|Sunken Pod|chest|bark/gold+glow|a barnacled treasure chest spilling gold',
    'sunkenidol|Sunken Robot|mask|jade/gold|a jade idol face with gold eyes',
    'galleon|Sunken Saucer|boat|bark/kelp+glow|a sunken ship on its side, covered in coral',
    'sunkencity|Sunken Station|tower|jade/pearl+glow,motes|ancient domed city towers rising out of the shallows, glowing windows'],

  ['lumin', 'Deep Lights', 'nerith', 6,
    'glowplankton|Glow Mote|pearl|spore+glow|a tiny glowing speck of plankton',
    'jellybell|Jelly Blob|bell|lilac/glow+glow|a small glowing jellyfish',
    'deeplantern|Lantern Critter|lantern|deepsea/glow+glow|an anglerfish-style lantern with a glowing lure',
    'abyssorb|Abyss Orb|planet|deepsea/aurora+glow|a dark orb with glowing deep-sea lights',
    'shallowheart|Deep Heart|orb|mint/glow+glow|a glowing sea-green heart, radiant'],

  ['squid', 'Reef Critters', 'nerith', 7,
    'bubbleegg|Bubble Egg|egg|water/coral|a clear jelly egg with a tiny critter curled inside',
    'squidlet|Squidlet|slime|coral|a tiny pink squid with big eyes',
    'tentapal|Tentacle Pal|slime|coral/mint|a round alien octopus waving four arms',
    'reefsquid|Reef Squid|slime|rose/coral|a bigger squid with a coral-crest hat',
    'glowocto|Glow Octo|slime|lilac/glow+glow|an octopus with glowing spots along its arms',
    'krakenpal|Kraken Pal|slime|deepsea/coral+glow|a big friendly kraken hugging a shell',
    'tidekraken|Tide Kraken|slime|deepsea/pearl+glow,motes|a giant gentle kraken wearing a pearl crown, arms curled around a wave'],

  ['turtle', 'Shell Critters', 'nerith', 8,
    'turtleegg|Shell Egg|egg|cream|a round leathery egg half buried in sand',
    'hatchling|Shellkin|fish|jade|a tiny sea turtle hatchling',
    'seaturtle|Shell Critter|fish|jade/sand|a grown sea turtle with a patterned shell',
    'islandturtle|Island Shell|house|jade/leaf+glow|an enormous turtle with a tiny palm island on its shell'],

  ['harbour', 'Sub Dock', 'nerith', 9,
    'knot|Cable Coil|rope|rope|a single tied rope knot',
    'float|Float Ring|bubble|glass/rope|a glass fishing float in a rope net',
    'buoy|Beacon Buoy|bell|coral/cream|a striped red-and-white buoy with a bell',
    'anchor|Tractor Hook|key|iron/rope|an iron anchor with a coiled rope',
    'shipwheel|Helm Console|cog|wood/gold|a wooden ship\'s wheel with gold caps',
    'divebell|Diving Pod|bell|copper/glass+glow|a round copper diving bell with portholes',
    'submarine|Submarine|boat|topaz/copper+glow,motes|a round yellow submarine with portholes and a periscope'],

  ['seaglass', 'Sea Glass', 'nerith', 10,
    'glasspebble|Glass Pebble|pebble|glass|a frosted blue-green glass pebble',
    'seaglassbit|Sea Glass|ice|mint|a smooth frosted mint sea-glass piece',
    'glassfloat|Glass Float|orb|glass/mint|a round glass float with a swirl inside',
    'glasslamp|Sea Glass Lamp|lantern|mint/glow|a lamp made of stained sea-glass pieces',
    'glasschime|Sea Glass Chimes|bell|glass/mint+glow|a hanging wind chime of coloured sea-glass pieces',
    'glasscity|Glass Reef Dome|house|glass/aurora+glow|an underwater glass dome city'],

  ['urchin', 'Spike Critters', 'nerith', 11,
    'urchinspine|Spike|twig|plum|a single violet urchin spine',
    'urchin|Spikeball|berry|plum|a round spiky violet sea urchin',
    'starurchin|Star Spike|star|coral/plum|a starfish with an urchin in its middle',
    'starfishcrown|Spike Crown|crown|coral/gold+glow|a crown of starfish on a gold band'],

  ['manta', 'Gliders', 'nerith', 12,
    'mantaegg|Glider Egg|egg|deepsea|a dark blue egg case with curly corners',
    'babymanta|Baby Glider|fish|deepsea/mint|a tiny manta ray',
    'manta|Glider|fish|deepsea/cream|a graceful manta ray gliding',
    'starmanta|Star Glider|fish|dusk/star+glow|a manta with a starry back',
    'skymanta|Sky Glider|bird|aurora/star+glow,motes|a giant manta flying above the waves trailing light'],

  /* =========================================================== AURORA REACH
     Cloudtops under a night sky: auroras, stars, satellites and star-beasts. */
  ['cloudc', 'Cloud Bank', 'vela', 1,
    'wisp|Wisp|cloud|cream|a tiny wisp of cloud',
    'cloudlet|Cloudlet|cloud|frost|a small round cloud',
    'cloudpuff|Cloud Puff|cloud|cloud|a big fluffy cloud',
    'thundercloud|Thunderhead|cloud|dusk/topaz+glow|a dark cloud with a gold lightning bolt',
    'cloudcastle|Cloud Castle|tower|cloud/aurora|a castle built on a cloud',
    'cloudcity|Cloud City|tower|cloud/aurora+glow|a city of cloud towers joined by rainbow bridges',
    'skykingdom|Sky Kingdom|tower|cloud/gold+glow,motes|a grand floating kingdom of white-and-gold palaces on a cloud island'],

  ['aurorac', 'Aurora Weave', 'vela', 1,
    'aurorathread|Aurora Thread|spiral|aurora|a glowing teal thread',
    'aurorasilk|Aurora Silk|cloth|aurora/mint|a folded shimmering silk',
    'auroraveil|Aurora Veil|wave|aurora/lilac+glow|a floating ribbon of aurora light',
    'auroracloak|Aurora Cloak|cloth|lilac/aurora+glow|a cloak made of aurora light on a stand',
    'auroracrown|Aurora Crown|crown|aurora/star|a crown of aurora light with star points',
    'auroraharp|Aurora Harp|bell|gold/aurora+glow,motes|a golden harp strung with aurora light'],

  ['starc', 'Star Nursery', 'vela', 2,
    'stardust|Stardust|pebble|star|a pinch of glittering gold stardust',
    'starspark|Star Spark|gem|star/gold|a small bright spark',
    'starlet|Starlet|star|star|a small chubby star',
    'starcluster|Star Cluster|berrycluster|star/gold+glow|a cluster of little stars',
    'starforge|Star Forge|anvil|dusk/star|an anvil forging a star',
    'constellation|Constellation|star|star/aurora+glow|stars joined by glowing lines into a little shape',
    'supernova|Supernova|orb|star/flame+glow,motes|a blazing burst of a star, rays and rings of light'],

  ['wind', 'Wind Currents', 'vela', 2,
    'breeze|Breeze|feather|mint|a small swirl of breeze',
    'gust|Gust|wave|frost/mint|a curling gust of wind',
    'windcoil|Wind Coil|spiral|frost/aurora|a tight spiral of wind',
    'windvane|Wind Vane|compass|silver/mint|a silver weather vane',
    'windmill|Sky Windmill|tower|silver/mint+glow|a tall windmill on a cloud with silver sails turning',
    'stormeye|Storm Eye|planet|dusk/aurora+glow|a swirling storm with a calm glowing eye'],

  ['skyfruit', 'Cloud Jelly', 'vela', 3,
    'skyseed|Jelly Wisp|seed|mint|a floating mint seed with a tiny wing',
    'skybud|Jelly Blob|blossom|mint/aurora|a blossom floating on a cloud',
    'skyfruit|Jelly Jar|fruit|topaz/mint|a round golden floating fruit',
    'skybasket|Jelly Cake|basket|straw/topaz|a basket of sky fruit hanging from a balloon',
    'skyfeast|Jelly Feast|cake|cloud/topaz|a cloud cake topped with sky fruit',
    'skytreehouse|Jelly Isle|tree|mint/topaz+glow|a floating island with a fruit tree and a little house'],

  ['chime', 'Chime Tower', 'vela', 3,
    'chimebit|Chime Shard|crystal|silver|a small silver chime rod',
    'chimebell|Chime Bell|bell|silver/mint|a silver bell',
    'chimeset|Chime Ring|ring|silver/aurora|a ring of hanging chimes',
    'chimetower|Chime Tower|tower|silver/aurora|a tall tower of chimes',
    'skybell|Sky Bell|bell|gold/aurora+glow|a great golden bell glowing with aurora',
    'chimecathedral|Chime Cathedral|tower|gold/aurora+glow,motes|a soaring golden cathedral full of bells and aurora light'],

  ['prismv', 'Prism Array', 'vela', 4,
    'lightmote|Light Mote|pearl|glow|a tiny mote of light',
    'lightbeam|Light Beam|prism|glow/aurora|a short beam of light in a crystal',
    'prismlens|Prism Lens|gem|glass/aurora|a round prism lens splitting light',
    'prismarray|Prism Array|snowflake|crystal/aurora+glow|a snowflake-shaped array of prisms',
    'sunsprism|Sun Prism|prism|gold/aurora+glow|a golden prism throwing a rainbow',
    'rainbowbridge|Rainbow Bridge|arch|aurora/gold+glow,motes|a solid rainbow arching between two small cloud islands'],

  ['skynest', 'Cloud Critters', 'vela', 5,
    'skydown|Cloud Puff|cloud|cream/mint|a tuft of cloud-soft down',
    'skyfeather|Sky Plume|feather|aurora/silver|a teal aurora feather',
    'skyplume|Cloud Nest|feather|star/gold|a golden starry plume',
    'skynestn|Sky Egg|shell|cloud/gold|a nest woven of cloud with gold threads',
    'skyegg|Cloud Flyer|egg|aurora/gold+glow|a glowing egg in dawn colours',
    'skyroc|Cloud Glider|bird|aurora/gold+glow,motes|a huge gentle bird with dawn-coloured wings spread wide'],

  ['balloonc', 'Drift Yards', 'vela', 6,
    'silkscrap|Silk Scrap|cloth|rose|a scrap of pink silk',
    'silkbag|Balloon Envelope|sack|rose/cream|a bundled silk balloon envelope',
    'driftballoon|Drift Balloon|balloon|rose/gold|a striped hot-air balloon',
    'skyship|Balloon Airship|boat|bark/aurora+glow|a wooden airship with aurora sails',
    'reachheart|Sky Heart|orb|aurora/glow+glow|a radiant heart of aurora light'],

  ['starling', 'Star Critters', 'vela', 7,
    'stardustegg|Starlit Egg|egg|dusk/star|a violet egg dotted with tiny stars',
    'glimmer|Glimmer|slime|star|a tiny round star-sprite with a sleepy face',
    'starsprite|Star Sprite|star|star/aurora|a small star-shaped alien with little arms, waving',
    'nebkitten|Nebula Kitten|slime|lilac/star|a violet kitten-like alien with star freckles',
    'cometfox|Comet Critter|slime|dusk/star+glow|a fox-like alien with a long comet tail',
    'aurorafox|Aurora Critter|slime|aurora/star+glow|a fox with a flowing aurora tail and glowing ears',
    'celestfox|Celestial Critter|slime|dusk/gold+glow|a majestic fox made of night sky, gold markings',
    'starbeast|Constellation Beast|slime|star/aurora+glow,motes|a giant gentle beast outlined in stars, glowing lines between them'],

  ['satellite', 'Satellite Works', 'vela', 8,
    'solarcell|Solar Cell|plank|sapphire|a single blue solar cell tile',
    'solarpanel|Solar Panel|plank|sapphire/silver|a folding solar panel in a silver frame',
    'minisat|Mini Satellite|cog|silver/sapphire|a small cube satellite with two panel wings',
    'commsat|Comm Satellite|compass|silver/gold|a satellite with a dish and gold foil body',
    'stationmod|Station Module|barrel|silver/sapphire|a round space-station module with windows and a docking port',
    'orbstation|Orbital Station|planet|silver/aurora+glow|a ring-shaped space station with solar wings',
    'stargate|Star Gate|ring|silver/aurora+glow,motes|a huge silver ring gate with swirling light inside'],

  ['nebula', 'Nebula Jars', 'vela', 9,
    'nebwisp|Nebula Wisp|cloud|lilac|a small wisp of pink-violet nebula gas',
    'nebpuff|Nebula Puff|cloud|lilac/aurora|a colourful swirling puff',
    'nebjar|Nebula Jar|jar|glass/lilac|a glass jar holding a swirling nebula',
    'nebglobe|Nebula Globe|orb|glass/lilac+glow|a snow-globe with a swirling pink nebula inside, on a gold base',
    'neblamp|Nebula Lamp|lantern|gold/lilac+glow|a lantern glowing with nebula colours',
    'bottledgalaxy|Bottled Galaxy|bottle|glass/aurora+glow,motes|a corked bottle with a whole spiral galaxy inside'],

  ['starflower', 'Glow Orbs', 'vela', 10,
    'starseed|Orb Seed|seed|star|a tiny glowing seed shaped like a star',
    'starsprout|Small Orb|sprout|mint/star|a sprout with star-tipped leaves',
    'starflower|Orb Pair|flower|star/lilac|a flower with star-shaped petals',
    'starpot|Orb Pot|pot|lilac/star|a pot of starflowers',
    'stargarden|Orb Garden|blossom|star/aurora+glow|a floating flowerbed of starflowers under a glowing arch',
    'starmeadow|Orb Field|blossom|star/lilac+glow,motes|a floating meadow island carpeted in glowing starflowers'],

  ['planets', 'Tiny Planets', 'vela', 11,
    'planetdust|Planet Dust|pebble|dusk|a tiny floating speck of rock',
    'planetoid|Planetoid|rock|slate/dusk|a small lumpy planetoid',
    'miniplanet|Mini Planet|planet|sapphire/leaf|a tiny round planet with seas and green land',
    'ringplanet|Ringed Planet|planet|topaz/cream|a planet with a wide cream ring',
    'twinplanets|Twin Planets|planet|rose/sapphire|two little planets orbiting each other',
    'orrery|Orrery|compass|gold/sapphire+glow|a brass orrery with planets on arms',
    'galaxyswirl|Galaxy Swirl|spiral|aurora/star+glow|a small spiral galaxy floating and glowing',
    'universe|Pocket Universe|orb|dusk/star+glow,motes|a glass sphere holding galaxies and stars'],

  ['kite', 'Drones', 'vela', 12,
    'kitetail|Rotor|rope|rose|a ribbon kite tail with bows',
    'kitediamond|Mini Drone|leaf|rose/aurora|a diamond kite with a bow tail',
    'boxkite|Drone|crate|topaz/rose|a box kite with striped panels',
    'dragonkite|Cargo Drone|bird|aurora/gold+glow,motes|a long glowing dragon kite coiling through the sky'],


  /* ---- v45: eight new chains, each riding on a producer that fits it */
  ['mail', 'Moon Mail', 'luna', 9,
    'stampchip|Stamp Chip|leaf|cream/sapphire|a tiny space stamp',
    'lettercap|Letter Capsule|bottle|glass/gold|a rolled letter in a capsule',
    'parcelpod|Parcel Pod|crate|cream/sapphire|a small parcel pod',
    'mailsack|Mail Sack|crate|cream/ruby|a stuffed mail sack with an antenna',
    'mailrover|Mail Rover|cog|cream/sapphire|a little mail rover',
    'postdome|Post Dome|house|cream/gold+glow|a round post office dome'],
  ['bots', 'Helper Bots', 'luna', 8,
    'boltbug|Bolt Bug|cog|steel|a loose bolt with tiny legs',
    'cupbot|Cup Bot|cog|cream/topaz|a round helper bot the size of a cup',
    'sweepbot|Sweeper Bot|cog|topaz/steel|a sweeper bot with a brush',
    'drillbot|Digger Bot|cog|topaz/steel|a digger bot with a drill',
    'walkerbot|Walker Bot|cog|topaz/steel|a two-legged walker bot',
    'buddymech|Buddy Mech|cog|cream/topaz+glow|a big friendly mech',
    'botshop|Bot Workshop|house|cream/topaz+glow|a robot workshop dome'],
  ['fireworks', 'Fireworks', 'cindra', 9,
    'fwspark|Fire Spark|star|gold|a single spark',
    'sparkler|Sparkler|twig|gold|a sparkler',
    'fwrocket|Firework|bottle|ruby/gold|a small firework rocket',
    'fwbox|Firework Box|crate|plum/ruby|a box of firework rockets',
    'fwcannon|Firework Cannon|cog|ruby/gold|a firework launcher',
    'fwtower|Sky Show Tower|house|gold/ruby+glow|a firework tower bursting into a big star'],
  ['snail', 'Lava Snails', 'cindra', 7,
    'snailegg|Snail Egg|egg|ember|a warm round snail egg',
    'snailet|Snailet|fish|ember/lilac|a tiny snail with a glowing shell',
    'volcsnail|Volcano Snail|fish|ember/lilac|a happy snail with a little volcano shell',
    'smokesnail|Smoky Snail|fish|ember/obsidian|a big snail with a smoking shell',
    'lampsnail|Lamp Snail|fish|ember/gold+glow|a snail carrying a lava lamp shell',
    'castlesnail|Castle Snail|house|ember/gold+glow|a giant snail with a castle on its shell'],
  ['jelly', 'Jelly Critters', 'nerith', 6,
    'jellyegg|Jelly Egg|egg|aurora|a jelly egg',
    'jellyling|Jellyling|fish|aurora|a tiny jellyling with two eyes',
    'floatjelly|Float Jelly|fish|aurora|a floating jelly with little arms',
    'crownjelly|Crown Jelly|fish|aurora/gold|a jelly with a bubble crown',
    'jellymum|Jelly Mum|fish|aurora/gold|a big jelly carrying smaller jellies',
    'jellyqueen|Jelly Queen|crown|aurora/gold+glow|a giant jelly queen'],
  ['racers', 'Bubble Racers', 'nerith', 9,
    'racebubble|Race Bubble|ice|glass|a racing bubble',
    'bubblescoot|Bubble Scooter|cog|glass/plum|a bubble scooter',
    'finboat|Fin Boat|fish|glass/sapphire|a bubble boat with a fin',
    'racesub|Racing Sub|fish|cream/ruby|a racing sub',
    'champsub|Champion Sub|fish|cream/gold+glow|a racing sub with a trophy flag',
    'racedome|Race Dome|house|glass/gold+glow|a bubble race stadium'],
  ['sweets', 'Star Sweets', 'vela', 5,
    'starsweet|Star Sweet|star|topaz|a star-shaped sweet',
    'cometlolly|Comet Lolly|twig|aurora|a comet lolly',
    'sweetjar|Planet Sweets|bottle|glass/aurora|a jar of planet sweets',
    'moonwafers|Moon Wafers|plank|cream/plum|a stack of moon wafers',
    'planetcake|Planet Cake|cake|plum/gold|a cake shaped like a ringed planet',
    'sweetufo|Sweet Saucer|house|cream/ruby+glow|a sweet shop shaped like a flying saucer'],
  ['station', 'Space Station', 'vela', 8,
    'rivetplate|Rivet Plate|plank|steel|a small rivet plate',
    'hatchwin|Hatch Window|ring|steel/sapphire|a round window hatch',
    'dockring|Docking Ring|ring|cream/gold|a docking ring',
    'roommod|Room Module|house|cream/sapphire|a station room module',
    'twinmod|Twin Modules|house|cream/sapphire|two modules joined together',
    'solarstation|Solar Station|house|cream/sapphire+glow|a station with solar wings',
    'ringstation|Ring Station|ring|cream/gold+glow,motes|a big ring-shaped space station'],

  /* ============================================================ EVERY WORLD */
  ['potion', 'Gloop Potions', 'any', 1,
    'goobubble|Goo Bubble|droplet|mint+glow|a single glowing bubble of green goo',
    'goovial|Goo Vial|bottle|glass/mint|a tiny corked vial of green goo',
    'gloopbottle|Gloop Bottle|jar|glass/mint+glow|a round potion bottle with Gloop peeking out',
    'twinflask|Twin Flasks|jar|glass/ember+glow|two bubbling flasks joined by a twisty glass tube',
    'potionrack|Potion Rack|crate|wood/aurora|a wooden rack of six colourful potions',
    'goocauldron|Goo Cauldron|pot|plum/mint+glow|a cauldron of glowing goo with tiny aliens swimming in it',
    'potiontower|Potion Tower|tower|glass/aurora+glow,motes|a giant flask tower with a rocket stopper and Gloop on top'],
  ['junk', 'Space Junk', 'any', 1,
    'junkbolt|Bent Bolt|pebble|iron|a bent rusty bolt',
    'junkcan|Squashed Can|jar|iron/cherry|a crumpled tin can with a faded star label',
    'junkball|Junk Ball|rock|iron/copper|a ball of squashed scrap and wires',
    'junkdrone|Junk Drone|gem|iron/copper+glow|a little patched-up drone with one glowing eye',
    'junksculpt|Junk Sculpture|totem|iron/gold|a moon-and-star sculpture welded from scraps',
    'junkbot|Junk Robot Friend|totem|copper/gold|a smiling robot made of junk parts',
    'junkrocket|Junk Rocket|tower|iron/cherry+glow|a rocket built from scraps, flames out the back'],

  ['star', 'Meteor Finds', 'any', 1,
    'scrap|Star Scrap|ore|steel/star|a twisted bit of star-metal scrap',
    'starcore|Star Core|star|star/gold+glow|a glowing golden star core'],

  ['relic', 'Relics', 'any', 1,
    'relic1|Sun Amber|gem|honey/gold+glow|a glowing amber gem with a tiny sun inside',
    'relic2|Prism Hearth|prism|flame/aurora+glow|a prism with a flame burning inside',
    'relic3|Tide Compass|compass|sapphire/gold+glow|a gold compass with a swirling tide for a needle',
    'relic4|Grove Sigil|totem|jade/glow+glow|a jade totem carved with leaves, glowing',
    'relic5|Vault Key|key|gold/aurora+glow|an ornate golden key glowing with aurora light'],

  ['bloom', 'Bloom Essence', 'any', 1,
    'bloomspark|Bloom Spark|seed|glow+glow|a tiny glowing seed of green-gold light',
    'bloommote|Bloom Mote|pearl|glow/aurora+glow|a floating mote of light with petals',
    'bloomcore|Bloom Core|orb|jade/glow+glow|a glowing jade orb with a flower inside',
    'bloomheart|Bloom Heart|orb|aurora/glow+glow|a radiant heart-shaped bloom of light'],

  ['chest', 'Chests', 'any', 1,
    'chest|Supply Chest|chest|wood/gold|a small wooden chest with gold corners and a round lock, lid slightly bulging',
    'bigchest|Treasure Chest|chest|gold/ruby+glow|a big gold-banded treasure chest glowing at the seams, gems on the lid'],

  ['wild', 'Wildcards', 'any', 1,
    'rainbow|Wildcard|orb|aurora/glow+glow,motes|a rainbow-swirled orb that could become anything'],

  /* ================================================================= ROCKET */
  ['hull', 'Rocket: Hull', 'ship', 1,
    'bolt|Bolt|cog|steel|a hex bolt with a nut',
    'boltpack|Bolt Pack|crate|steel/iron|a small box of bolts',
    'hullplate|Hull Plate|plank|steel/silver|a curved riveted hull plate'],
  ['engine', 'Rocket: Engine', 'ship', 1,
    'spring|Spring|spiral|copper|a copper spring',
    'coil|Coil|spiral|copper/gold|a thick copper coil',
    'enginecore|Engine Core|cog|iron/flame|a rocket engine nozzle glowing hot'],
  ['nav', 'Rocket: Nav Dish', 'ship', 1,
    'wire|Wire|rope|copper|a loop of wire',
    'circuit|Circuit|plank|jade/gold|a green circuit board with gold tracks',
    'navdish|Nav Dish|compass|silver/sapphire|a small nav dish with a blinking light'],
  ['tank', 'Rocket: Fuel Tank', 'ship', 1,
    'glass|Glass Pane|ice|glass|a square pane of glass',
    'tankglass|Tank Glass|crate|glass/steel|a glass tank shell in a steel frame',
    'fueltank|Fuel Tank|barrel|steel/glow|a steel fuel tank with a glowing gauge'],
  ['fuel', 'Rocket Fuel', 'ship', 1,
    'fuelore|Fuel Ore|ore|glow/jade|a rock with glowing green veins',
    'fuelcan|Fuel Canister|bottle|jade/glow|a canister of glowing fuel',
    'rocketfuel|Rocket Fuel|flask|glow/aurora+glow|a flask of bright bubbling rocket fuel'],
];

/* Items whose completion does something special. */
export const SPECIAL = {
  hullplate: { part: 'hull' }, enginecore: { part: 'engine' },
  navdish: { part: 'nav' }, fueltank: { part: 'tank' },
  rocketfuel: { fuel: true },
};
