/* The merge catalogue.
 *
 * One line per item: 'id|Name|shape|material[/accent][+deco,deco]|description'
 *   shape       — a primitive from src/artgen.ts (SHAPE_NAMES), used only for
 *                 the generated stand-in drawing until a painted sprite lands
 *   material    — a palette entry from src/artgen.ts (MAT_NAMES); the whole
 *                 lighting ramp is derived from it, so one word is a full look
 *   deco        — optional: glow, motes
 *   description — what the thing actually is, in a painter's words. It never
 *                 reaches the game: it goes into the art prompt only
 *                 (art/notes.json -> art/manifest.csv). Say what makes its
 *                 silhouette different from the step below it.
 *
 * A chain is [key, Name, world, unlockAtWorldLevel, ...items]. Tier is the
 * position in the chain; sell price and XP come off the tier curve. Chains run
 * from 4 to 8 steps — short ones are quick wins, long ones are the grind worth
 * showing off. Nothing here is code — add a line, get an item.
 */

export const CHAINS = [
  /* ============================================================ SUNNY MEADOW
     Home: an Earth that looks like a summer countryside, with the first
     hints that the sky is full of other worlds. */
  ['wood', 'Woodworks', 'earth', 1,
    'twig|Twig|twig|wood|a tiny forked twig with one green leaf',
    'branch|Branch|vine|bark/leaf|a longer curved branch with three leaves sprouting from it',
    'log|Log|log|wood|a short fat cut log lying on its side, pale rings on the end',
    'lumber|Lumber Pile|plank|wood/straw|three neat planks stacked crosswise and tied with twine',
    'cart|Timber Crate|crate|wood/iron|a sturdy wooden crate with iron corner brackets',
    'workshop|Toolchest|chest|bark/gold|a carpenter\'s chest, lid ajar, hammer and saw handles poking out, gold latch',
    'treehouse|Great Oak|tree|bark/leaf|a huge round-crowned oak with a tiny treehouse and rope ladder in its branches',
    'woodrocket|Timber Rocket|tower|wood/gold+glow|a hand-built wooden toy rocket on a launch stand, riveted planks, gold nose cone, glowing porthole'],

  ['stone', 'Rock Quarry', 'earth', 1,
    'pebble|Pebble|pebble|stone|a single small smooth grey pebble',
    'rock|Rock|rock|stone|a chunky lumpy rock with a flat top',
    'geode|Geode|geode|slate/amethyst|a rock split open to show purple crystals inside',
    'gem|Gemstone|gem|amethyst|a faceted violet gemstone, cut and gleaming',
    'statue|Stone Idol|totem|stone/moss|a squat carved stone idol with a friendly face and moss on its head',
    'obelisk|Obelisk|prism|slate/moon|a tall four-sided obelisk with a pale moonstone tip',
    'monument|Monument|arch|stone/gold|a grand stone arch with gold inlay and a star carved at its keystone'],

  ['berry', 'Berry Kitchen', 'earth', 2,
    'berry|Berry|berry|berry|one plump red berry with a little leaf',
    'berries|Berry Bunch|berrycluster|berry/leaf|a bunch of five berries on a sprig',
    'jam|Jar of Jam|jar|glass/berry|a glass jar of red jam with a gingham cloth lid',
    'pie|Berry Pie|pie|dough/berry|a round lattice-top berry pie in a dish',
    'cake|Berry Cake|cake|cream/berry|a two-tier cream cake topped with berries',
    'feast|Harvest Feast|basket|straw/cherry|a picnic hamper overflowing with pies, jam and fruit',
    'jamfactory|Jam Kitchen|house|cream/berry+glow|a cute cottage kitchen with a giant jam pot bubbling on the roof'],

  ['water', 'Waterworks', 'earth', 2,
    'dew|Dewdrop|droplet|water|a single bright dewdrop',
    'puddle|Puddle|bubble|water|a small round puddle with a ripple',
    'jug|Water Jug|jar|glass/water|a round glass jug full of water with a handle',
    'barrel|Rain Barrel|barrel|wood/water|a wooden rain barrel brimming with water',
    'fountain|Fountain|pot|stone/water|a round stone fountain with a little water spout',
    'aqueduct|Aqueduct|arch|stone/water|a short three-arched stone aqueduct with water running along the top',
    'watertower|Water Tower|tower|wood/water+glow|a tall round water tower on stilts, painted tank with a sparkling spout'],

  ['grass', 'Hay Meadow', 'earth', 3,
    'grass|Grass Tuft|fern|grass|a small tuft of bright grass',
    'hay|Hay Bundle|grain|straw|a loose bundle of golden hay tied at the middle',
    'bale|Hay Bale|barrel|straw/rope|a round rolled hay bale bound with rope',
    'hat|Straw Hat|basket|straw/cloth|a wide-brimmed straw hat with a red ribbon',
    'scarecrow|Scarecrow|totem|cloth/straw|a cheerful scarecrow on a post with a patched shirt',
    'harvest|Golden Harvest|crate|straw/gold|a wagon heaped with golden wheat sheaves, gold trim'],

  ['flower', 'Flower Beds', 'earth', 3,
    'bulbseed|Flower Seed|seed|moss|a tiny striped seed',
    'sprig|Green Sprig|sprout|leaf|a seedling with two round leaves',
    'bloombud|Bud|bud|rose|a closed pink flower bud on a stem',
    'bouquet|Bouquet|flower|rose/leaf|a hand-tied bouquet of pink flowers',
    'garland|Garland|blossom|lilac/gold|a looped garland of lilac flowers with a gold ribbon',
    'flowercrown|Flower Crown|crown|rose/gold|a circlet of roses woven on a thin gold band',
    'flowerarch|Blossom Arch|arch|rose/leaf+glow|a garden arch covered in blooming roses, petals drifting'],

  ['honey', 'Honeyworks', 'earth', 4,
    'nectar|Nectar Drop|droplet|honey|a small drop of golden nectar',
    'honeydrop|Honey Bead|bubble|honey|a round glossy bead of honey',
    'honeycomb|Honeycomb|honey|honey|a slab of hexagonal honeycomb dripping honey',
    'honeypot|Honey Pot|pot|clay/honey|a round clay honey pot with a wooden dipper',
    'beehive|Beehive|sack|honey/straw|a domed straw skep beehive with a round door',
    'royaljelly|Royal Jelly|orb|honey/gold+glow|a glowing golden orb of royal jelly on a tiny gold stand',
    'honeypalace|Honey Palace|tower|honey/gold+glow|a tall honeycomb tower with golden domes and happy little bees'],

  ['mush', 'Forest Floor', 'earth', 4,
    'caplet|Tiny Cap|bud|spore|a tiny single mushroom button',
    'toadstool|Toadstool|mushroom|ruby/cream|a red-capped toadstool with cream spots',
    'mushring|Cap Cluster|berrycluster|fungus/cream|a cluster of three mushrooms of different heights',
    'fairyring|Fairy Ring|flower|spore/glow|a ring of small glowing mushrooms around a mossy patch',
    'mossheart|Moss Heart|orb|moss/glow|a heart-shaped mossy stone glowing softly green'],

  ['cloth', 'The Weavery', 'earth', 5,
    'fibre|Plant Fibre|rope|straw|a short twist of pale plant fibre',
    'thread|Spool of Thread|spiral|cloth|a wooden spool wound with red thread',
    'yarn|Ball of Yarn|orb|rose/cloth|a round ball of pink yarn with a loose end',
    'clothbolt|Bolt of Cloth|cloth|cloth|a rolled bolt of red cloth',
    'quilt|Patch Quilt|cloth|lilac/mint|a folded patchwork quilt in lilac and mint squares',
    'tapestry|Tapestry|scroll|rose/gold|a hanging tapestry on a gold rod, showing a rocket among stars',
    'spacesuit|Patchwork Spacesuit|cloth|cream/sapphire+glow|a puffy hand-sewn spacesuit with patches and a round glass helmet'],

  ['feather', 'The Nesting', 'earth', 5,
    'down|Down Tuft|cloud|cream|a soft tuft of white down',
    'plume|Feather|feather|dusk/silver|a single long violet feather',
    'nest|Twig Nest|basket|bark/straw|a round twig nest',
    'speckegg|Speckled Egg|egg|cream/rose|a speckled egg sitting in a scrap of nest',
    'songbird|Songbird|bird|sapphire/gold|a round blue songbird singing, gold chest',
    'aviary|Aviary|house|glass/leaf|a domed glass birdhouse with vines and two birds inside'],

  ['clay', 'The Pottery', 'earth', 6,
    'mud|Clay Daub|pebble|clay|a small wet dab of terracotta clay',
    'claylump|Clay Lump|rock|clay|a fist-sized lump of clay with finger marks',
    'claypot|Clay Pot|pot|clay|a plain round clay pot',
    'urn|Painted Urn|jar|clay/rose|a tall urn painted with pink swirls',
    'kiln|Kiln|house|clay/flame|a small domed brick kiln with fire glowing in its mouth',
    'porcelain|Porcelain Vase|pot|cream/sapphire|an elegant white vase with blue patterns and a gold rim'],

  ['garden', 'Meadow Wilds', 'earth', 7,
    'grub|Grub|cocoon|cream/moss|a chubby smiling grub',
    'chrysalis|Chrysalis|cocoon|jade/gold|a jade chrysalis hanging from a twig with gold dots',
    'flutter|Flutterwing|butterfly|lilac/topaz|a lilac butterfly with golden wing spots',
    'swarm|Bloom Swarm|butterfly|rose/gold+glow|three butterflies swirling together in a ring of light',
    'meadowheart|Meadow Heart|orb|leaf/glow+glow|a glowing green heart-shaped seed wrapped in leaves, radiant'],

  ['veggie', 'Veggie Patch', 'earth', 8,
    'vegseed|Veggie Seed|seed|clay|a small brown seed',
    'seedling|Seedling|sprout|leaf|a sprouting seedling in a pinch of soil',
    'carrot|Carrot|fruit|peach/leaf|a fat orange carrot with a leafy top',
    'vegbundle|Veggie Bundle|grain|peach/leaf|a carrot, a leek and a radish tied together',
    'vegcrate|Veggie Crate|crate|wood/peach|a wooden crate heaped with colourful vegetables',
    'vegstall|Market Stall|house|cloth/peach|a striped-awning market stall stacked with vegetables',
    'giantpumpkin|Prize Pumpkin|fruit|peach/gold+glow|a gigantic prize pumpkin with a blue rosette and gold ribbon'],

  ['stargaze', 'Stargazing', 'earth', 9,
    'lenschip|Lens Chip|ice|glass|a small round chip of glass',
    'lens|Lens|gem|glass/copper|a round polished lens in a thin copper ring',
    'spyglass|Spyglass|bottle|copper/glass|a brass spyglass, extended',
    'telescope|Telescope|lantern|copper/sapphire|a stubby brass telescope on a wooden tripod',
    'observatory|Observatory|house|cream/sapphire+glow|a round white observatory with an open dome and a telescope peeking out',
    'planetarium|Planetarium|house|sapphire/star+glow,motes|a grand domed planetarium, its roof open to a projected starry sky'],

  ['visitor', 'Little Visitors', 'earth', 10,
    'oddegg|Odd Egg|egg|mint/star|a mint-green egg with little glowing star spots',
    'blinky|Blinky|slime|mint|a tiny round mint alien blob with one big blinking eye',
    'alienkid|Little Alien|slime|mint/lilac|a small green alien with two antennae and a big smile',
    'alienexplorer|Alien Explorer|slime|mint/steel|the little alien in a bubble helmet with a backpack',
    'saucer|Flying Saucer|planet|steel/glow+glow|a small round flying saucer with a glass dome and ring of lights',
    'alienfamily|Saucer Family|planet|silver/mint+glow|a big saucer with three little aliens waving from its dome',
    'mothership|Mothership|planet|silver/aurora+glow,motes|a huge friendly mothership, glowing rings of windows, beams of light underneath'],

  /* ============================================================= CRATER CAMP
     A lilac moon: craters, crystals, robot friends and bouncy alien pets. */
  ['moon', 'Moon Rocks', 'luna', 1,
    'mrock|Moon Rock|pebble|moon|a small pale lilac moon pebble with a tiny crater',
    'mcrystal|Moon Shard|crystal|moon/frost|a single frosty moon crystal shard',
    'mcore|Moon Core|gem|dusk/moon|a round cut violet core stone',
    'mstar|Moon Star|star|moon/star|a chunky five-point star carved from moonstone',
    'moonorb|Moon Orb|planet|moon/star+glow|a small glowing moon with craters and a star ring',
    'moonstatue|Moon Idol|mask|moon/silver|a carved moonstone face with calm closed eyes and silver trim',
    'moonbase|Moon Outpost|house|silver/moon+glow|a cosy domed moon habitat with round windows and an antenna',
    'moonpalace|Lunar Palace|tower|moon/star+glow,motes|a shining lilac palace of domes and spires on a crater rim'],

  ['glow', 'Glow Garden', 'luna', 1,
    'spore|Glow Spore|seed|spore|a tiny violet spore with a soft glow',
    'bulb|Glow Bulb|bud|glow|a round glowing flower bulb',
    'glowflower|Glow Flower|flower|glow/spore|a cyan glowing flower with violet centre',
    'starbloom|Star Bloom|blossom|star/glow|a star-shaped golden blossom',
    'glowtree|Glow Tree|tree|spore/glow+glow|a small tree with glowing round fruit',
    'glowgrove|Glow Grove|house|spore/glow|a greenhouse dome full of glowing plants'],

  ['dust', 'Dust Flats', 'luna', 2,
    'dustpinch|Dust Pinch|pebble|sand|a small heap of grey-lilac moon dust',
    'dustclump|Dust Clump|rock|sand/slate|a packed clump of moon dust',
    'regolith|Regolith Brick|plank|slate/sand|a single pressed moon-dust brick',
    'moonbrick|Moon Brick|crate|slate/moon|a neat stack of moon bricks',
    'moonwall|Moon Wall|arch|slate/moon|a curved moon-brick wall with a round doorway',
    'moontown|Dome Town|house|slate/glow+glow|a little town of moon-brick domes with warm glowing windows'],

  ['ice', 'Ice Fields', 'luna', 2,
    'frostchip|Frost Chip|ice|frost|a small chip of frost',
    'iceshard|Ice Shard|crystal|ice|a pointed pale-blue ice shard',
    'icecore|Ice Core|gem|ice/frost|a clear round ice core with a frozen bubble inside',
    'snowstar|Snow Star|snowflake|frost/ice|a big six-point snowflake',
    'glacier|Glacier Block|crate|ice/deepsea|a big cube of layered glacier ice',
    'icecastle|Ice Castle|tower|ice/frost|a small ice castle with two turrets',
    'icepalace|Frost Citadel|tower|ice/aurora+glow|a tall glittering ice citadel with aurora light inside'],

  ['crystal', 'Crystal Vein', 'luna', 3,
    'shardlet|Crystal Chip|pebble|crystal|a tiny cyan crystal chip',
    'prismlet|Prism Shard|crystal|crystal|a single long cyan crystal',
    'prismcore|Prism Core|prism|crystal/aurora|a cluster of three crystals on a rock base',
    'prismheart|Prism Heart|planet|crystal/aurora+glow|a heart-shaped crystal glowing from inside',
    'prismtower|Prism Spire|tower|crystal/aurora|a tall spire of stacked crystals',
    'prismgarden|Crystal Garden|house|crystal/aurora+glow|a whole garden of crystal spires under a glass dome',
    'prismthrone|Crystal Throne|arch|crystal/gold+glow,motes|a radiant throne of cyan crystal with gold arms'],

  ['lantern', 'Lanternworks', 'luna', 4,
    'wick|Wick|rope|cloth|a short candle wick',
    'lampglass|Lamp Glass|jar|glass|an empty glass lamp chimney',
    'moonlamp|Moon Lantern|lantern|gold/glow|a gold lantern with a glowing moon inside',
    'beacon|Beacon|lantern|copper/flame+glow|a big copper signal beacon with a bright flame',
    'lighthouse|Lighthouse|tower|cream/flame|a striped lighthouse on a crater rock',
    'starbeacon|Star Beacon|tower|gold/star+glow,motes|a golden lighthouse beaming a star-shaped light into space'],

  ['silver', 'Silver Lode', 'luna', 4,
    'silverore|Silver Ore|ore|silver|a rock with shiny silver veins',
    'silvernug|Silver Nugget|pebble|silver|a lumpy silver nugget',
    'silveringot|Silver Ingot|ingot|silver|a neat silver bar',
    'silvercup|Silver Chalice|pot|silver/amethyst|a silver goblet set with violet gems',
    'silvercrown|Silver Crown|crown|silver/moon|a silver crown with moonstone points',
    'silverthrone|Silver Throne|arch|silver/amethyst+glow|a tall silver throne with a crescent-moon back'],

  ['comet', 'Comet Trail', 'luna', 5,
    'cometdust|Comet Dust|pebble|dusk|a sparkling pinch of violet comet dust',
    'cometice|Comet Ice|ice|frost/dusk|a dirty-snowball chunk of comet ice',
    'cometcore|Comet Core|comet|star/gold|a small golden comet with a short tail',
    'cometstone|Comet Stone|boulder|dusk/star+glow|a big comet rock trailing sparkles',
    'cometheart|Comet Heart|planet|star/aurora+glow|a blazing comet heart with a long aurora tail'],

  ['lunamoth', 'Crater Wings', 'luna', 6,
    'mothegg|Moth Egg|egg|moon/spore|a small lilac egg on a leaf',
    'mothcocoon|Silk Cocoon|cocoon|cream/moon|a silky cream cocoon',
    'lunamothi|Luna Moth|butterfly|mint/moon|a pale green moth with long tails',
    'moonmoth|Moon Moth|butterfly|aurora/star+glow|a big glowing moth with star-patterned wings',
    'craterheart|Crater Heart|planet|moon/glow+glow|a glowing moon-heart wrapped in moth wings, radiant'],

  ['moonpup', 'Moon Critters', 'luna', 7,
    'wobbleegg|Wobble Egg|egg|lilac/moon|a lilac egg wobbling, a tiny crack at the top',
    'blip|Blip|slime|lilac|a tiny round lilac alien critter with big eyes',
    'moonpup|Moon Pup|slime|lilac/silver|a puppy-like moon alien with floppy antenna-ears',
    'hoppup|Hop Pup|slime|lilac/sapphire|the moon pup mid-bounce, spring-like feet',
    'craterhound|Crater Hound|slime|moon/sapphire|a bigger six-legged moon hound with a silver collar',
    'starhound|Star Hound|slime|dusk/star+glow|a hound with a coat of twinkling stars',
    'moonguardian|Moon Guardian|slime|moon/gold+glow,motes|a majestic glowing guardian beast with a crescent-moon crest'],

  ['rover', 'Rover Yard', 'luna', 8,
    'screw|Screw|cog|steel|a single fat steel screw',
    'wheel|Rover Wheel|cog|steel/slate|a chunky treaded rover wheel',
    'axle|Wheel Axle|plank|steel/slate|two wheels joined on an axle',
    'toyrover|Little Rover|crate|steel/sapphire|a small four-wheeled rover with a camera head',
    'moonbuggy|Moon Buggy|boat|silver/sapphire|an open two-seat moon buggy with a dish on the back',
    'bigrover|Six-Wheel Rover|crate|silver/topaz|a big six-wheeled rover with solar wings and a drill arm',
    'roverbase|Rover Garage|house|silver/sapphire+glow|a domed rover garage with a buggy parked out front',
    'launchpad|Launch Pad|tower|silver/flame+glow,motes|a moon launch pad with a small rocket ready to lift off'],

  ['helium', 'Helium Wells', 'luna', 9,
    'gaswisp|Gas Wisp|cloud|glow|a small swirling wisp of glowing gas',
    'gasbubble|Gas Bubble|bubble|glow/lilac|a round bubble of glowing gas',
    'gasflask|Gas Flask|flask|glass/glow|a round flask with glowing gas inside',
    'gascan|Gas Canister|bottle|steel/glow|a stubby steel canister with a valve and gauge',
    'gastank|Helium Tank|barrel|silver/glow|a big round pressure tank with pipes and a glowing window',
    'fusioncell|Fusion Cell|orb|glow/aurora+glow,motes|a glowing sphere of plasma held in silver rings',
    'fusionreactor|Fusion Reactor|tower|silver/aurora+glow,motes|a tall silver reactor with a glowing plasma ring at its centre'],

  ['meteorite', 'Meteorite Field', 'luna', 10,
    'spacegrit|Space Grit|pebble|iron|a small dark pitted grain of meteorite',
    'meteorite|Meteorite|rock|iron/slate|a dark scorched meteorite with a melted crust',
    'ironmeteor|Iron Meteorite|ore|iron/silver|a heavy meteorite with polished silver cross-hatching',
    'pallasite|Pallasite|geode|iron/jade|a sliced meteorite slab full of green gem crystals',
    'meteorgeode|Star Geode|geode|dusk/star+glow|an opened meteorite glittering with starlight crystals',
    'starmetal|Star Metal|ingot|silver/star+glow|a glowing ingot of star metal with a sparkle',
    'meteormonument|Skyfall Stone|boulder|iron/star+glow,motes|a huge meteorite standing upright on a plinth, glowing veins'],

  ['dish', 'Signal Dishes', 'luna', 11,
    'antwire|Antenna Wire|rope|copper|a coil of copper antenna wire',
    'antenna|Antenna|key|silver/copper|a tall thin antenna with a blinking tip',
    'minidish|Mini Dish|compass|silver|a small satellite dish on a stand',
    'radar|Radar Dish|compass|silver/sapphire|a larger radar dish tilted to the sky',
    'signaltower|Signal Tower|tower|silver/sapphire+glow|a lattice tower with dishes and blinking lights',
    'deeparray|Deep Space Array|tower|silver/aurora+glow,motes|three giant dishes pointed up, beams of light between them',
    'starhorn|Listening Spire|tower|gold/aurora+glow,motes|a golden spire of dishes catching a beam of light from the stars'],

  ['moonmelon', 'Crater Farm', 'luna', 12,
    'moonseed|Moon Seed|seed|lilac|a pale lilac seed',
    'moonsprout|Moon Sprout|sprout|mint/lilac|a sprout with curly lilac leaves',
    'moonmelon|Moon Melon|fruit|mint/lilac|a round pale-green melon with lilac stripes',
    'meloncrate|Melon Crate|crate|steel/mint|a steel crate full of moon melons',
    'moondome|Farm Dome|house|glass/mint+glow|a glass farm dome full of melon vines',
    'moonfarm|Crater Farmstead|house|mint/lilac+glow,motes|a whole crater of farm domes, melon patches and a little windmill'],

  /* ============================================================ EMBER HOLLOW
     A volcanic world at dusk: magma, forges, basalt and fire-loving creatures. */
  ['magma', 'Magma Works', 'cindra', 1,
    'ember|Ember|ember|ember|a small glowing ember',
    'cinder|Cinder|coal|smoke/ember|a dark cinder with orange glowing cracks',
    'lavablob|Lava Blob|slime|magma/flame|a wobbly blob of bright lava',
    'fireopal|Fire Opal|gem|flame/gold|a cut orange fire opal flickering inside',
    'suncore|Sun Core|orb|flame/gold+glow|a small blazing orb like a pocket sun',
    'sunforge|Sun Forge|anvil|obsidian/flame|an obsidian anvil with a sun blazing on it',
    'toyvolcano|Little Volcano|boulder|obsidian/magma+glow|a cute cone volcano puffing a smoke ring, lava down one side',
    'sunengine|Sun Engine|cog|gold/flame+glow,motes|a golden engine of gears with a blazing sun at its heart'],

  ['shroom', 'Ash Garden', 'cindra', 1,
    'sporecap|Ash Spore|seed|smoke|a small grey spore',
    'ashroom|Ash Shroom|mushroom|smoke/ember|a grey mushroom with ember-orange gills',
    'bigshroom|Great Shroom|mushroom|fungus/flame|a tall salmon mushroom with a wide cap',
    'glowcap|Glow Cap|mushroom|ember/glow+glow|a mushroom glowing warm orange',
    'shroomtree|Shroom Tree|tree|fungus/ember|a tree made of stacked mushroom caps',
    'shroomcity|Shroom Hollow|house|fungus/glow|a mushroom house with round windows and a chimney',
    'shroomcastle|Shroom Castle|tower|fungus/ember+glow|a castle of giant glowing mushroom towers'],

  ['iron', 'Iron Forge', 'cindra', 2,
    'ironore|Iron Ore|ore|iron|a rock with rusty iron veins',
    'ironnug|Iron Nugget|pebble|iron|a dull iron nugget',
    'ironingot|Iron Ingot|ingot|iron|a neat iron bar',
    'ironanvil|Anvil|anvil|steel/iron|a classic steel anvil',
    'ironcrown|Iron Crown|crown|steel/rust|a heavy iron crown with rivets',
    'ironbot|Iron Bot|totem|iron/flame|a small boxy iron robot with an ember glowing in its chest',
    'ironmech|Great Mech|totem|steel/flame+glow|a big friendly walking mech with furnace eyes'],

  ['obsid', 'Obsidian Cut', 'cindra', 2,
    'obchip|Obsidian Chip|pebble|obsidian|a small glossy black-purple chip',
    'obshard|Obsidian Shard|crystal|obsidian/dusk|a sharp glossy obsidian shard',
    'obblade|Obsidian Blade|prism|obsidian/ember|a polished obsidian blade with an ember edge',
    'obmirror|Dark Mirror|ring|obsidian/silver+glow|a round obsidian mirror in a silver frame',
    'obthrone|Obsidian Throne|arch|obsidian/gold|a glossy obsidian throne with gold trim',
    'obcitadel|Obsidian Citadel|tower|obsidian/ember+glow,motes|a tall black-glass citadel with ember light in every window'],

  ['glassw', 'Glassworks', 'cindra', 3,
    'sandpinch|Hot Sand|pebble|sand|a small heap of hot orange sand',
    'moltenglass|Molten Glass|slime|glass/flame|a glowing gob of molten glass',
    'glassbead|Glass Bead|pearl|glass/aurora|a round swirled glass bead',
    'glassvase|Glass Vase|bottle|glass/mint|a tall green glass vase',
    'glasslily|Glass Lily|flower|glass/aurora|a delicate glass lily',
    'glassdome|Glass Dome|house|glass/aurora+glow|a blown-glass dome with a tiny garden inside',
    'glasspalace|Glass Palace|tower|glass/aurora+glow,motes|a crystal-clear palace of blown glass throwing rainbows'],

  ['forge', 'The Smithy', 'cindra', 4,
    'coallump|Coal Lump|coal|coal|a lump of coal',
    'coalbrick|Coal Brick|plank|coal/smoke|a pressed coal brick',
    'forgefire|Forge Fire|flame|flame/ember+glow|a crackling fire in a small stone hearth',
    'bellows|Bellows|sack|bark/copper|a leather bellows with copper nozzle',
    'greatforge|Great Forge|house|iron/flame|an iron forge building with a glowing furnace door',
    'foundry|Star Foundry|house|iron/star+glow,motes|a huge foundry pouring a glowing river of star metal'],

  ['spice', 'Spice Kiln', 'cindra', 4,
    'pepperpod|Pepper Pod|seed|rust|a small red hot pepper',
    'spicepouch|Spice Pouch|sack|clay/flame|a tied pouch of red spice',
    'spicejar|Spice Jar|jar|glass/rust|a glass jar of layered spices',
    'spicecrate|Spice Crate|crate|wood/flame|a crate of spice sacks and jars',
    'spicefeast|Ember Feast|soup|clay/flame|a steaming pot of fiery stew',
    'spicebazaar|Spice Bazaar|house|cloth/flame+glow|a tented market stall hung with spice sacks and lanterns'],

  ['copper', 'Copper Seam', 'cindra', 5,
    'copperore|Copper Ore|ore|copper|a rock with copper-orange veins',
    'coppernug|Copper Nugget|pebble|copper|a shiny copper nugget',
    'copperingot|Copper Ingot|ingot|copper|a copper bar',
    'copperbell|Copper Bell|bell|copper/gold|a copper hand bell',
    'coppercog|Great Cog|cog|copper/gold|a large copper cog wheel',
    'copperclock|Copper Clock|compass|copper/gold+glow|a round copper clock with visible gears',
    'automaton|Copper Automaton|totem|copper/gold+glow,motes|a graceful copper clockwork figure with a wind-up key',
    'clocktower|Clockwork Tower|tower|copper/gold+glow,motes|a tall copper clock tower full of turning gears'],

  ['phoenix', 'Ashfall Wings', 'cindra', 6,
    'ashfeather|Ash Feather|feather|smoke/ember|a grey feather with an ember tip',
    'emberegg|Ember Egg|egg|ember/gold|an orange egg with glowing cracks',
    'firebird|Firebird|bird|flame/gold+glow|a round little bird made of flame',
    'phoenix|Phoenix|bird|gold/aurora+glow|a grand phoenix with sweeping flame wings',
    'hollowheart|Hollow Heart|orb|flame/glow+glow|a burning heart-shaped core, radiant'],

  ['salamander', 'Fire Critters', 'cindra', 7,
    'warmegg|Warm Egg|egg|ember|a small orange egg giving off heat shimmer',
    'newt|Flicker Newt|fish|ember/flame|a tiny orange newt with a flickering flame tail',
    'salamander|Salamander|fish|flame/magma|a chunky salamander with fire along its back',
    'lavalizard|Lava Lizard|fish|magma/obsidian|a bigger lizard with obsidian scales and glowing spots',
    'magmadrake|Magma Drake|bird|magma/gold+glow|a small friendly dragon of lava with gold horns',
    'emberwyrm|Ember Wyrm|bird|flame/gold+glow,motes|a great gentle fire dragon curled around a volcano peak'],

  ['basalt', 'Basalt Columns', 'cindra', 8,
    'basaltchip|Basalt Chip|pebble|slate|a small dark basalt chip',
    'basaltblock|Basalt Block|rock|slate/obsidian|a squared basalt block',
    'hexcolumn|Hex Column|prism|slate/obsidian|a single six-sided basalt column',
    'columnstack|Column Stack|prism|slate/ember|three hex columns of different heights',
    'basaltarch|Basalt Gate|arch|slate/ember+glow|a gate made of hex columns with lava glowing underneath',
    'causeway|Giant\'s Steps|tower|slate/flame+glow|a towering staircase of hex columns glowing at the seams',
    'basaltcrown|Basalt Crown|crown|obsidian/gold+glow,motes|a crown of hex columns with lava glowing between them'],

  ['sulfur', 'Sulfur Springs', 'cindra', 9,
    'sulfurdust|Sulfur Dust|pebble|topaz|a small heap of bright yellow sulfur dust',
    'sulfurcrystal|Sulfur Crystal|crystal|topaz|a single yellow sulfur crystal',
    'sulfurcluster|Sulfur Cluster|geode|topaz/obsidian|a spiky cluster of yellow crystals on dark rock',
    'brimstone|Brimstone Heart|gem|topaz/flame+glow|a glowing yellow brimstone gem with fire inside'],

  ['steam', 'Steamworks', 'cindra', 10,
    'steampuff|Steam Puff|cloud|smoke|a small white puff of steam',
    'steampipe|Steam Pipe|plank|copper/smoke|a bent copper pipe with a puff at the end',
    'valve|Pressure Valve|cog|copper/ruby|a copper valve wheel with a red handle',
    'boiler|Boiler|barrel|copper/flame|a round copper boiler with a gauge and a firebox',
    'steamengine|Steam Engine|cog|iron/copper|a chugging steam engine with pistons and a flywheel',
    'geoplant|Geothermal Plant|house|iron/flame+glow|a small power station on a vent, pipes and steam towers',
    'steamtitan|Steam Titan|totem|copper/flame+glow,motes|a giant brass robot puffing steam from its shoulders'],

  ['emberfruit', 'Ember Orchard', 'cindra', 11,
    'charseed|Char Seed|seed|coal/ember|a black seed with an ember glow',
    'embersprout|Ember Sprout|sprout|ember|a sprout with orange flame-shaped leaves',
    'firefruit|Fire Fruit|fruit|flame/magma|a round fruit with flame-coloured skin',
    'fruitbasket|Fire Fruit Basket|basket|straw/flame|a basket of glowing fire fruit',
    'embertree|Ember Tree|tree|obsidian/flame+glow|a black-barked tree heavy with glowing fire fruit',
    'embergrove|Ember Grove|tree|flame/gold+glow,motes|a ring of glowing fire-fruit trees around a warm lava pool'],

  ['rubyc', 'Ruby Caves', 'cindra', 12,
    'redchip|Red Chip|pebble|ruby|a tiny red stone chip',
    'rubyshard|Ruby Shard|crystal|ruby|a single raw ruby crystal',
    'cutruby|Cut Ruby|gem|ruby|a brilliant cut ruby',
    'rubyring|Ruby Ring|ring|gold/ruby|a gold ring set with a ruby',
    'rubyscepter|Ruby Sceptre|key|gold/ruby+glow|a gold sceptre topped with a big ruby',
    'rubycrown|Ruby Crown|crown|gold/ruby+glow|a tall gold crown studded with rubies',
    'rubyidol|Ruby Idol|mask|ruby/gold+glow,motes|a giant glowing ruby carved into a smiling face, gold base'],

  /* ========================================================= TIDAL SHALLOWS
     An ocean planet of bright shallows, reefs, sunken cities and sea aliens. */
  ['shellc', 'Shell Bed', 'nerith', 1,
    'shellchip|Shell Chip|pebble|shell|a small pink shell fragment',
    'seashell|Sea Shell|shell|shell|a single pink scallop shell',
    'bigshell|Great Shell|shell|coral/cream|a big spiral conch',
    'nautilus|Nautilus|spiral|cream/coral|a striped nautilus shell',
    'shellhorn|Shell Horn|bell|shell/gold|a conch horn with a gold mouthpiece',
    'shellthrone|Shell Throne|arch|pearl/coral|a throne made of a giant scallop shell',
    'shellpalace|Shell Palace|tower|pearl/coral+glow,motes|a palace built of giant spiral shells on a pink sandbar'],

  ['kelp', 'Kelp Forest', 'nerith', 1,
    'kelpleaf|Kelp Leaf|leaf|kelp|a single wavy kelp leaf',
    'kelpfrond|Kelp Frond|fern|kelp|a tall kelp frond with air bladders',
    'kelpcoil|Kelp Coil|rope|kelp/jade|a coiled rope of kelp',
    'kelpbale|Kelp Bale|basket|kelp/moss|a bundled bale of kelp',
    'kelpgrove|Kelp Grove|tree|kelp/jade|a tall swaying kelp tree',
    'kelpheart|Tide Grove|house|kelp/glow|a hut woven from kelp with glowing windows',
    'kelpcathedral|Kelp Cathedral|tower|kelp/glow+glow|a towering spire of woven kelp and glowing lanterns'],

  ['pearlc', 'Pearl Diving', 'nerith', 2,
    'grit|Grain of Grit|pebble|sand|a tiny grain of sand',
    'seedpearl|Seed Pearl|pearl|cream|a tiny pearl in a small open shell',
    'pearl|Pearl|pearl|pearl+glow|a big lustrous pearl in an oyster',
    'pearlstrand|Pearl Strand|berrycluster|pearl/silver|a looped strand of pearls',
    'pearlcrown|Pearl Crown|crown|pearl/silver|a silver crown set with pearls',
    'pearlorb|Pearl Orb|orb|pearl/aurora+glow|a huge glowing pearl on a coral stand',
    'pearlpalace|Pearl Palace|tower|pearl/coral+glow,motes|a palace of pearly domes rising from the waves'],

  ['coralc', 'Coral Reef', 'nerith', 2,
    'coralbud|Coral Bud|bud|coral|a tiny coral bud',
    'coralsprig|Coral Sprig|coral|coral|a small branching coral',
    'coralfan|Coral Fan|coral|rose/coral|a wide pink sea fan',
    'coralcrown|Coral Crown|crown|coral/gold|a crown of branching coral',
    'coralpalace|Coral Palace|tower|rose/pearl|a coral tower with pearl windows',
    'coralcity|Coral City|house|coral/pearl+glow|a cluster of coral towers and domes, fish swimming around',
    'reefcrown|Reef Crown|crown|coral/pearl+glow,motes|a giant crown of living coral set with pearls, fish circling it'],

  ['fishc', 'Fish Market', 'nerith', 3,
    'minnow|Minnow|fish|mint|a tiny mint fish',
    'silverfish|Silverfin|fish|silver/sapphire|a sleek silver fish',
    'bigfish|Big Catch|fish|sapphire/gold|a big round blue fish',
    'fishcatch|Full Net|basket|rope/sapphire|a net bulging with fish',
    'fishfeast|Tide Feast|soup|shell/mint|a steaming seafood pot',
    'fishhall|Harbour Market|house|shell/sapphire+glow|a seaside market hall with fish-shaped weathervane and striped awnings'],

  ['tide', 'Tide Pools', 'nerith', 3,
    'bubblet|Sea Bubble|bubble|water|a single sea bubble',
    'seafoam|Sea Foam|cloud|frost/water|a puff of sea foam',
    'tidewave|Tide Swell|wave|deepsea/frost|a curling blue wave',
    'tidalorb|Tidal Orb|planet|deepsea/aurora+glow|a glowing orb of swirling seawater',
    'tidalheart|Tidal Heart|orb|sapphire/glow+glow|a blue heart-shaped gem with a tide inside'],

  ['salt', 'Salt Pans', 'nerith', 4,
    'saltgrain|Salt Grain|pebble|cream|a small heap of salt',
    'saltcake|Salt Cake|ingot|cream/frost|a pressed salt cake',
    'saltbrick|Salt Brick|crate|cream/ice|a stack of salt bricks',
    'saltpillar|Salt Pillar|crystal|cream/frost|a tall salt crystal pillar',
    'salttemple|Salt Temple|tower|cream/aurora|a white salt temple with a domed roof',
    'saltlight|Salt Lighthouse|tower|cream/aurora+glow,motes|a tall white salt-crystal lighthouse beaming over the sea'],

  ['sunkn', 'Sunken Finds', 'nerith', 5,
    'driftbit|Driftwood Bit|twig|bone/kelp|a small bleached stick of driftwood',
    'driftwood|Driftwood|log|bone/kelp|a twisted driftwood log with kelp',
    'driftboat|Beached Skiff|boat|bark/cloth|a little wooden skiff with a patched sail',
    'sunkenchest|Sunken Chest|chest|bark/gold+glow|a barnacled treasure chest spilling gold',
    'sunkenidol|Drowned Idol|mask|jade/gold|a jade idol face with gold eyes',
    'galleon|Sunken Galleon|boat|bark/kelp+glow|a sunken ship on its side, covered in coral',
    'sunkencity|Drowned City|tower|jade/pearl+glow,motes|ancient domed city towers rising out of the shallows, glowing windows'],

  ['lumin', 'Deep Lights', 'nerith', 6,
    'glowplankton|Plankton Mote|pearl|spore+glow|a tiny glowing speck of plankton',
    'jellybell|Jelly Bell|bell|lilac/glow+glow|a small glowing jellyfish',
    'deeplantern|Deep Lantern|lantern|deepsea/glow+glow|an anglerfish-style lantern with a glowing lure',
    'abyssorb|Abyss Orb|planet|deepsea/aurora+glow|a dark orb with glowing deep-sea lights',
    'shallowheart|Shallow Heart|orb|mint/glow+glow|a glowing sea-green heart, radiant'],

  ['squid', 'Reef Critters', 'nerith', 7,
    'bubbleegg|Bubble Egg|egg|water/coral|a clear jelly egg with a tiny critter curled inside',
    'squidlet|Squidlet|slime|coral|a tiny pink squid with big eyes',
    'tentapal|Tentacle Pal|slime|coral/mint|a round alien octopus waving four arms',
    'reefsquid|Reef Squid|slime|rose/coral|a bigger squid with a coral-crest hat',
    'glowocto|Glow Octo|slime|lilac/glow+glow|an octopus with glowing spots along its arms',
    'krakenpal|Kraken Pal|slime|deepsea/coral+glow|a big friendly kraken hugging a shell',
    'tidekraken|Tide Kraken|slime|deepsea/pearl+glow,motes|a giant gentle kraken wearing a pearl crown, arms curled around a wave'],

  ['turtle', 'Turtle Cove', 'nerith', 8,
    'turtleegg|Turtle Egg|egg|cream|a round leathery egg half buried in sand',
    'hatchling|Hatchling|fish|jade|a tiny sea turtle hatchling',
    'seaturtle|Sea Turtle|fish|jade/sand|a grown sea turtle with a patterned shell',
    'islandturtle|Island Turtle|house|jade/leaf+glow|an enormous turtle with a tiny palm island on its shell'],

  ['harbour', 'Harbour', 'nerith', 9,
    'knot|Rope Knot|rope|rope|a single tied rope knot',
    'float|Net Float|bubble|glass/rope|a glass fishing float in a rope net',
    'buoy|Buoy|bell|coral/cream|a striped red-and-white buoy with a bell',
    'anchor|Anchor|key|iron/rope|an iron anchor with a coiled rope',
    'shipwheel|Ship\'s Wheel|cog|wood/gold|a wooden ship\'s wheel with gold caps',
    'divebell|Diving Bell|bell|copper/glass+glow|a round copper diving bell with portholes',
    'submarine|Submarine|boat|topaz/copper+glow,motes|a round yellow submarine with portholes and a periscope'],

  ['seaglass', 'Sea Glass', 'nerith', 10,
    'glasspebble|Glass Pebble|pebble|glass|a frosted blue-green glass pebble',
    'seaglassbit|Sea Glass|ice|mint|a smooth frosted mint sea-glass piece',
    'glassfloat|Glass Float|orb|glass/mint|a round glass float with a swirl inside',
    'glasslamp|Sea Glass Lamp|lantern|mint/glow|a lamp made of stained sea-glass pieces',
    'glasschime|Sea Glass Chimes|bell|glass/mint+glow|a hanging wind chime of coloured sea-glass pieces',
    'glasscity|Glass Reef Dome|house|glass/aurora+glow|an underwater glass dome city'],

  ['urchin', 'Urchin Garden', 'nerith', 11,
    'urchinspine|Urchin Spine|twig|plum|a single violet urchin spine',
    'urchin|Urchin|berry|plum|a round spiky violet sea urchin',
    'starurchin|Star Urchin|star|coral/plum|a starfish with an urchin in its middle',
    'starfishcrown|Starfish Crown|crown|coral/gold+glow|a crown of starfish on a gold band'],

  ['manta', 'Manta Glide', 'nerith', 12,
    'mantaegg|Manta Egg|egg|deepsea|a dark blue egg case with curly corners',
    'babymanta|Baby Manta|fish|deepsea/mint|a tiny manta ray',
    'manta|Manta Ray|fish|deepsea/cream|a graceful manta ray gliding',
    'starmanta|Star Manta|fish|dusk/star+glow|a manta with a starry back',
    'skymanta|Sky Manta|bird|aurora/star+glow,motes|a giant manta flying above the waves trailing light'],

  /* =========================================================== AURORA REACH
     Cloudtops under a night sky: auroras, stars, satellites and star-beasts. */
  ['cloudc', 'Cloud Bank', 'vela', 1,
    'wisp|Wisp|cloud|cream|a tiny wisp of cloud',
    'cloudlet|Cloudlet|cloud|frost|a small round cloud',
    'cloudpuff|Cloud Puff|cloud|cloud|a big fluffy cloud',
    'thundercloud|Thunderhead|cloud|dusk/topaz+glow|a dark cloud with a gold lightning bolt',
    'cloudcastle|Cloud Castle|tower|cloud/aurora|a castle built on a cloud',
    'cloudcity|Cloud City|tower|cloud/aurora+glow|a city of cloud towers joined by rainbow bridges',
    'skykingdom|Sky Kingdom|tower|cloud/gold+glow,motes|a grand floating kingdom of white-and-gold palaces on a cloud island'],

  ['aurorac', 'Aurora Weave', 'vela', 1,
    'aurorathread|Aurora Thread|spiral|aurora|a glowing teal thread',
    'aurorasilk|Aurora Silk|cloth|aurora/mint|a folded shimmering silk',
    'auroraveil|Aurora Veil|wave|aurora/lilac+glow|a floating ribbon of aurora light',
    'auroracloak|Aurora Cloak|cloth|lilac/aurora+glow|a cloak made of aurora light on a stand',
    'auroracrown|Aurora Crown|crown|aurora/star|a crown of aurora light with star points',
    'auroraharp|Aurora Harp|bell|gold/aurora+glow,motes|a golden harp strung with aurora light'],

  ['starc', 'Star Nursery', 'vela', 2,
    'stardust|Stardust|pebble|star|a pinch of glittering gold stardust',
    'starspark|Star Spark|gem|star/gold|a small bright spark',
    'starlet|Starlet|star|star|a small chubby star',
    'starcluster|Star Cluster|berrycluster|star/gold+glow|a cluster of little stars',
    'starforge|Star Forge|anvil|dusk/star|an anvil forging a star',
    'constellation|Constellation|star|star/aurora+glow|stars joined by glowing lines into a little shape',
    'supernova|Supernova|orb|star/flame+glow,motes|a blazing burst of a star, rays and rings of light'],

  ['wind', 'Wind Currents', 'vela', 2,
    'breeze|Breeze|feather|mint|a small swirl of breeze',
    'gust|Gust|wave|frost/mint|a curling gust of wind',
    'windcoil|Wind Coil|spiral|frost/aurora|a tight spiral of wind',
    'windvane|Wind Vane|compass|silver/mint|a silver weather vane',
    'windmill|Sky Windmill|tower|silver/mint+glow|a tall windmill on a cloud with silver sails turning',
    'stormeye|Storm Eye|planet|dusk/aurora+glow|a swirling storm with a calm glowing eye'],

  ['skyfruit', 'Sky Orchard', 'vela', 3,
    'skyseed|Sky Seed|seed|mint|a floating mint seed with a tiny wing',
    'skybud|Sky Bud|blossom|mint/aurora|a blossom floating on a cloud',
    'skyfruit|Sky Fruit|fruit|topaz/mint|a round golden floating fruit',
    'skybasket|Sky Basket|basket|straw/topaz|a basket of sky fruit hanging from a balloon',
    'skyfeast|Cloud Feast|cake|cloud/topaz|a cloud cake topped with sky fruit',
    'skytreehouse|Orchard Isle|tree|mint/topaz+glow|a floating island with a fruit tree and a little house'],

  ['chime', 'Chime Tower', 'vela', 3,
    'chimebit|Chime Shard|crystal|silver|a small silver chime rod',
    'chimebell|Chime Bell|bell|silver/mint|a silver bell',
    'chimeset|Chime Ring|ring|silver/aurora|a ring of hanging chimes',
    'chimetower|Chime Tower|tower|silver/aurora|a tall tower of chimes',
    'skybell|Sky Bell|bell|gold/aurora+glow|a great golden bell glowing with aurora',
    'chimecathedral|Chime Cathedral|tower|gold/aurora+glow,motes|a soaring golden cathedral full of bells and aurora light'],

  ['prismv', 'Prism Array', 'vela', 4,
    'lightmote|Light Mote|pearl|glow|a tiny mote of light',
    'lightbeam|Light Beam|prism|glow/aurora|a short beam of light in a crystal',
    'prismlens|Prism Lens|gem|glass/aurora|a round prism lens splitting light',
    'prismarray|Prism Array|snowflake|crystal/aurora+glow|a snowflake-shaped array of prisms',
    'sunsprism|Sun Prism|prism|gold/aurora+glow|a golden prism throwing a rainbow',
    'rainbowbridge|Rainbow Bridge|arch|aurora/gold+glow,motes|a solid rainbow arching between two small cloud islands'],

  ['skynest', 'Sky Nest', 'vela', 5,
    'skydown|Sky Down|cloud|cream/mint|a tuft of cloud-soft down',
    'skyfeather|Sky Feather|feather|aurora/silver|a teal aurora feather',
    'skyplume|Sky Plume|feather|star/gold|a golden starry plume',
    'skynestn|Sky Nest|shell|cloud/gold|a nest woven of cloud with gold threads',
    'skyegg|Dawn Egg|egg|aurora/gold+glow|a glowing egg in dawn colours',
    'skyroc|Sky Roc|bird|aurora/gold+glow,motes|a huge gentle bird with dawn-coloured wings spread wide'],

  ['balloonc', 'Drift Yards', 'vela', 6,
    'silkscrap|Silk Scrap|cloth|rose|a scrap of pink silk',
    'silkbag|Silk Envelope|sack|rose/cream|a bundled silk balloon envelope',
    'driftballoon|Drift Balloon|balloon|rose/gold|a striped hot-air balloon',
    'skyship|Sky Ship|boat|bark/aurora+glow|a wooden airship with aurora sails',
    'reachheart|Reach Heart|orb|aurora/glow+glow|a radiant heart of aurora light'],

  ['starling', 'Star Critters', 'vela', 7,
    'stardustegg|Starlit Egg|egg|dusk/star|a violet egg dotted with tiny stars',
    'glimmer|Glimmer|slime|star|a tiny round star-sprite with a sleepy face',
    'starsprite|Star Sprite|star|star/aurora|a small star-shaped alien with little arms, waving',
    'nebkitten|Nebula Kitten|slime|lilac/star|a violet kitten-like alien with star freckles',
    'cometfox|Comet Fox|slime|dusk/star+glow|a fox-like alien with a long comet tail',
    'aurorafox|Aurora Fox|slime|aurora/star+glow|a fox with a flowing aurora tail and glowing ears',
    'celestfox|Celestial Fox|slime|dusk/gold+glow|a majestic fox made of night sky, gold markings',
    'starbeast|Constellation Beast|slime|star/aurora+glow,motes|a giant gentle beast outlined in stars, glowing lines between them'],

  ['satellite', 'Satellite Works', 'vela', 8,
    'solarcell|Solar Cell|plank|sapphire|a single blue solar cell tile',
    'solarpanel|Solar Panel|plank|sapphire/silver|a folding solar panel in a silver frame',
    'minisat|Mini Satellite|cog|silver/sapphire|a small cube satellite with two panel wings',
    'commsat|Comm Satellite|compass|silver/gold|a satellite with a dish and gold foil body',
    'stationmod|Station Module|barrel|silver/sapphire|a round space-station module with windows and a docking port',
    'orbstation|Orbital Station|planet|silver/aurora+glow|a ring-shaped space station with solar wings',
    'stargate|Star Gate|ring|silver/aurora+glow,motes|a huge silver ring gate with swirling light inside'],

  ['nebula', 'Nebula Jars', 'vela', 9,
    'nebwisp|Nebula Wisp|cloud|lilac|a small wisp of pink-violet nebula gas',
    'nebpuff|Nebula Puff|cloud|lilac/aurora|a colourful swirling puff',
    'nebjar|Nebula Jar|jar|glass/lilac|a glass jar holding a swirling nebula',
    'nebglobe|Nebula Globe|orb|glass/lilac+glow|a snow-globe with a swirling pink nebula inside, on a gold base',
    'neblamp|Nebula Lamp|lantern|gold/lilac+glow|a lantern glowing with nebula colours',
    'bottledgalaxy|Bottled Galaxy|bottle|glass/aurora+glow,motes|a corked bottle with a whole spiral galaxy inside'],

  ['starflower', 'Starflower Beds', 'vela', 10,
    'starseed|Starseed|seed|star|a tiny glowing seed shaped like a star',
    'starsprout|Star Sprout|sprout|mint/star|a sprout with star-tipped leaves',
    'starflower|Starflower|flower|star/lilac|a flower with star-shaped petals',
    'starpot|Starflower Pot|pot|lilac/star|a pot of starflowers',
    'stargarden|Celestial Garden|blossom|star/aurora+glow|a floating flowerbed of starflowers under a glowing arch',
    'starmeadow|Starflower Meadow|blossom|star/lilac+glow,motes|a floating meadow island carpeted in glowing starflowers'],

  ['planets', 'Tiny Planets', 'vela', 11,
    'planetdust|Planet Dust|pebble|dusk|a tiny floating speck of rock',
    'planetoid|Planetoid|rock|slate/dusk|a small lumpy planetoid',
    'miniplanet|Mini Planet|planet|sapphire/leaf|a tiny round planet with seas and green land',
    'ringplanet|Ringed Planet|planet|topaz/cream|a planet with a wide cream ring',
    'twinplanets|Twin Planets|planet|rose/sapphire|two little planets orbiting each other',
    'orrery|Orrery|compass|gold/sapphire+glow|a brass orrery with planets on arms',
    'galaxyswirl|Galaxy Swirl|spiral|aurora/star+glow|a small spiral galaxy floating and glowing',
    'universe|Pocket Universe|orb|dusk/star+glow,motes|a glass sphere holding galaxies and stars'],

  ['kite', 'Sky Kites', 'vela', 12,
    'kitetail|Kite Tail|rope|rose|a ribbon kite tail with bows',
    'kitediamond|Kite|leaf|rose/aurora|a diamond kite with a bow tail',
    'boxkite|Box Kite|crate|topaz/rose|a box kite with striped panels',
    'dragonkite|Dragon Kite|bird|aurora/gold+glow,motes|a long glowing dragon kite coiling through the sky'],

  /* ============================================================ EVERY WORLD */
  ['star', 'Meteor Finds', 'any', 1,
    'scrap|Star Scrap|ore|steel/star|a twisted bit of star-metal scrap',
    'starcore|Star Core|star|star/gold+glow|a glowing golden star core'],

  ['relic', 'Relics', 'any', 1,
    'relic1|Sun Amber|gem|honey/gold+glow|a glowing amber gem with a tiny sun inside',
    'relic2|Prism Hearth|prism|flame/aurora+glow|a prism with a flame burning inside',
    'relic3|Tide Compass|compass|sapphire/gold+glow|a gold compass with a swirling tide for a needle',
    'relic4|Grove Sigil|totem|jade/glow+glow|a jade totem carved with leaves, glowing',
    'relic5|Vault Key|key|gold/aurora+glow|an ornate golden key glowing with aurora light'],

  ['bloom', 'Bloom Essence', 'any', 1,
    'bloomspark|Bloom Spark|seed|glow+glow|a tiny glowing seed of green-gold light',
    'bloommote|Bloom Mote|pearl|glow/aurora+glow|a floating mote of light with petals',
    'bloomcore|Bloom Core|orb|jade/glow+glow|a glowing jade orb with a flower inside',
    'bloomheart|Bloom Heart|orb|aurora/glow+glow|a radiant heart-shaped bloom of light'],

  ['wild', 'Wildcards', 'any', 1,
    'rainbow|Wildcard|orb|aurora/glow+glow,motes|a rainbow-swirled orb that could become anything'],

  /* ================================================================= ROCKET */
  ['hull', 'Rocket: Hull', 'ship', 1,
    'bolt|Bolt|cog|steel|a hex bolt with a nut',
    'boltpack|Bolt Pack|crate|steel/iron|a small box of bolts',
    'hullplate|Hull Plate|plank|steel/silver|a curved riveted hull plate'],
  ['engine', 'Rocket: Engine', 'ship', 1,
    'spring|Spring|spiral|copper|a copper spring',
    'coil|Coil|spiral|copper/gold|a thick copper coil',
    'enginecore|Engine Core|cog|iron/flame|a rocket engine nozzle glowing hot'],
  ['nav', 'Rocket: Nav Dish', 'ship', 1,
    'wire|Wire|rope|copper|a loop of wire',
    'circuit|Circuit|plank|jade/gold|a green circuit board with gold tracks',
    'navdish|Nav Dish|compass|silver/sapphire|a small nav dish with a blinking light'],
  ['tank', 'Rocket: Fuel Tank', 'ship', 1,
    'glass|Glass Pane|ice|glass|a square pane of glass',
    'tankglass|Tank Glass|crate|glass/steel|a glass tank shell in a steel frame',
    'fueltank|Fuel Tank|barrel|steel/glow|a steel fuel tank with a glowing gauge'],
  ['fuel', 'Rocket Fuel', 'ship', 1,
    'fuelore|Fuel Ore|ore|glow/jade|a rock with glowing green veins',
    'fuelcan|Fuel Canister|bottle|jade/glow|a canister of glowing fuel',
    'rocketfuel|Rocket Fuel|flask|glow/aurora+glow|a flask of bright bubbling rocket fuel'],
];

/* Items whose completion does something special. */
export const SPECIAL = {
  hullplate: { part: 'hull' }, enginecore: { part: 'engine' },
  navdish: { part: 'nav' }, fueltank: { part: 'tank' },
  rocketfuel: { fuel: true },
};
