/* Restoration projects — the main thread of every world.
 *
 * Travel Town has you rebuild a place task by task; Galaxy Adventure has you wake
 * a world the same way. Each project asks for a few specific things (and a
 * little money), and finishing it pays well, moves the story on and makes the
 * camp a little more alive. They come in order: the next one opens when the
 * last is done.
 *
 * `launch: true` marks the project that repairs the way off this world. Until
 * it is done the next planet stays locked on the star map, so a world takes a
 * few hours to leave, not ten minutes.
 *
 *   id, name, who (character), text (said when it is done),
 *   needs: [[itemId, qty], ...], coins (cost), xp (world XP reward), gift
 *   (optional: an item or 'chest' dropped on the board as a reward)
 *
 * Needs are picked so each project only uses chains that are awake by the
 * time you reach it.
 */

export const PROJECTS = {
  /* Sunny Meadow is told as one story. You start with a single tree; every
     chapter hands you the next thing — a producer that stays (`unlock`), a
     guest that stays for a while (`temp`), or an event (`event`). The last
     chapter needs the finished rocket, and finishing it opens the sky. */
  earth: [
    { id: 'e1', name: 'Clear the Path', who: 'pip', needs: [['branch', 2]], coins: 0, xp: 15, unlock: ['rocks', 'bush'],
      talk: [['pip', 'A visitor! Nobody has come up this path in years.'], ['pip', 'Tap the Meteor Heap for meteor chips. Two chips make a hot meteor. Two hot meteors clear the path!']],
      text: 'The path is clear! Behind the rubble: a heap of space rocks and a beeping snack cart.' },
    { id: 'e2', name: 'A Rock Border', who: 'grandma', needs: [['rock', 2], ['log', 1]], unlock: ['well'], coins: 80, xp: 25,
      talk: [['grandma', 'The space weeds walk into my garden like they own it. Rude.'], ['grandma', 'Two rocks and a metal ingot for a border, dear.']],
      text: 'A tidy border. Nana is very pleased. Behind it, an old moonwater well starts to drip again.' },
    { id: 'e3', name: 'Nana Luma\'s Snacks', who: 'grandma', needs: [['jam', 1], ['berries', 2]], coins: 120, xp: 40,
      talk: [['grandma', 'Snacks! One food tube and two snack cubes for the picnic.'], ['biscuit', 'The snacks are hereby confiscated. Mayoral privilege.']],
      text: 'First proper meal in years! Nana even washed the jars.' },
    { id: 'e4', name: 'Water for the Garden', who: 'grandma', needs: [['jug', 1], ['puddle', 2]], coins: 200, xp: 60, event: 'meteor',
      talk: [['pip', 'Tap the well: water drops make puddles, puddles make a canister.']],
      text: 'The garden perks up. ...Wait. What is that in the sky?' },
    { id: 'e5', name: 'Dr. Zonk\'s Workshop', who: 'bloop', needs: [['scrap', 1], ['lumber', 1], ['geode', 1]], coins: 320, xp: 80, lab: true,
      talk: [['bloop', 'Blorp. Thank you for not screaming. Most planets scream.'], ['bloop', 'I need a workshop: one Star Scrap, some metal plates and a shiny geode.'], ['timmy', 'A REAL alien! Can I help? CAN I?']],
      text: 'Dr. Zonk\'s Lab hums to life. Recycle spare things there for 🧪 Science.' },
    { id: 'e6', name: 'Mend the Fences', who: 'biscuit', needs: [['lumber', 2], ['pie', 1]], coins: 400, xp: 100, unlock: ['meadow', 'flowerbed'], gift: 'chest', retire: ['tree'],
      talk: [['biscuit', 'Citizens! The fence is broken. Also a moon goat ate my hat.'], ['grandma', 'Two stacks of metal plates and a ration tray for the builder, please.']],
      text: 'The fence stands. The Meteor Heap gave its last metal and cools down now. A solar farm hums on the hill and a light stall opens.' },
    { id: 'e7', name: 'Power Supper', who: 'grandma', needs: [['bale', 1], ['pie', 1], ['barrel', 1]], coins: 560, xp: 120, retire: ['well'],
      talk: [['grandma', 'A supper under the stars! A solar panel for the lights, a ration tray and a water tank.'], ['bloop', 'What is supper. I would like to learn about supper.']],
      text: 'Dr. Zonk had three trays. The old well has done its job.' },
    { id: 'e8', name: 'The Light Market', who: 'gigi', needs: [['bouquet', 1], ['gem', 1]], unlock: ['teabush'], coins: 720, xp: 140, gift: 'chest', retire: ['rocks'],
      temp: { p: 'hive', taps: 18, mins: 25 },
      talk: [['gigi', 'Darling, a village without a light market is just houses in the dark.'], ['gigi', 'A star lantern for the stall and a gem for the sign.']],
      text: 'The market glows! The space rocks are all used up, buzzbots moved in for a while, and a fizz vent starts to bubble.' },
    { id: 'e9', name: 'Nectar Jelly', who: 'gigi', needs: [['honeycomb', 1], ['cake', 1]], coins: 880, xp: 160, retire: ['bush'],
      temp: { p: 'mosslog', taps: 16, mins: 30 },
      talk: [['gigi', 'Nectar jelly! A hex cell of nectar, quickly, before the buzzbots leave.']],
      text: 'Jelly for all. The snack cart is empty. In the woods, an eyeshroom log is blinking awake.' },
    { id: 'e10', name: 'Forest Fizz', who: 'grandma', needs: [['mushring', 1], ['teacup', 1]], coins: 1040, xp: 180,
      temp: { p: 'cottonpatch', taps: 24, mins: 40 },
      talk: [['grandma', 'My mother\'s forest fizz: a bunch of eyeshrooms and a can of soda.'], ['bloop', 'On my world, soda is a colour. Fascinating.']],
      text: 'Fizz for everyone. A suit loom hums for a little while. Sirra has ideas.' },
    { id: 'e11', name: 'Spacesuits for All', who: 'gigi', needs: [['clothbolt', 1], ['hat', 1], ['teacup', 1]], coins: 1200, xp: 200, unlock: ['nestbox', 'toychest'],
      talk: [['gigi', 'Everyone is dressed like a scare-bot. No offence to the scare-bot.'], ['gigi', 'A space helmet, a solar panel array and a soda for the tailor. I do the rest. I always do the rest.']],
      text: 'Suits for all. Then a delivery: a jet wreck and a toy chest. Busy days ahead!' },
    { id: 'e12', name: 'Jet Day', who: 'timmy', needs: [['speckegg', 1], ['garland', 1]], unlock: ['vegpatch', 'tinkerbench'], coins: 1360, xp: 220, retire: ['flowerbed', 'teabush'],
      temp: { p: 'crashsite', taps: 20, mins: 30 },
      talk: [['timmy', 'A twin jetpack and a light string so it looks cool!'], ['pip', 'Jetpacks do not care about lights, Ember.'], ['timmy', 'THIS jetpack does.']],
      text: 'Timmy flew all evening. The light stall and the fizz vent have given all they had; a hydro bed and a lens workbench take their place. Then something small crashes behind the hill, blinking!' },
    { id: 'e13', name: 'The Little Visitors', who: 'timmy', needs: [['alienkid', 1], ['toyrobot', 1], ['nest', 1]], coins: 1520, xp: 240, gift: 'chest',
      talk: [['bloop', 'Blinkies! Babies. Far from home, like me.'], ['timmy', 'Help one grow up: give it a toy robot and a jet boot. Can we keep it?!']],
      text: 'The little visitors are safe and very hungry.' },
    { id: 'e14', name: 'A Garden for Guests', who: 'biscuit', needs: [['carrot', 2], ['scarecrow', 1], ['spintop', 1]], unlock: ['lilypond'], coins: 1680, xp: 260, retire: ['meadow'],
      talk: [['biscuit', 'The space crows threaten civic order. I drafted a strongly worded letter.'], ['pip', 'Or two grow tubes, a power station and a spinning top for the Blinkies?']],
      text: 'The solar farm powers the last station and goes quiet. Down by the water, a slime pond fills up.' },
    { id: 'e15', name: 'Stargazing Night', who: 'timmy', needs: [['spyglass', 1], ['vegbundle', 1], ['speckegg', 1]], coins: 1920, xp: 300, unlock: ['windmill', 'claypit'], gift: 'chest', retire: ['nestbox'],
      talk: [['timmy', 'Dr. Zonk says his home is up THERE. Behind the Moon!'], ['grandma', 'A spyglass, a hydro tray and a twin jetpack. Nobody stargazes on an empty stomach.']],
      text: 'The Moon has tiny lights. "Friends," whispers Dr. Zonk. And in the woods: his ship. In pieces. Time to build a rocket! Next to the slime pond: a cheese mill and a goo pit.' },
    { id: 'e16', name: 'The Cheese Shop', who: 'mumbo', needs: [['carrot', 1], ['lilypad', 2], ['spintop', 1]], coins: 2080, xp: 320, gift: 'chest', retire: ['toychest'],
      talk: [['mumbo', 'Chef Gubbo, cheese master. Well, cheese master without a shop.'], ['mumbo', 'A grow tube, two slime puddles to age the cheese, and a spinning top to keep the Blinkies out of it.']],
      text: 'The cheese shop is open. Moon cheese for everyone!' },
    { id: 'e17', name: 'Goo Day', who: 'gigi', needs: [['loaf', 1], ['vegbundle', 1], ['lotus', 1]], coins: 2320, xp: 340, retire: ['vegpatch'],
      talk: [['gigi', 'Cheese but no bowls. Uncivilised, darling.'], ['gigi', 'A cheese wheel, a hydro tray and a slime jar for the potters. There is moon goo by the river.']],
      text: 'The hydro bed is resting. Sirra ordered twelve vases.' },
    { id: 'e18', name: 'Fizz in the Garden', who: 'pim', needs: [['claypot', 2], ['roll', 2], ['lotus', 1]], coins: 2560, xp: 360, gift: 'chest',
      temp: { p: 'picnichamper', taps: 14, mins: 30 },
      talk: [['pim', 'Duchess Splatt. I have come a very long way for a proper fizz.'], ['grandma', 'Finally, someone with manners.']],
      text: 'Fizz under the stars. The Duchess leaves her cargo pod behind. On purpose.' },
    { id: 'e19', name: 'The Slime Pond', who: 'timmy', needs: [['lotus', 1], ['urn', 1], ['picnicbasket', 1]], coins: 2800, xp: 380, gift: 'chest', unlock: ['eggnest', 'buskbot'],
      talk: [['timmy', 'A party at the slime pond! Slime deserves nice things.']],
      text: 'The slime frogs hold a party. Behind the crates: wobbling pet eggs and a busker bot.' },
    { id: 'e20', name: 'Toys for the Blinkies', who: 'bloop', needs: [['pondfrog', 1], ['blobpup', 1], ['claypot', 2]], unlock: ['rockethull'], coins: 3040, xp: 400, gift: 'chest',
      temp: { p: 'raincloud', taps: 10, mins: 12 },
      talk: [['bloop', 'Bored Blinkies chew rockets.'], ['biscuit', 'They chewed my OFFICIAL sash.']],
      text: 'The Blinkies have a pet now. The busker bot plays one chord, over and over. And under the crates: an old scrap hull, full of rocket bits.' },
    { id: 'e21', name: 'The Space Parade', who: 'pip', needs: [['drum', 1], ['breadbasket', 1], ['urn', 1]], coins: 3280, xp: 420, gift: 'chest', retire: ['windmill', 'claypit'],
      talk: [['pip', 'A parade before the launch! A drum, a cheese stack and an orbit urn.']],
      text: 'Best parade ever. "Nearly there," says Dr. Zonk, patting a fin. The fin falls off.' },
    { id: 'e22', name: 'The Launch Pad', who: 'bloop', launch: true, rocket: true, needs: [['nosecone', 1], ['telescope', 1], ['lotus', 2], ['blobpup', 1]], coins: 2240, xp: 360, gift: 'bigchest', unlock: 'weatherballoon',
      talk: [['bloop', 'A nose cone, a telescope, two slime jars to cool the engines, and a blob pup. It insists on coming.'], ['bloop', 'Miss you? No. You are coming too.']],
      text: 'The rocket stands. Sunny Meadow is awake, and the Moon is waiting.' },
  ],
  luna: [
    { id: "l1", name: "Light the Camp", who: "luma", needs: [["mcrystal", 2], ["bulb", 1]], coins: 240, xp: 30, unlock: ["dustflat"],
      talk: [["luma", "Oh, far out. Visitors. Sorry it is so dark, man — the lamps gave up years ago."], ["luma", "Two moon shards and a glow pod and I can make a little ring of light. Vibes first, then everything else."], ["zib", "Kix stowed away in the cargo hold. Kix regrets nothing. Kix is cold."]],
      text: "A little ring of glow around the tents. Behind them, a flat of moon dust is ready to dig." },
    { id: "l2", name: "Build a Dust Wall", who: "rokk", needs: [["regolith", 2], ["mcore", 1]], coins: 360, xp: 45,
      talk: [["rokk", "GREETINGS. I AM ROKK. I WAS THE BUTLER OF THIS CAMP. THE CAMP LEFT. I STAYED."], ["rokk", "THE DUST STORMS KNOCK OVER THE TENTS. TWO REGOLITH BRICKS AND ONE MOON CORE FOR THE KEYSTONE. PLEASE."]],
      text: "WALL: STANDING. WIND: BLOCKED. ROKK: PROUD." },
    { id: "l3", name: "The Crystal Garden", who: "nix", needs: [["mstar", 1], ["glowflower", 1]], coins: 520, xp: 60, unlock: ["icevein", "wickpod"], gift: "chest",
      talk: [["nix", "Ah. Tourists. Mind the moon stars, they are older than your planet and twice as interesting."], ["nix", "A moon star and a pod cluster. I am building a garden. A tasteful one. You would not understand."]],
      text: "Nix has a garden. Rokk found an ice vein and an old wick pod behind it." },
    { id: "l4", name: "Lanterns for the Dark Side", who: "rokk", needs: [["moonlamp", 1], ["iceshard", 1]], coins: 720, xp: 80,
      talk: [["rokk", "THE FAR SIDE IS DARK FOR FOURTEEN DAYS AT A TIME. I DO NOT LIKE IT. I AM NOT AFRAID. I AM A ROBOT."], ["rokk", "A MOON LANTERN AND AN ICE SHARD TO FOCUS IT. FOR NO REASON. NOT FEAR."]],
      text: "Rokk walks the far side at night now. Humming. Rokk does not hum. Rokk is humming." },
    { id: "l5", name: "Catch a Comet", who: "luma", needs: [["icecore", 1], ["starbloom", 1]], coins: 960, xp: 100, gift: "chest",
      talk: [["luma", "A comet passes every night at nine, man. Like clockwork. Like a really cold friend."], ["luma", "Catch a ball of its clear ice, and bring a pod lamp so we can see it. Comets carry seeds, you know. Old ones."], ["bloop", "Blorp. She is right. I checked. I hate it when the hippie is right."]],
      text: "The comet's ice was full of old seeds. Moonbeam planted every one." },
    { id: "l6", name: "Moon Launch Pad", who: "zib", needs: [["moonbrick", 1], ["moonorb", 1], ["beacon", 1]], temp: {"p": "pupnest", "taps": 20, "mins": 30}, coins: 1280, xp: 140, launch: true, unlock: ["crystalspire", "silverseam"], retire: ["geyser", "glowpod"], gift: "chest",
      talk: [["zib", "Kix has a business proposal. A launch pad. Kix builds, you pay, everybody flies."], ["zib", "Moon brick, a moon orb for the guidance light, one beacon so the pilot does not miss. Kix missed once. Long story."], ["bloop", "There is a fire planet in range. Ember Hollow. Bring a fire extinguisher."]],
      text: "Pad ready! The old geyser and the glow pods are spent, but a crystal spire and a silver seam just broke through. Ember Hollow is in range now! And something small is bouncing out of a crater: a moon pup nest!" },
    { id: "l7", name: "A Home for the Pups", who: "nix", needs: [["moonpup", 1], ["prismlet", 1]], coins: 1520, xp: 170,
      talk: [["nix", "Those bouncing things are moon pups. They chew crystals. MY crystals."], ["nix", "Give them a burrow far from my garden. A pup to show the others the way, and a prism shard to chew instead of mine."]],
      text: "The pups have a burrow with a view. They bounce off the walls. Literally." },
    { id: "l8", name: "The Rover Garage", who: "zib", needs: [["moonwall", 1], ["silveringot", 1]], coins: 1840, xp: 210, gift: "chest",
      talk: [["zib", "Kix found an old rover. Kix needs a garage. A moon wall and a silver ingot for the door."], ["rokk", "THERE WILL BE NO GRAND OPENING."], ["zib", "There will be a SMALL grand opening."]],
      text: "A garage with a silver door. The rover is still in pieces. Kix calls that \"potential\"." },
    { id: "l9", name: "Fuel the Heaters", who: "rokk", needs: [["glacier", 1], ["prismcore", 1]], coins: 2160, xp: 250, unlock: ["comettrail", "scrapyard"], retire: ["dustflat", "icevein"],
      talk: [["rokk", "THE HEATERS NEED COOLANT AND A FOCUS. EVERYONE IS COLD. MOSTLY ME. I AM METAL."], ["rokk", "ONE GLACIER BLOCK AND ONE PRISM CORE. THE IRONY IS NOT LOST ON ME."]],
      text: "WARM. The dust flat and the ice vein are mined out. A comet trail lands nearby, and the scrapyard wakes up full of little bots." },
    { id: "l10", name: "Call Home", who: "luma", needs: [["lighthouse", 1], ["cometcore", 1], ["cupbot", 1]], coins: 2800, xp: 340, gift: "chest",
      talk: [["bloop", "The old dish still points at the sky. If it turns again, the camp can talk to everyone out there."], ["luma", "A lighthouse for the signal, a comet core for the tuner, and a little cup bot to turn the dish. Mostly for the vibes."], ["nix", "Fine. I will admit it. I would like to call someone."]],
      text: "The dish turns, the stars answer. Crater Camp is part of the sky again." },
    { id: "l11", name: "The Fortune Tent", who: "oops", needs: [["prismheart", 1], ["cometstone", 1]], temp: {"p": "melonvine", "taps": 20, "mins": 30}, coins: 3200, xp: 380,
      talk: [["oops", "I saw you coming! In my crystal ball! ...It was cracked, so you were in three pieces. Still."], ["oops", "A prism heart for a new ball and a comet stone to make it shine. Then I can see the future in ONE piece."], ["nix", "She is a fraud. A charming fraud. I want my fortune read."]],
      text: "Madame Oops reads fortunes by the craters now. She is right about a third of the time. Nix says that is a record. An algae vine pokes out of the soil, just for a while." },
    { id: "l12", name: "The Algae Dome", who: "luma", needs: [["moonmelon", 1], ["silvercup", 1]], coins: 3600, xp: 410, unlock: ["gasvent", "relaymast"], retire: ["wickpod", "crystalspire"], gift: "chest",
      talk: [["luma", "Everybody keeps arriving, man, and everybody is hungry. Visitors eat a LOT."], ["luma", "An algae tank to start the dome, and a silver chalice for the first harvest. Green food, good vibes."], ["rokk", "I DO NOT EAT. I WILL SUPERVISE THE EATING."]],
      text: "Algae soup for everyone. The wick pods and the crystal spire have given all they had, and a helium vent and a relay mast take their place." },
    { id: "l13", name: "Captain Glimmer's Moon Show", who: "glimmer", needs: [["silvercrown", 1], ["cometheart", 1], ["parcelpod", 1]], temp: {"p": "impact", "taps": 24, "mins": 30}, coins: 4000, xp: 440,
      talk: [["glimmer", "MAGNIFICENT! A moon with NO show! I, Captain Glimmer, shall fix that at once."], ["glimmer", "A silver crown for the star (me), a comet heart for the finale, and a parcel pod full of invitations. They will come. They always do."], ["zib", "Kix sells the tickets. Kix has already sold the tickets."]],
      text: "Standing ovation. Glimmer took eleven bows. A fresh impact crater smokes at the edge of camp." },
    { id: "l14", name: "The Skyfall Museum", who: "nix", needs: [["pallasite", 1], ["drillbot", 1], ["gascan", 1]], coins: 4500, xp: 480, gift: "chest",
      talk: [["nix", "All these visitors and nothing to look at but me. I am wonderful, but I am not enough."], ["nix", "A museum. A pallasite for the main hall, a digger bot to find more, and a gas canister for the lights. Labels in my handwriting."]],
      text: "The museum opened at dawn. The labels are very long. Everybody reads them anyway." },
    { id: "l15", name: "The Deep Space Ear", who: "rokk", needs: [["radar", 1], ["gastank", 1], ["walkerbot", 1]], coins: 5200, xp: 540, gift: "chest",
      talk: [["rokk", "THE DISH HEARS THE OTHER WORLDS. NOW I WANT TO HEAR FURTHER. PAST THE EDGE OF THE MAP."], ["rokk", "A RADAR DISH, A HELIUM TANK TO POWER IT AND A WALKER BOT TO KEEP IT POINTED. I WILL LISTEN. I AM GOOD AT LISTENING."], ["bloop", "Blorp. If something out there says hello, I want to know first."]],
      text: "Something out past the map is humming back. Rokk has started humming along again. He denies it." },
  ],
  cindra: [
    { id: "c1", name: "Rekindle the Forge", who: "vulk", needs: [["cinder", 2], ["ashroom", 1]], coins: 320, xp: 35, unlock: ["ironseam"],
      talk: [["vulk", "HRM. A visitor. The forge has been cold for a hundred years. I have been angry for a hundred and one."], ["vulk", "Two cinders and an ash shroom. The forge eats, then it works. Like me."]],
      text: "The forge breathes. Vulk pretends it was nothing. Behind it, an old iron seam glints." },
    { id: "c2", name: "New Tools", who: "vulk", needs: [["ironingot", 1], ["lavablob", 1]], coins: 480, xp: 50,
      talk: [["vulk", "The forge breathes. Now it needs tools. My old ones melted. My mood melted them."], ["vulk", "An iron ingot and a lava blob to temper it. Hot things. Good things."]],
      text: "Hammers, tongs and one very large spoon. Vulk will not explain the spoon." },
    { id: "c3", name: "The Market Stall", who: "ember", needs: [["bigshroom", 1], ["ironnug", 2]], temp: {"p": "spicevine", "taps": 20, "mins": 30}, coins: 680, xp: 70, unlock: ["obsidslab", "coalpit"], gift: "chest",
      talk: [["ember", "A REAL VISITOR! Do you want a mushroom? I grow mushrooms! I grow TOO MANY mushrooms!"], ["ember", "A great shroom for the stall roof and two iron nuggets for the frame. Travellers will come. They will! Probably!"]],
      text: "Fizz sells mushrooms to travellers who have not arrived yet. Vulk dug out an obsidian slab and a star coal pit. A fire gel spring bubbles up for a little while." },
    { id: "c4", name: "Stew for Everyone", who: "ember", needs: [["spicejar", 1], ["forgefire", 1]], coins: 920, xp: 90,
      talk: [["ember", "Everyone here is grumpy because nobody has eaten. Vulk has not eaten since the volcano."], ["vulk", "I had a rock in spring."], ["ember", "A jar of fire gel and a forge flame. STEW. The spiciest stew in the system."]],
      text: "Very, very spicy. Nobody complained. Nobody could speak." },
    { id: "c5", name: "The Bell Tower", who: "vulk", needs: [["obblade", 1], ["fireopal", 1]], coins: 1200, xp: 120, gift: "chest",
      talk: [["vulk", "The vents roar at night. The old bell used to calm them. It cracked."], ["vulk", "An obsidian blade for a new clapper and a fire opal to make it ring true. Then we sleep."]],
      text: "The bell rings at sunset. The vents seem to quieten when it does." },
    { id: "c6", name: "Heat-Proof Launch Pad", who: "bloop", needs: [["ironanvil", 1], ["obmirror", 1], ["bellows", 1]], temp: {"p": "ashnest", "taps": 18, "mins": 30}, coins: 1520, xp: 160, launch: true, unlock: ["sandpit", "copperseam"], retire: ["lavavent", "shroomlog"], gift: "chest",
      talk: [["bloop", "A launch pad on a planet made of fire. Blorp. What could go wrong."], ["vulk", "Iron anvil for the base. Dark mirror to throw the heat back. Bellows to cool the engines."], ["ember", "And a little flag! I will make the flag!"]],
      text: "It will not melt. Probably. The lava vent and the shroom log are spent, so Vulk opened a hot sand pit and a copper seam. Tidal Shallows is in range! And firebirds are circling an old ash nest." },
    { id: "c7", name: "Nests for the Firebirds", who: "ember", needs: [["emberegg", 1], ["glassbead", 1]], coins: 1800, xp: 200,
      talk: [["ember", "The firebirds keep sleeping in Vulk's boots."], ["vulk", "They are WARM boots."], ["ember", "An ember egg and a glass bead to keep it warm — they need a nest of their own!"]],
      text: "Tiny flames curled in warm glass. They follow Fizz everywhere now." },
    { id: "c8", name: "The Quiet Hall", who: "vulk", needs: [["coppercog", 1], ["glassvase", 1]], coins: 2160, xp: 240, gift: "chest",
      talk: [["vulk", "Too many people now. Meetings. Opinions. I need a hall with a door that closes."], ["vulk", "A great cog for the door and a glass vase, so Fizz stops putting flowers in my helmet."]],
      text: "A hall with a heavy door. Meetings happen there now. Vulk sits by the door." },
    { id: "c9", name: "Pipes for the Hollow", who: "rokk", needs: [["copperbell", 1], ["greatforge", 1]], temp: {"p": "charstump", "taps": 22, "mins": 30}, coins: 2560, xp: 290, unlock: ["sulfurspring", "warmnest"], retire: ["ironseam", "obsidslab"],
      talk: [["rokk", "GREETINGS AGAIN. I FOLLOWED THE HEAT. HEAT IS POWER. POWER IS ORDER."], ["rokk", "A COPPER BELL FOR THE ALARM AND A GREAT FORGE TO HEAT THE PIPES. THE SMELL IS UNFORTUNATE. THE PROGRESS IS NOT."]],
      text: "PRESSURE: NOMINAL. The iron and obsidian are mined out. A sulfur spring starts to fizz, and lava snails crawl out of a warm nest. A charred stump starts to glow like a lava lamp." },
    { id: "c10", name: "The Lava Lights", who: "ember", needs: [["fruitbasket", 1], ["glasslily", 1], ["sulfurcrystal", 1]], coins: 3200, xp: 380, gift: "chest",
      talk: [["ember", "Lava lamps all over the hollow! Light that is warm when you touch it!"], ["vulk", "A big lava lamp, a glass lily and a sulfur crystal to mark the spot."], ["bloop", "And then the oceans, friend. Tidal Shallows. You will need a towel."]],
      text: "The hollow glows from end to end. Cindra is reborn." },
    { id: "c11", name: "The Grub Brothers' Stall", who: "grubs", needs: [["fwbox", 1], ["glassvase", 1]], coins: 3600, xp: 420,
      talk: [["grubs", "Deal! We heard there is a fire planet with customers. (He heard. I came anyway.)"], ["grubs", "A box of fireworks to sell and a glass vase for the counter. Classy. Best stall on the planet. Only stall on the planet."], ["vulk", "If they sell my spoon I will be angry."]],
      text: "The stall sells everything twice: once by each brother." },
    { id: "c12", name: "Dragonlet Daycare", who: "ember", needs: [["magmadrake", 1], ["volcsnail", 1]], coins: 4000, xp: 450, unlock: ["steamvent", "basaltcliff"], retire: ["coalpit", "sandpit"], gift: "chest",
      talk: [["ember", "The fire critters had babies! Then the babies had OPINIONS!"], ["ember", "A magma dragonlet to keep the little ones in line and a volcano snail to slow them down. Carefully! Mostly carefully!"]],
      text: "Tiny dragons asleep in warm sand. The coal pit and the sand pit are spent, and a steam vent and a basalt cliff rise up." },
    { id: "c13", name: "The Clockwork Tower", who: "zib", needs: [["copperclock", 1], ["steamengine", 1]], coins: 4400, xp: 490,
      talk: [["zib", "Kix has noticed nobody here is ever on time. Kix sees a business: TIME."], ["zib", "A copper clock and a steam engine to wind it. Kix will charge per minute. Small minutes."], ["rokk", "I WILL KEEP THE TIME. FOR FREE. SORRY, KIX."]],
      text: "The tower chimes every hour. Rokk is never late now. Kix is still a bit late. On purpose." },
    { id: "c14", name: "The Great Fire Show", who: "glimmer", needs: [["fwcannon", 1], ["brimstone", 1], ["basaltarch", 1]], coins: 4900, xp: 530, gift: "chest",
      talk: [["glimmer", "MAGNIFICENT! A planet made of fireworks and NOBODY has done a show? Tragic. Leave it to me."], ["glimmer", "A firework cannon for the big bang, a brimstone heart for the smell, and a basalt gate to make my entrance. I always make an entrance."], ["vulk", "Hrm. If it is loud, I am in."]],
      text: "The sky over the hollow went gold, then red, then gold. Vulk clapped. Nobody had seen Vulk clap before." },
    { id: "c15", name: "The Basalt Citadel", who: "vulk", needs: [["causeway", 1], ["automaton", 1], ["lampsnail", 1]], coins: 5600, xp: 580, gift: "chest",
      talk: [["vulk", "A hundred years ago we had a citadel. The volcano took it. I want it back. Bigger."], ["vulk", "Giant's steps for the gate, a copper clock for the tower and a lamp snail to light the way. Not for me. I am too grumpy to rule."], ["ember", "You would be a lovely king, Vulk!"], ["vulk", "HRM."]],
      text: "The citadel shines black and red over the hollow. Vulk sits on the step next to the empty throne." },
  ],
  nerith: [
    { id: "n1", name: "Clean the Beach", who: "kelpa", needs: [["seashell", 2], ["kelpfrond", 1]], coins: 400, xp: 40, unlock: ["coralhead"],
      talk: [["kelpa", "Oh! Hello! Welcome to the Shallows! Mind the bubbles. And the other bubbles. It is all bubbles, sorry."], ["kelpa", "Two sea shells and a bubble cluster and I can clear a path to the water. Then we can paddle!"]],
      text: "Sand you can actually walk on. A coral head is growing back by the rocks." },
    { id: "n2", name: "Replant the Reef", who: "kelpa", needs: [["coralsprig", 2], ["kelpcoil", 1]], coins: 600, xp: 55,
      talk: [["kelpa", "The reef used to be every colour. Now it is mostly beige. Beige is not a reef colour."], ["kelpa", "Two coral sprigs to plant, and a bubble jar to keep them company. Corals get lonely."]],
      text: "Little corals in neat rows. The first swimmers arrived an hour later." },
    { id: "n3", name: "The Critter Market", who: "marin", needs: [["bigshell", 1], ["coralfan", 1]], coins: 840, xp: 75, unlock: ["oysterbed", "tidepool"], gift: "chest",
      talk: [["marin", "Harbourmaster Brine. Forty years on this pier. Thirty-nine of them grumpy."], ["marin", "No market, no gossip. A great shell for the counter and a coral fan for shade. Hop to it."]],
      text: "The market bubbles with gossip. Brine found an oyster bed and a tide pool under the pier." },
    { id: "n4", name: "The Store Room", who: "marin", needs: [["pearl", 1], ["seafoam", 1]], coins: 1080, xp: 95,
      talk: [["marin", "Supplies go off down here. Everybody knows that. Except Kelpa, who keeps a swimmer in a jar \"as a friend\"."], ["kelpa", "His name is Gerald!"], ["marin", "A pearl for the lock and some sea foam to pack it all in. Please."]],
      text: "Enough stores for the whole winter. Brine counted twice." },
    { id: "n5", name: "Raise the Wreck", who: "marin", needs: [["nautilus", 1], ["tidewave", 1]], coins: 1360, xp: 125, gift: "chest",
      talk: [["marin", "There is an old saucer at the bottom of the bay. My first ship. I sank it. Long story. Short storm."], ["marin", "A nautilus to patch her hull and a tide swell to lift her. Pilots are superstitious. I am VERY superstitious."]],
      text: "The old saucer floats again. Pearl swears it is the same one her grandmother flew." },
    { id: "n6", name: "The Floating Launch Pad", who: "bloop", needs: [["shellhorn", 1], ["coralcrown", 1], ["kelpbale", 1]], temp: {"p": "nestbeach", "taps": 16, "mins": 30}, coins: 1680, xp: 170, launch: true, unlock: ["fishtrap", "saltpan"], retire: ["shellbed", "kelpbed"], gift: "chest",
      talk: [["bloop", "Blorp! The next world is up there. The only flat thing here is the water. So the launch pad will float."], ["marin", "Floating launch pads. In my day we launched things by throwing them."], ["bloop", "A shell horn for the hull, a coral crown to steady it, a bubble helmet for the pilot."]],
      text: "It bobs a bit. The shell bed and the bubble bed are spent; a critter trap and a crystal pan take over. Aurora Reach is in range! Up the beach, a nesting beach is full of wobbling eggs." },
    { id: "n7", name: "Guard the Shellkins", who: "kelpa", needs: [["hatchling", 1], ["silverfish", 1]], coins: 2000, xp: 210,
      talk: [["kelpa", "The shellkins are hatching! All at once! There are SO MANY of them!"], ["kelpa", "A shellkin to show the others the way, and a three-eye swimmer to guide them to the water. Gently!"]],
      text: "Every shellkin made it to the water. Kelpa counted every single one, out loud." },
    { id: "n8", name: "The Crystal Pier", who: "marin", needs: [["saltpillar", 1], ["pearlstrand", 1]], coins: 2400, xp: 260, gift: "chest",
      talk: [["marin", "Subs are coming in from the other worlds now. Rocket subs. Whatever those are."], ["marin", "A proper pier needs a crystal pillar and a pearl strand for the lamps. Do it right or do not do it."]],
      text: "Subs come and go. Some of them from worlds you woke." },
    { id: "n9", name: "Mood Lighting", who: "sirra", needs: [["tidalorb", 1], ["saltcake", 2]], coins: 2800, xp: 310, unlock: ["wrecksite", "lightvent"], retire: ["coralhead", "oysterbed"],
      talk: [["sirra", "Darling, the Shallows are lovely by day, but by night? Pitch black. Unacceptable."], ["sirra", "A tidal orb that glows and two crystal cubes to hang it from. Everybody deserves mood lighting."]],
      text: "The shallows glow at night. The coral and the oysters rest; a saucer wreck and a light vent full of jellies wake up." },
    { id: "n10", name: "Wake the Drowned City", who: "sirra", needs: [["sunkenidol", 1], ["salttemple", 1], ["jellyling", 1]], coins: 3520, xp: 400, gift: "chest",
      talk: [["sirra", "There is a city under the bay. My grandmother said so. She also said she was a mermaid queen, so."], ["marin", "The city is real. I have seen the domes at low tide."], ["sirra", "A sunken robot, a crystal temple and a jellyling to swim through the gate — the old songs say that opens it."]],
      text: "The domes break the surface, glittering. Nerith breathes again." },
    { id: "n11", name: "Parcels by Sub", who: "blorb", needs: [["driftboat", 1], ["floatjelly", 1]], coins: 4000, xp: 450,
      talk: [["blorb", "Parcel! For... the bottom of the sea. Sign here. Any leg. Any tentacle."], ["blorb", "A porthole pod to deliver it and a float jelly to carry me back up. Six legs do not swim. I checked."]],
      text: "Postie Blorb now delivers under water. Parcels arrive a bit damp. Nobody minds." },
    { id: "n12", name: "The Big Aquarium", who: "kelpa", needs: [["fishfeast", 1], ["deeplantern", 1]], coins: 4400, xp: 490, unlock: ["dock", "glassbeach"], retire: ["tidepool", "fishtrap"], gift: "chest",
      talk: [["kelpa", "Gerald is lonely! Gerald needs a BIG home with friends!"], ["marin", "Gerald is a swimmer in a jar."], ["kelpa", "An aquarium and a lantern critter so he has a night light. He gets scared. Like me."]],
      text: "Gerald has two hundred friends now. The tide pool and the critter trap rest, and a sub dock and a glass beach open up." },
    { id: "n13", name: "Madame Oops Reads the Tides", who: "oops", needs: [["abyssorb", 1], ["glassfloat", 1]], temp: {"p": "mantadeep", "taps": 22, "mins": 30}, coins: 4800, xp: 520,
      talk: [["oops", "The sea told me a secret! I did not understand it. It was very wet."], ["oops", "An abyss orb and a glass float. Orbs see everything. Floats see... up. I mostly guess."], ["sirra", "Darling, she guessed my birthday. I am impressed and a little scared."]],
      text: "The tides now arrive exactly when Oops says. Nobody knows if she predicts them or tells them. Out in the deep, the gliders are gathering." },
    { id: "n14", name: "The Glider Races", who: "sirra", needs: [["starmanta", 1], ["racesub", 1]], coins: 5300, xp: 560, gift: "chest",
      talk: [["sirra", "Darling, the gliders are faster than anything with an engine. Let us prove it!"], ["sirra", "A star glider to lead the race and a racing sub to chase it."]],
      text: "The star glider won by a fin. The sub driver demands a rematch." },
    { id: "n15", name: "The Crystal Lighthouse", who: "marin", needs: [["saltlight", 1], ["champsub", 1], ["jellymum", 1]], coins: 6000, xp: 620, gift: "chest",
      talk: [["marin", "Ships from every world come here now. One more thing and the Shallows are a proper port."], ["marin", "A crystal lighthouse, a champion sub to guide ships in and a jelly mum to keep the bay calm. Forty years I waited for this."]],
      text: "The lighthouse sweeps the bay. Brine has stopped being grumpy. Thirty-nine years was enough." },
  ],
  vela: [
    { id: "v1", name: "Solid Ground", who: "zephyr", needs: [["cloudpuff", 1], ["aurorasilk", 1]], coins: 480, xp: 45, unlock: ["starcradle"],
      talk: [["zephyr", "Wheee! Oh — visitors! Careful, there is no ground. There is no ground ANYWHERE. Isn't it great?"], ["zephyr", "A big cloud puff and some aurora silk to stitch it down, and you will have something to stand on."]],
      text: "A cloud you can stand on. Nearby, a star cradle starts to twinkle." },
    { id: "v2", name: "Stitch the Sky", who: "halo", needs: [["auroraveil", 1], ["starlet", 2]], coins: 720, xp: 60,
      talk: [["halo", "Hello. I have been expecting you for three hundred years. You are slightly late."], ["halo", "The sky is torn. An aurora veil to mend it and two starlets to pin it in place."]],
      text: "One stripe of colour across the dark. Halo keeps looking up." },
    { id: "v3", name: "Cloud Pillows", who: "wren", needs: [["thundercloud", 1], ["starspark", 2]], coins: 1000, xp: 85, unlock: ["windvanep", "skytree"], gift: "chest",
      talk: [["wren", "Chirrup! New faces! Did you hear about Zephyr? Fell off a cloud. TWICE. Anyway."], ["wren", "Cloud pillows float off unless you pin them. A thunderhead and two star sparks, please!"]],
      text: "Pillows on every cloud. A wind vane spins up, and a jelly cloud drifts in to stay." },
    { id: "v4", name: "Cloud Jelly", who: "wren", needs: [["skyfruit", 1], ["windcoil", 1]], temp: {"p": "skynestp", "taps": 16, "mins": 30}, coins: 1280, xp: 110,
      talk: [["wren", "Cloud jelly! It floats off unless you hold it down."], ["wren", "A jelly jar and a wind coil to keep it put. Chirrup!"]],
      text: "Wobbly jelly on every cloud. The cloud critters found it before anyone. A sky nest drifts past, full of fluff." },
    { id: "v5", name: "Nests on the Wind", who: "wren", needs: [["skyplume", 1], ["starcluster", 1]], coins: 1600, xp: 140, gift: "chest",
      talk: [["wren", "The sky birds are coming home! I told everyone first. Obviously."], ["wren", "A cloud nest to line and a star cluster to keep them warm at night."]],
      text: "Nests on every cloud. The sky birds are home." },
    { id: "v6", name: "Sails for the Islands", who: "zephyr", needs: [["windvane", 1], ["auroracloak", 1], ["skybasket", 1]], temp: {"p": "starden", "taps": 16, "mins": 30}, coins: 1920, xp: 180, unlock: ["chimepost", "prismstand"], retire: ["cloudbank", "auroraloom"], gift: "chest",
      talk: [["zephyr", "The islands drift apart and nobody visits anybody. Let us fix that!"], ["zephyr", "A wind vane to steer by, an aurora cloak for a sail, and a jelly cake for the trip. Mostly the cake."]],
      text: "Sails between the islands. The cloud bank and the aurora loom rest now; a chime post and a prism stand catch the wind. Something twinkles in a little star den." },
    { id: "v7", name: "A Den for the Star-Kits", who: "halo", needs: [["starsprite", 1], ["chimebell", 1]], coins: 2240, xp: 220,
      talk: [["halo", "The star-kits are frightened. They were born after the Bloom left and have never seen it."], ["halo", "A star sprite to lead them and a chime bell to sing them to sleep."]],
      text: "The little star-kits have a den of their own. They glow brighter when you visit." },
    { id: "v8", name: "Tune the Chimes", who: "wren", needs: [["chimetower", 1], ["prismlens", 1]], coins: 2640, xp: 270, gift: "chest",
      talk: [["wren", "The chimes stopped ringing when the Bloom left. Nobody has gossiped properly since. Tragic."], ["wren", "A chime tower and a prism lens to tune it. Chirrup!"]],
      text: "The chimes play a tune nobody taught them. Halo says it is the Vault singing back." },
    { id: "v9", name: "The Prism Array", who: "halo", needs: [["prismarray", 1], ["starforge", 1]], coins: 3040, xp: 320, unlock: ["silkloom", "solarfarm"], retire: ["starcradle", "windvanep"],
      talk: [["halo", "The light is coming back. We should catch it before it slips away again."], ["halo", "A prism array to catch it and a star forge to feed it."]],
      text: "Light pours across the Reach. The star cradle and the wind vane rest; a silk loom and a solar array take their turn." },
    { id: "v10", name: "The Drift Yards", who: "zephyr", needs: [["driftballoon", 1], ["moonwafers", 1]], temp: {"p": "kitepost", "taps": 16, "mins": 30}, coins: 3800, xp: 420, gift: "chest",
      talk: [["zephyr", "Balloons! Big ones! Between EVERY island!"], ["zephyr", "A drift balloon and a stack of moon wafers for the passengers. Wheee!"]],
      text: "Balloons between the islands. Everyone can visit everyone now. A drone pad lands on the next cloud over." },
    { id: "v11", name: "Sky Mail", who: "blorb", needs: [["skyship", 1], ["boxkite", 1]], coins: 4600, xp: 500,
      talk: [["blorb", "Parcel! For... a cloud. Which cloud? They all move. This is the worst route in the galaxy."], ["blorb", "A balloon airship to carry the mail and a drone for the tricky clouds. Then I can finally be on time. Once."]],
      text: "Sky mail flies every morning. Postie Blorb has been on time twice. A record." },
    { id: "v12", name: "The Orbital Station", who: "zib", needs: [["commsat", 1], ["roommod", 1]], coins: 5000, xp: 540, unlock: ["nebulapool", "gravwell"], retire: ["skytree", "chimepost"], gift: "chest",
      talk: [["zib", "Kix has found a business opportunity. Satellites! Every world talking to every world. Kix sells the phones."], ["bloop", "Kix. That is just a network."], ["zib", "A comm satellite and a room module for the staff. Kix will handle the rest."]],
      text: "Every camp on every world can talk to every other. A nebula pool and a gravity well open up beneath the station." },
    { id: "v13", name: "The Grand Orrery", who: "halo", needs: [["ringplanet", 1], ["neblamp", 1]], coins: 5500, xp: 580,
      talk: [["halo", "I would like to see every world you woke, all at once, turning in the light."], ["halo", "A ringed planet for the centre and a nebula lamp to light it."]],
      text: "Little worlds turn in the lamp light. Halo watches the Meadow the longest." },
    { id: "v14", name: "The Rainbow Bridge", who: "zephyr", needs: [["rainbowbridge", 1], ["nebglobe", 1]], coins: 6000, xp: 630, gift: "chest",
      talk: [["zephyr", "What if you could walk from cloud to cloud? Without falling? I fell twice today!"], ["zephyr", "A rainbow bridge, and a nebula globe to light it at night. Whee!"]],
      text: "A bridge of every colour from one end of the Reach to the other. Zephyr has crossed it forty times." },
    { id: "v15", name: "The Bloom Returns", who: "bloop", needs: [["orbstation", 1], ["twinplanets", 1], ["solarstation", 1]], coins: 7000, xp: 700, gift: "chest",
      talk: [["bloop", "This is it. The very last piece of the Vault. Everything we carried, from the Meadow to here."], ["halo", "An orbital station to hold the light, twin planets to balance it, and a solar station to power it."], ["bloop", "Blorp. Rokk heard a hum from past the edge of the map. So did I. Something out there is waving."]],
      text: "Five worlds, all lit. The Vault is empty and the galaxy is full. And past the edge of the map, something waves back... To be continued." },
  ],
};
