/* Restoration projects — the main thread of every world.
 *
 * Travel Town has you rebuild a place task by task; Galaxy Adventure has you wake
 * a world the same way. Each project asks for a few specific things (and a
 * little money), and finishing it pays well, moves the story on and makes the
 * camp a little more alive. They come in order: the next one opens when the
 * last is done.
 *
 * `launch: true` marks the project that repairs the way off this world. Until
 * it is done the next planet stays locked on the star map, so a world takes a
 * few hours to leave, not ten minutes.
 *
 *   id, name, who (character), text (said when it is done),
 *   needs: [[itemId, qty], ...], coins (cost), xp (world XP reward), gift
 *   (optional: an item or 'chest' dropped on the board as a reward)
 *
 * Needs are picked so each project only uses chains that are awake by the
 * time you reach it.
 */

export const PROJECTS = {
  /* Sunny Meadow is told as one story. You start with a single tree; every
     chapter hands you the next thing — a producer that stays (`unlock`), a
     guest that stays for a while (`temp`), or an event (`event`). The last
     chapter needs the finished rocket, and finishing it opens the sky. */
  earth: [
    { id: 'e1', name: 'Clear the Path', who: 'pip', needs: [['branch', 2]], coins: 0, xp: 15, unlock: 'rocks',
      talk: [['pip', 'A visitor! Nobody has come up this path in years.'], ['pip', 'Tap the Meteor Crater for meteor chips. Two chips make a hot meteor. Two hot meteors clear the path!']],
      text: 'The path is clear, and there was a heap of space rocks under the rubble.' },
    { id: 'e2', name: 'A Rock Border', who: 'grandma', needs: [['rock', 2], ['log', 1]], coins: 80, xp: 25, unlock: 'bush',
      talk: [['grandma', 'The space weeds walk into my garden like they own it. Rude.'], ['grandma', 'Two rocks and a metal ingot for a border, dear.']],
      text: 'A tidy border. Behind it, a snack cart rolls up, beeping.' },
    { id: 'e3', name: 'Nana Luma\'s Snacks', who: 'grandma', needs: [['jam', 1], ['berries', 2]], coins: 120, xp: 40, unlock: 'well',
      talk: [['grandma', 'Snacks! One food tube and two snack cubes for the picnic.'], ['biscuit', 'The snacks are hereby confiscated. Mayoral privilege.']],
      text: 'First proper meal in years! Washing up, Nana remembered the old moonwater well.' },
    { id: 'e4', name: 'Water for the Garden', who: 'grandma', needs: [['jug', 1], ['puddle', 2]], coins: 200, xp: 60, event: 'meteor',
      talk: [['pip', 'Tap the well: water drops make puddles, puddles make a canister.']],
      text: 'The garden perks up. ...Wait. What is that in the sky?' },
    { id: 'e5', name: 'Dr. Zonk\'s Workshop', who: 'bloop', needs: [['scrap', 1], ['lumber', 1], ['geode', 1]], coins: 320, xp: 80, lab: true,
      talk: [['bloop', 'Blorp. Thank you for not screaming. Most planets scream.'], ['bloop', 'I need a workshop: one Star Scrap, some metal plates and a shiny geode.'], ['timmy', 'A REAL alien! Can I help? CAN I?']],
      text: 'Dr. Zonk\'s Lab hums to life. Recycle spare things there for 🧪 Science.' },
    { id: 'e6', name: 'Mend the Fences', who: 'biscuit', needs: [['lumber', 2], ['pie', 1]], coins: 400, xp: 100, unlock: 'meadow', gift: 'chest', retire: ['tree'],
      talk: [['biscuit', 'Citizens! The fence is broken. Also a moon goat ate my hat.'], ['grandma', 'Two stacks of metal plates and a ration tray for the builder, please.']],
      text: 'The fence stands. The Meteor Crater gave its last metal and cools down now. A solar farm hums on the hill.' },
    { id: 'e7', name: 'Power Supper', who: 'grandma', needs: [['bale', 1], ['pie', 1], ['barrel', 1]], coins: 560, xp: 120, unlock: 'flowerbed', retire: ['well'],
      talk: [['grandma', 'A supper under the stars! A solar panel for the lights, a ration tray and a water tank.'], ['bloop', 'What is supper. I would like to learn about supper.']],
      text: 'Dr. Zonk had three trays. The old well has done its job, and Sirra brought a light stall.' },
    { id: 'e8', name: 'The Light Market', who: 'gigi', needs: [['bouquet', 1], ['gem', 1]], coins: 720, xp: 140, unlock: 'teabush', gift: 'chest', retire: ['rocks'],
      temp: { p: 'hive', taps: 18, mins: 25 },
      talk: [['gigi', 'Darling, a village without a light market is just houses in the dark.'], ['gigi', 'A star lantern for the stall and a gem for the sign.']],
      text: 'The market glows! The space rocks are all used up, a fizz vent bubbles up, and buzzbots moved in for a while.' },
    { id: 'e9', name: 'Nectar Jelly', who: 'gigi', needs: [['honeycomb', 1], ['cake', 1]], coins: 880, xp: 160, retire: ['bush'],
      temp: { p: 'mosslog', taps: 16, mins: 30 },
      talk: [['gigi', 'Nectar jelly! A hex cell of nectar, quickly, before the buzzbots leave.']],
      text: 'Jelly for all. The snack cart is empty. In the woods, an eyeshroom log is blinking awake.' },
    { id: 'e10', name: 'Forest Fizz', who: 'grandma', needs: [['mushring', 1], ['teacup', 1]], coins: 1040, xp: 180,
      temp: { p: 'cottonpatch', taps: 24, mins: 40 },
      talk: [['grandma', 'My mother\'s forest fizz: a bunch of eyeshrooms and a can of soda.'], ['bloop', 'On my world, soda is a colour. Fascinating.']],
      text: 'Fizz for everyone. A suit loom hums for a little while. Sirra has ideas.' },
    { id: 'e11', name: 'Spacesuits for All', who: 'gigi', needs: [['clothbolt', 1], ['hat', 1], ['teacup', 1]], coins: 1200, xp: 200, unlock: 'nestbox',
      talk: [['gigi', 'Everyone is dressed like a scare-bot. No offence to the scare-bot.'], ['gigi', 'A space helmet, a solar panel array and a soda for the tailor. I do the rest. I always do the rest.']],
      text: 'Suits for all. Someone dragged an old jet wreck into the square.' },
    { id: 'e12', name: 'Jet Day', who: 'timmy', needs: [['speckegg', 1], ['garland', 1]], coins: 1360, xp: 220, unlock: 'toychest', retire: ['flowerbed', 'teabush'],
      temp: { p: 'crashsite', taps: 20, mins: 30 },
      talk: [['timmy', 'A twin jetpack and a light string so it looks cool!'], ['pip', 'Jetpacks do not care about lights, Ember.'], ['timmy', 'THIS jetpack does.']],
      text: 'Timmy flew all evening. The light stall and the fizz vent have given all they had. Then something small crashes behind the hill, blinking!' },
    { id: 'e13', name: 'The Little Visitors', who: 'timmy', needs: [['alienkid', 1], ['toyrobot', 1], ['nest', 1]], coins: 1520, xp: 240, unlock: 'vegpatch', gift: 'chest',
      talk: [['bloop', 'Blinkies! Babies. Far from home, like me.'], ['timmy', 'Help one grow up: give it a toy robot and a jet boot. Can we keep it?!']],
      text: 'The little visitors are safe and very hungry. Zib set up a hydro bed.' },
    { id: 'e14', name: 'A Garden for Guests', who: 'biscuit', needs: [['carrot', 2], ['scarecrow', 1], ['spintop', 1]], coins: 1680, xp: 260, unlock: 'tinkerbench', retire: ['meadow'],
      talk: [['biscuit', 'The space crows threaten civic order. I drafted a strongly worded letter.'], ['pip', 'Or two grow tubes, a power station and a spinning top for the Blinkies?']],
      text: 'The solar farm powers the last station. Dr. Zonk drags out a lens workbench: "For star lenses."' },
    { id: 'e15', name: 'Stargazing Night', who: 'timmy', needs: [['spyglass', 1], ['vegbundle', 1], ['speckegg', 1]], coins: 1920, xp: 300, unlock: 'lilypond', gift: 'chest', retire: ['nestbox'],
      talk: [['timmy', 'Dr. Zonk says his home is up THERE. Behind the Moon!'], ['grandma', 'A spyglass, a hydro tray and a twin jetpack. Nobody stargazes on an empty stomach.']],
      text: 'The Moon has tiny lights. "Friends," whispers Dr. Zonk. And in the woods: his ship. In pieces. Time to build a rocket!' },
    { id: 'e16', name: 'The Cheese Shop', who: 'mumbo', needs: [['carrot', 1], ['lilypad', 2], ['spintop', 1]], coins: 2080, xp: 320, gift: 'chest', unlock: 'windmill', retire: ['toychest'],
      talk: [['mumbo', 'Chef Gubbo, cheese master. Well, cheese master without a shop.'], ['mumbo', 'A grow tube, two slime puddles to age the cheese, and a spinning top to keep the Blinkies out of it.']],
      text: 'The cheese shop is open, and a cheese mill turns on the hill. Moon cheese for everyone!' },
    { id: 'e17', name: 'Goo Day', who: 'gigi', needs: [['loaf', 1], ['vegbundle', 1], ['lotus', 1]], coins: 2320, xp: 340, unlock: 'claypit', retire: ['vegpatch'],
      talk: [['gigi', 'Cheese but no bowls. Uncivilised, darling.'], ['gigi', 'A cheese wheel, a hydro tray and a slime jar for the potters. There is moon goo by the river.']],
      text: 'The goo pit is open. The hydro bed is resting. Sirra ordered twelve vases.' },
    { id: 'e18', name: 'Fizz in the Garden', who: 'pim', needs: [['claypot', 2], ['roll', 2], ['lotus', 1]], coins: 2560, xp: 360, gift: 'chest',
      temp: { p: 'picnichamper', taps: 14, mins: 30 },
      talk: [['pim', 'Duchess Splatt. I have come a very long way for a proper fizz.'], ['grandma', 'Finally, someone with manners.']],
      text: 'Fizz under the stars. The Duchess leaves her cargo pod behind. On purpose.' },
    { id: 'e19', name: 'The Slime Pond', who: 'timmy', needs: [['lotus', 1], ['urn', 1], ['picnicbasket', 1]], coins: 2800, xp: 380, gift: 'chest', unlock: 'eggnest',
      talk: [['timmy', 'A party at the slime pond! Slime deserves nice things.']],
      text: 'The slime frogs hold a party. Behind the crates: wobbling pet eggs.' },
    { id: 'e20', name: 'Toys for the Blinkies', who: 'bloop', needs: [['pondfrog', 1], ['blobpup', 1], ['claypot', 2]], coins: 3040, xp: 400, gift: 'chest', unlock: 'buskbot',
      temp: { p: 'raincloud', taps: 10, mins: 12 },
      talk: [['bloop', 'Bored Blinkies chew rockets.'], ['biscuit', 'They chewed my OFFICIAL sash.']],
      text: 'The Blinkies have a pet now. A busker bot wanders in, plays one chord, and refuses to leave.' },
    { id: 'e21', name: 'The Space Parade', who: 'pip', needs: [['drum', 1], ['breadbasket', 1], ['urn', 1]], coins: 3280, xp: 420, gift: 'chest', unlock: 'rockethull', retire: ['windmill', 'claypit'],
      talk: [['pip', 'A parade before the launch! A drum, a cheese stack and an orbit urn.']],
      text: 'Best parade ever. "Nearly there," says Dr. Zonk, patting a fin. The fin falls off.' },
    { id: 'e22', name: 'The Launch Pad', who: 'bloop', launch: true, rocket: true, needs: [['nosecone', 1], ['telescope', 1], ['lotus', 2], ['blobpup', 1]], coins: 2240, xp: 360, gift: 'bigchest', unlock: 'weatherballoon',
      talk: [['bloop', 'A nose cone, a telescope, two slime jars to cool the engines, and a blob pup. It insists on coming.'], ['bloop', 'Miss you? No. You are coming too.']],
      text: 'The rocket stands. Sunny Meadow is awake, and the Moon is waiting.' },
  ],
  luna: [
    { id: 'l1', name: 'Light the Camp', who: 'luma', needs: [['mcrystal', 2], ['bulb', 1]], coins: 240, xp: 30,
      talk: [['luma', 'Oh, far out. Visitors. Sorry it is so dark, man — the lamps gave up years ago.'], ['luma', 'Two moon shards and a glow bulb and I can make a little ring of light. Vibes first, then everything else.'], ['zib', 'Kix stowed away in the cargo hold. Kix regrets nothing. Kix is cold.']],
      text: 'A little ring of glow around the tents. The dark is smaller already.' },
    { id: 'l2', name: 'Build a Dust Wall', who: 'rokk', needs: [['regolith', 2], ['iceshard', 1]], coins: 360, xp: 45,
      talk: [['rokk', 'GREETINGS. I AM ROKK. I WAS THE BUTLER OF THIS CAMP. THE CAMP LEFT. I STAYED.'], ['rokk', 'THE DUST STORMS KNOCK OVER THE TENTS. TWO REGOLITH BRICKS AND ONE ICE SHARD FOR MORTAR. PLEASE.'], ['zib', 'Kix could sell him a wall. Kix will not. Kix is being nice. Note it.']],
      text: 'WALL: STANDING. WIND: BLOCKED. ROKK: PROUD.' },
    { id: 'l3', name: 'The Crystal Garden', who: 'nix', needs: [['prismcore', 1], ['glowflower', 1]], coins: 520, xp: 60, gift: 'chest',
      talk: [['nix', 'Ah. Tourists. Mind the crystals, they are older than your planet and twice as interesting.'], ['nix', 'A prism core and a glow flower. I am building a garden. A tasteful one. You would not understand.']],
      text: 'Nix has arranged the crystals by colour, then by size, then by mood.' },
    { id: 'l4', name: 'Lanterns for the Dark Side', who: 'rokk', needs: [['moonlamp', 1], ['silveringot', 1]], coins: 720, xp: 80,
      talk: [['rokk', 'THE FAR SIDE IS DARK FOR FOURTEEN DAYS AT A TIME. I DO NOT LIKE IT. I AM NOT AFRAID. I AM A ROBOT.'], ['rokk', 'A MOON LANTERN AND A SILVER INGOT FOR THE HANDLE. FOR NO REASON. NOT FEAR.']],
      text: 'Rokk walks the far side at night now. Humming. Rokk does not hum. Rokk is humming.' },
    { id: 'l5', name: 'Catch a Comet', who: 'luma', needs: [['cometcore', 1], ['icecore', 1]], coins: 960, xp: 100, gift: 'chest',
      talk: [['luma', 'A comet passes every night at nine, man. Like clockwork. Like a really cold friend.'], ['luma', 'Catch me its core and a ball of clear ice. Comets carry seeds, you know. Old ones.'], ['bloop', 'Blorp. She is right. I checked. I hate it when the hippie is right.']],
      text: 'The comet\'s ice was full of old seeds. Moonbeam planted every one.' },
    { id: 'l6', name: 'Moon Launch Pad', who: 'zib', launch: true, needs: [['moonbrick', 1], ['mstar', 1], ['beacon', 1]], coins: 1280, xp: 140, gift: 'chest',
      talk: [['zib', 'Kix has a business proposal. A launch pad. Kix builds, you pay, everybody flies.'], ['zib', 'Moon brick, moon star, one beacon so the pilot does not miss. Kix missed once. Long story.'], ['bloop', 'There is a fire planet in range. Ember Hollow. Bring a towel. And a fire extinguisher.']],
      text: 'Beep! Pad ready! Kix tested it. Kix only exploded a little. Ember Hollow is in range now!' },
    { id: 'l7', name: 'A Home for the Pups', who: 'nix', needs: [['moonpup', 1], ['lunamothi', 1]], coins: 1520, xp: 170,
      talk: [['nix', 'Those bouncing things are moon pups. They chew crystals. MY crystals.'], ['nix', 'Give them a burrow somewhere far from my garden. A pup and a moth to keep them company.']],
      text: 'The pups have a burrow with a view. They bounce off the walls. Literally.' },
    { id: 'l8', name: 'The Rover Garage', who: 'zib', needs: [['toyrover', 1], ['silvercup', 1]], coins: 1840, xp: 210, gift: 'chest',
      talk: [['zib', 'Kix found an old rover. Kix needs a garage. And a silver cup. For the grand opening.'], ['rokk', 'THERE WILL BE NO GRAND OPENING.'], ['zib', 'There will be a SMALL grand opening.']],
      text: 'Six wheels, one drill, zero brakes. Kix loves it.' },
    { id: 'l9', name: 'Fuel the Heaters', who: 'rokk', needs: [['gascan', 1], ['glacier', 1]], coins: 2160, xp: 250,
      talk: [['rokk', 'THE HEATERS RUN ON HELIUM. THE HELIUM RUNS OUT. EVERYONE IS COLD. MOSTLY ME. I AM METAL.'], ['rokk', 'ONE GAS CANISTER AND ONE GLACIER BLOCK FOR THE COOLANT. THE IRONY IS NOT LOST ON ME.']],
      text: 'WARM. The whole crew slept through the night for the first time.' },
    { id: 'l10', name: 'Call Home', who: 'zib', needs: [['radar', 1], ['pallasite', 1], ['glowtree', 1]], coins: 2800, xp: 340, gift: 'chest',
      talk: [['bloop', 'The old dish still points at the sky. If it turns again, the camp can talk to everyone out there.'], ['luma', 'A radar dish, a pallasite for the tuner, and a glow tree for the vibes. Mostly the vibes.'], ['nix', 'Fine. I will admit it. I would like to call someone.']],
      text: 'The dish turns, the stars answer. Crater Camp is part of the sky again.' },
  ],
  cindra: [
    { id: 'c1', name: 'Rekindle the Forge', who: 'vulk', needs: [['cinder', 2], ['ashroom', 1]], coins: 320, xp: 35,
      talk: [['vulk', 'HRM. A visitor. The forge has been cold for a hundred years. I have been angry for a hundred and one.'], ['vulk', 'Two cinders and an ash mushroom. The forge eats, then it works. Like me.']],
      text: 'The forge breathes. Vulk pretends it was nothing. It was not nothing.' },
    { id: 'c2', name: 'New Tools', who: 'vulk', needs: [['ironingot', 1], ['obshard', 2]], coins: 480, xp: 50,
      talk: [['vulk', 'The forge breathes. Now it needs tools. My old ones melted. My mood melted them.'], ['vulk', 'An iron ingot and two obsidian shards. Sharp things. Good things.']],
      text: 'Hammers, tongs and one very large spoon. Vulk will not explain the spoon.' },
    { id: 'c3', name: 'The Glass Stall', who: 'ember', needs: [['glassbead', 2], ['bigshroom', 1]], coins: 680, xp: 70, gift: 'chest',
      talk: [['ember', 'A REAL VISITOR! Do you want a glass bead? I make glass beads! I make TOO MANY glass beads!'], ['ember', 'Two beads and a big mushroom for the stall roof. Travellers will come. They will! Probably!']],
      text: 'Fizz sells beads to travellers who have not arrived yet. She says they will.' },
    { id: 'c4', name: 'Stew for Everyone', who: 'ember', needs: [['spicejar', 1], ['forgefire', 1]], coins: 920, xp: 90,
      talk: [['ember', 'Everyone here is grumpy because nobody has eaten. Vulk has not eaten since the volcano.'], ['vulk', 'I had a rock in spring.'], ['ember', 'A jar of spice and a forge fire. STEW. The spiciest stew in the system.']],
      text: 'Very, very spicy. Nobody complained. Nobody could speak.' },
    { id: 'c5', name: 'The Bell Tower', who: 'vulk', needs: [['copperbell', 1], ['fireopal', 1]], coins: 1200, xp: 120, gift: 'chest',
      talk: [['vulk', 'The vents roar at night. The old bell used to calm them. Do not ask how. I do not know.'], ['vulk', 'A copper bell and a fire opal for the clapper. Then we sleep.']],
      text: 'The bell rings at sunset. The vents seem to quieten when it does.' },
    { id: 'c6', name: 'Heat-Proof Launch Pad', who: 'bloop', launch: true, needs: [['ironanvil', 1], ['obmirror', 1], ['bellows', 1]], coins: 1520, xp: 160, gift: 'chest',
      talk: [['bloop', 'A launch pad on a planet made of fire. Blorp. What could go wrong.'], ['vulk', 'Iron anvil for the base. Obsidian mirror to throw the heat back. Bellows to cool the engines.'], ['ember', 'And a little flag! I will make the flag!']],
      text: 'It will not melt. Probably. Blorp. Tidal Shallows is next — pack a towel.' },
    { id: 'c7', name: 'Nests for the Salamanders', who: 'ember', needs: [['salamander', 1], ['emberegg', 1]], coins: 1800, xp: 200,
      talk: [['ember', 'The salamanders keep sleeping in Vulk\'s boots.'], ['vulk', 'They are WARM boots.'], ['ember', 'One salamander and an ember egg — they need a nest of their own!']],
      text: 'Tiny flames curled in warm stone. They follow Fizz everywhere now.' },
    { id: 'c8', name: 'The Basalt Hall', who: 'vulk', needs: [['columnstack', 1], ['coppercog', 1]], coins: 2160, xp: 240, gift: 'chest',
      talk: [['vulk', 'Too many people now. Meetings. Opinions. I need a hall with thick walls.'], ['vulk', 'A column stack and a copper cog for the door. A door that closes.']],
      text: 'A hall of stone columns, cool inside, warm outside. Meetings happen there now.' },
    { id: 'c9', name: 'Steam Power', who: 'rokk', needs: [['boiler', 1], ['sulfurcrystal', 2]], coins: 2560, xp: 290,
      talk: [['rokk', 'GREETINGS AGAIN. I FOLLOWED THE STEAM. STEAM IS POWER. POWER IS ORDER.'], ['rokk', 'ONE BOILER AND TWO SULFUR CRYSTALS. THE SMELL IS UNFORTUNATE. THE PROGRESS IS NOT.']],
      text: 'PRESSURE: NOMINAL. HOLLOW: POWERED. ROKK: ALSO NOMINAL.' },
    { id: 'c10', name: 'The Ember Orchard', who: 'ember', needs: [['fruitbasket', 1], ['greatforge', 1], ['rubyshard', 1]], coins: 3200, xp: 380, gift: 'chest',
      talk: [['ember', 'Last one! A garden that grows in fire! Fruit that is warm when you pick it!'], ['vulk', 'A fruit basket, the great forge and a ruby shard to mark the spot. Then Cindra is ours again.'], ['bloop', 'And then the oceans, friend. Tidal Shallows. You will need that towel after all.']],
      text: 'Fire and garden at the same time, without either winning. Cindra is reborn.' },
  ],
  nerith: [
    { id: 'n1', name: 'Clean the Beach', who: 'kelpa', needs: [['seashell', 2], ['kelpfrond', 1]], coins: 400, xp: 40,
      talk: [['kelpa', 'Oh! Hello! Welcome to the Shallows! Mind the seaweed. And the other seaweed. It is all seaweed, sorry.'], ['kelpa', 'Two seashells and a kelp frond and I can clear a path to the water. Then we can paddle!']],
      text: 'Sand you can actually walk on. Kelpa made a sandcastle. Then another. Then eleven.' },
    { id: 'n2', name: 'Replant the Reef', who: 'kelpa', needs: [['coralsprig', 2], ['seedpearl', 1]], coins: 600, xp: 55,
      talk: [['kelpa', 'The reef used to be every colour. Now it is mostly beige. Beige is not a reef colour.'], ['kelpa', 'Two coral sprigs to plant, and a seed pearl to keep them company. Corals get lonely.']],
      text: 'Little corals in neat rows. The first fish arrived an hour later.' },
    { id: 'n3', name: 'The Fish Market', who: 'marin', needs: [['silverfish', 2], ['seafoam', 1]], coins: 840, xp: 75, gift: 'chest',
      talk: [['marin', 'Harbourmaster Brine. Forty years on this pier. Thirty-nine of them grumpy.'], ['marin', 'No fish, no market. No market, no gossip. Two silverfish and some sea foam to keep them fresh. Hop to it.']],
      text: 'The market smells of salt and gossip. Exactly right.' },
    { id: 'n4', name: 'Salt the Catch', who: 'marin', needs: [['saltbrick', 1], ['kelpcoil', 1]], coins: 1080, xp: 95,
      talk: [['marin', 'Fish go off. Everybody knows that. Except Kelpa, who keeps one in a jar "as a friend".'], ['kelpa', 'His name is Gerald!'], ['marin', 'A salt brick and a coil of kelp for the drying racks. Please.']],
      text: 'Enough stores for the whole winter. Brine counted twice.' },
    { id: 'n5', name: 'Raise the Wreck', who: 'marin', needs: [['driftboat', 1], ['pearl', 1]], coins: 1360, xp: 125, gift: 'chest',
      talk: [['marin', 'There is an old skiff at the bottom of the bay. My first boat. I sank it. Long story. Short storm.'], ['marin', 'A driftwood boat to patch her with and a pearl for luck. Sailors are superstitious. I am VERY superstitious.']],
      text: 'The old skiff floats again. Pearl swears it is the same boat her grandmother sailed.' },
    { id: 'n6', name: 'The Floating Launch Pad', who: 'bloop', launch: true, needs: [['nautilus', 1], ['coralfan', 1], ['jellybell', 1]], coins: 1680, xp: 170, gift: 'chest',
      talk: [['bloop', 'Blorp! The next world is up there. The only flat thing here is the water. So the launch pad will float.'], ['marin', 'Floating launch pads. In my day we launched things by throwing them.'], ['bloop', 'A nautilus shell for the hull, a coral fan to steady it, a jelly bell for the lights.']],
      text: 'It bobs a bit. The rocket does not mind. Aurora Reach — the last world — is in range.' },
    { id: 'n7', name: 'Guard the Hatchlings', who: 'kelpa', needs: [['hatchling', 1], ['tentapal', 1]], coins: 2000, xp: 210,
      talk: [['kelpa', 'The turtles are hatching! All at once! There are SO MANY of them!'], ['kelpa', 'A hatchling to show the others the way, and a tentapal to wave the gulls off. Gently!']],
      text: 'Every hatchling made it to the water. Kelpa counted every single one, out loud.' },
    { id: 'n8', name: 'The Harbour', who: 'marin', needs: [['anchor', 1], ['saltpillar', 1]], coins: 2400, xp: 260, gift: 'chest',
      talk: [['marin', 'Boats are coming in from the other worlds now. Rocket boats. Whatever those are.'], ['marin', 'A proper harbour needs an anchor and a salt pillar for a lighthouse. Do it right or do not do it.']],
      text: 'Boats come and go. Some of them from worlds you woke.' },
    { id: 'n9', name: 'Sea-Glass Lamps', who: 'sirra', needs: [['glasslamp', 1], ['pearlstrand', 1]], coins: 2800, xp: 310,
      talk: [['sirra', 'Darling, the Shallows are lovely by day, but by night? Pitch black. Unacceptable.'], ['sirra', 'Sea-glass lamps and a strand of pearls to hang them on. Mood lighting. Everybody deserves mood lighting.']],
      text: 'The shallows glow green at night. The humming is louder now.' },
    { id: 'n10', name: 'Wake the Drowned City', who: 'sirra', needs: [['sunkenidol', 1], ['coralpalace', 1], ['starurchin', 1]], coins: 3520, xp: 400, gift: 'chest',
      talk: [['sirra', 'There is a city under the bay. My grandmother said so. She also said she was a mermaid queen, so.'], ['marin', 'The city is real. I have seen the domes at low tide.'], ['sirra', 'Then let us wake it. A sunken idol, a coral palace and a star urchin — the old songs say that opens the gates.']],
      text: 'The domes break the surface, glittering. Nerith breathes again.' },
  ],
  vela: [
    { id: 'v1', name: 'Solid Ground', who: 'zephyr', needs: [['cloudpuff', 1], ['aurorasilk', 1]], coins: 480, xp: 45,
      talk: [['zephyr', "Wheee! Oh — visitors! Careful, there is no ground. There is no ground ANYWHERE. Isn't it great?"], ['zephyr', 'A big cloud puff and some aurora silk to stitch it down, and you will have something to stand on.']],
      text: 'A cloud you can stand on. Zephyr has been jumping on it for an hour.' },
    { id: 'v2', name: 'Stitch the Sky', who: 'halo', needs: [['auroraveil', 1], ['starlet', 2]], coins: 720, xp: 60,
      talk: [['halo', 'Hello. I have been expecting you for three hundred years. You are slightly late.'], ['halo', 'The sky is torn. An aurora veil to mend it and two starlets to pin it in place.']],
      text: 'One stripe of colour across the dark. Halo keeps looking up.' },
    { id: 'v3', name: 'The Sky Orchard', who: 'wren', needs: [['skyfruit', 1], ['windcoil', 1]], coins: 1000, xp: 85, gift: 'chest',
      talk: [['wren', 'Chirrup! New faces! Did you hear about Zephyr? Fell off a cloud. TWICE. Anyway.'], ['wren', 'The orchard trees float off unless you anchor them. A sky fruit to plant and a wind coil to hold it down.']],
      text: 'Golden fruit on floating branches. The birds found it before anyone.' },
    { id: 'v4', name: 'Tune the Chimes', who: 'wren', needs: [['chimeset', 1], ['prismlens', 1]], coins: 1280, xp: 110,
      talk: [['wren', 'The chimes stopped ringing when the Bloom left. Nobody has gossiped properly since. Tragic.'], ['wren', 'A set of chimes and a prism lens to tune them. Chirrup!']],
      text: 'The chimes play a tune nobody taught them. Halo says it is the Vault singing back.' },
    { id: 'v5', name: 'Nests on the Wind', who: 'wren', needs: [['skyplume', 1], ['starcluster', 1]], coins: 1600, xp: 140, gift: 'chest',
      talk: [['wren', 'The sky birds are coming home! I told everyone first. Obviously.'], ['wren', 'A sky plume to line the nests and a star cluster to keep them warm at night.']],
      text: 'Nests on every cloud. The sky birds are home.' },
    { id: 'v6', name: 'The Drift Yards', who: 'zephyr', needs: [['driftballoon', 1], ['windvane', 1], ['thundercloud', 1]], coins: 1920, xp: 180, gift: 'chest',
      talk: [['zephyr', 'The islands drift apart and nobody visits anybody. Let us fix that!'], ['zephyr', 'A drift balloon, a wind vane to steer by, and a thundercloud for... honestly I just like thunderclouds.']],
      text: 'Balloons between the islands. Everyone can visit everyone now.' },
    { id: 'v7', name: 'A Den for the Star-Kits', who: 'halo', needs: [['starsprite', 1], ['auroracloak', 1]], coins: 2240, xp: 220,
      talk: [['halo', 'The star-kits are frightened. They were born after the Bloom left and have never seen it.'], ['halo', 'A star sprite to lead them and an aurora cloak to keep them warm. Then they will have a home.']],
      text: 'The little star-kits have a den of their own. They glow brighter when you visit.' },
    { id: 'v8', name: 'The Orbital Station', who: 'zib', needs: [['commsat', 1], ['nebjar', 1]], coins: 2640, xp: 270, gift: 'chest',
      talk: [['zib', 'Kix has found a business opportunity. Satellites! Every world talking to every world. Kix sells the phones.'], ['bloop', 'Kix. That is just a network.'], ['zib', 'A comm satellite and a nebula jar for power. Kix will handle the rest. Kix always handles the rest.']],
      text: 'Every camp on every world can talk to every other. Kix has not stopped beeping.' },
    { id: 'v9', name: 'The Celestial Garden', who: 'halo', needs: [['starpot', 1], ['ringplanet', 1]], coins: 3040, xp: 320,
      talk: [['halo', 'The last garden. The Bloom grew here first, they say. We will grow it again.'], ['halo', 'A pot of starflowers and a ringed planet to light them. Slowly. Gently.']],
      text: 'Flowers that glow, planets that spin, a garden in the sky.' },
    { id: 'v10', name: 'The Bloom Returns', who: 'bloop', needs: [['skytreehouse', 1], ['prismarray', 1], ['boxkite', 1]], coins: 3800, xp: 420, gift: 'chest',
      talk: [['bloop', 'This is it. The very last piece of the Vault. Everything we carried, from the Meadow to here.'], ['halo', 'A sky treehouse, a prism array and a box kite to lift it into the light.'], ['bloop', 'Blorp. I think I might cry. Do not tell Rokk.']],
      text: 'Five worlds, all lit. The Vault is empty and the galaxy is full. That was the whole idea.' },
  ],
};
