/* Restoration projects — the main thread of every world.
 *
 * Travel Town has you rebuild a place task by task; Merge Rocket has you wake
 * a world the same way. Each project asks for a few specific things (and a
 * little money), and finishing it pays well, moves the story on and makes the
 * camp a little more alive. They come in order: the next one opens when the
 * last is done.
 *
 * `launch: true` marks the project that repairs the way off this world. Until
 * it is done the next planet stays locked on the star map, so a world takes a
 * few hours to leave, not ten minutes.
 *
 *   id, name, who (character), text (said when it is done),
 *   needs: [[itemId, qty], ...], coins (cost), xp (world XP reward), gift
 *   (optional: an item or 'chest' dropped on the board as a reward)
 *
 * Needs are picked so each project only uses chains that are awake by the
 * time you reach it.
 */

export const PROJECTS = {
  /* Sunny Meadow is told as one story. You start with a single tree; every
     chapter hands you the next thing — a producer that stays (`unlock`), a
     guest that stays for a while (`temp`), or an event (`event`). The last
     chapter needs the finished rocket, and finishing it opens the sky. */
  earth: [
    { id: 'e1', name: 'Clear the Path', who: 'pip', needs: [['branch', 2]], coins: 0, xp: 15, unlock: 'rocks',
      talk: [['pip', 'Oh! A visitor! Nobody has come up the old path in years.'],
        ['pip', 'Ever since the Bloom faded, the meadow just... stopped. Brambles everywhere.'],
        ['pip', 'Tap the Big Tree for twigs, put two together and you get a branch. Two branches and we can clear the path!']],
      text: 'You can see the road to the village again! And look what was under the brambles — an old rock pile. It is yours now.' },
    { id: 'e2', name: 'A Stone Border', who: 'pip', needs: [['rock', 2], ['log', 1]], coins: 20, xp: 25, unlock: 'bush',
      talk: [['pip', 'Nana Gloop\'s garden used to be the prettiest in the valley.'],
        ['grandma', 'Used to be, dear. Now the weeds walk right in. A stone border would keep them out.'],
        ['pip', 'Two rocks and a log. We can do that!']],
      text: 'A tidy border round the garden. Nana Gloop peeked over it and spotted a berry bush that is ready to fruit again.' },
    { id: 'e3', name: 'Nana Gloop\'s Jam', who: 'grandma', needs: [['jam', 1], ['berries', 2]], coins: 30, xp: 40,
      temp: { p: 'raincloud', taps: 16, mins: 20 },
      talk: [['grandma', 'Berries! Real berries! My hands remember the recipe even if my head does not.'],
        ['grandma', 'One jar of jam and two bunches for the pie tin, and we shall have a proper tea.'],
        ['biscuit', 'The pie tin is hereby confiscated. Mayoral privilege.']],
      text: 'The first jar of jam in years! And look — a rain cloud is drifting over the meadow. Catch the drops while it is here.' },
    { id: 'e4', name: 'Mend the Old Well', who: 'grandma', needs: [['jug', 1], ['puddle', 2]], coins: 50, xp: 60, unlock: 'well', event: 'meteor',
      talk: [['grandma', 'That cloud reminded me — the village well dried up the year the Bloom went.'],
        ['pip', 'If we fill it once, maybe it remembers how to fill itself?'],
        ['grandma', 'Bring water while the cloud is here, dear. Puddles merge into a jug.']],
      text: 'The well is singing again, so water is here to stay. ...Wait. What is that in the sky?' },
    { id: 'e5', name: 'Dr. Zonk\'s Workshop', who: 'bloop', needs: [['scrap', 1], ['lumber', 1], ['geode', 1]], coins: 80, xp: 80, lab: true,
      talk: [['bloop', 'Blorp. Thank you for not screaming. Most planets scream.'],
        ['bloop', 'I need a little workshop to fix it. Some star scrap, some lumber, one shiny geode for the lens.'],
        ['timmy', 'A real star-traveller! From a DIFFERENT planet! Can I help? CAN I?']],
      text: 'Dr. Zonk\'s Lab hums to life. Bring it things you do not need and it turns them into 🧪 Science — Science buys upgrades that last for ever.' },
    { id: 'e6', name: 'Mend the Fences', who: 'biscuit', needs: [['lumber', 2], ['pie', 1]], coins: 100, xp: 100, unlock: 'meadow', gift: 'chest',
      talk: [['biscuit', 'Citizens! As your Mayor I declare the fence... broken. Also my hat was eaten.'],
        ['pip', 'The goats keep eating hats. Nana Gloop\'s, the Mayor\'s, mine...'],
        ['grandma', 'My second-best hat. Two lumber piles and a pie for the carpenter, please.']],
      text: 'Mayor Snorb cuts a ribbon on the new fence (twice — the first take was bad), and the hay meadow behind it is growing tall again.' },
    { id: 'e7', name: 'Harvest Supper', who: 'grandma', needs: [['bale', 1], ['cake', 1], ['barrel', 1]], coins: 140, xp: 120, unlock: 'flowerbed',
      talk: [['grandma', 'The whole village used to eat together at harvest. Long tables, lanterns, too much cake.'],
        ['pip', 'Let\'s do it again! A hay bale for seats, a cake, and a barrel of water.'],
        ['bloop', 'What is cake. I would like to learn about cake.']],
      text: 'Everyone came. Dr. Zonk had three slices. Madame Fleeb arrived late with a packet of flower seeds, "for a little colour, darling".' },
    { id: 'e8', name: 'The Flower Market', who: 'gigi', needs: [['bouquet', 1], ['gem', 1]], coins: 180, xp: 140, gift: 'chest',
      temp: { p: 'hive', taps: 18, mins: 25 },
      talk: [['gigi', 'Darling, a village without a flower market is just a lot of houses.'],
        ['gigi', 'A bouquet for the stall, and a gemstone for the sign. People notice a gemstone.']],
      text: 'Colour on every stall — and the flowers brought the bees back! A wild hive has settled for a while. Catch its honey.' },
    { id: 'e9', name: 'Honey Cakes', who: 'gigi', needs: [['honeycomb', 1], ['cake', 1]], coins: 220, xp: 160, unlock: 'mosslog',
      talk: [['gigi', 'Honey cake! The recipe calls for real honeycomb, not the sad syrup kind.'],
        ['grandma', 'And a cake to put it on, I suppose. Quickly, before the bees move on.']],
      text: 'Honey cakes for everyone. Nana Gloop says the old mossy log in the woods is sprouting mushrooms again — she knows a recipe.' },
    { id: 'e10', name: 'Forest Tea', who: 'grandma', needs: [['mushring', 1], ['fountain', 1]], coins: 260, xp: 180, unlock: 'cottonpatch',
      talk: [['grandma', 'My mother made forest tea every spring. Mushrooms and well water, nothing more.'],
        ['grandma', 'Bring me a ring of caps, and a fountain for the square while you are at it. We had one once.'],
        ['bloop', 'On my world, tea is a colour. Here it is a drink. Fascinating.']],
      text: 'The fountain splashes in the square. Behind it, the old cotton patch is fluffing up white.' },
    { id: 'e11', name: 'Patchwork Coats', who: 'gigi', needs: [['clothbolt', 1], ['hat', 1]], coins: 300, xp: 200, unlock: 'nestbox',
      talk: [['gigi', 'Autumn is coming and everyone is dressed like a scarecrow. No offence to the scarecrow.'],
        ['gigi', 'A bolt of cloth and a straw hat. I will do the rest. I always do the rest.']],
      text: 'Warm coats for the whole village. The birds have come back to nest in Gorbo\'s old bird box.' },
    { id: 'e12', name: 'Bird Song', who: 'timmy', needs: [['nest', 1], ['garland', 1]], coins: 340, xp: 220,
      temp: { p: 'crashsite', taps: 20, mins: 30 },
      talk: [['timmy', 'The songbirds are back but they need somewhere cosy. A nest! And a garland so it looks nice!'],
        ['pip', 'Birds do not care about garlands, Gorbo.'],
        ['timmy', 'THESE birds do.']],
      text: 'The birds sang all evening. Then Gorbo came running: something small crashed behind the hill — and it is blinking!' },
    { id: 'e13', name: 'The Little Visitors', who: 'timmy', needs: [['alienkid', 1], ['speckegg', 1]], coins: 380, xp: 240, unlock: 'vegpatch', gift: 'chest',
      talk: [['bloop', 'Blorp! Those are Blinkies. Babies. They hatch from the eggs in that wreck.'],
        ['timmy', 'Can we keep one?! Can we?'],
        ['bloop', 'Help one grow up, and keep a speckled egg warm for the next. They are far from home. Like me.']],
      text: 'The little visitors are safe and very hungry. Zorp dug a veggie patch so nobody goes to bed without supper.' },
    { id: 'e14', name: 'A Garden for Guests', who: 'biscuit', needs: [['carrot', 2], ['scarecrow', 1]], coins: 420, xp: 260, unlock: 'tinkerbench',
      talk: [['biscuit', 'The crows are a threat to civic order. I have drafted a strongly worded letter.'],
        ['pip', 'Or... two carrots for the Blinkies and a scarecrow for the crows?']],
      text: 'The garden thrives. Dr. Zonk dragged an old tinker bench out of the barn: "for lenses. We need to see where we are going."' },
    { id: 'e15', name: 'Stargazing Night', who: 'timmy', needs: [['spyglass', 1], ['statue', 1], ['vegbundle', 1]], coins: 480, xp: 300, gift: 'chest',
      talk: [['timmy', 'Dr. Zonk says his home is up THERE. Somewhere. Behind the Moon.'],
        ['bloop', 'A spyglass to find the way. A statue to mark this spot, so we can always come back.'],
        ['grandma', 'And a basket of veggies, because nobody stargazes on an empty stomach.']],
      text: 'Through the spyglass: the Moon, and on it, tiny lights. "Crater Camp," whispers Dr. Zonk. "Friends."' },
    { id: 'e16', name: 'The Village Bakery', who: 'mumbo', needs: [['carrot', 1], ['bale', 1], ['vegbundle', 1]], coins: 520, xp: 320, unlock: 'windmill',
      talk: [['mumbo', 'Hello hello! Chef Gubbo, baker. Well — baker without a bakery.'],
        ['mumbo', 'Bring me carrots, hay for the oven floor and a bundle of veggies, and I will build us a windmill.'],
        ['pip', 'A windmill! Real bread again!']],
      text: 'The windmill turns. Flour, at last — Chef Gubbo is already humming over a bowl of dough.' },
    { id: 'e17', name: 'Pottery Day', who: 'gigi', needs: [['loaf', 1], ['nest', 1], ['quilt', 1]], coins: 580, xp: 340, unlock: 'claypit',
      talk: [['gigi', 'Bread on the table but no bowls to put it in. Uncivilised, darling.'],
        ['gigi', 'A loaf for the potters, a nest and a quilt to pack the kiln. There is clay by the river.']],
      text: 'The old clay pit by the river is open again. Madame Fleeb has already ordered twelve vases.' },
    { id: 'e18', name: 'Tea in the Garden', who: 'pim', needs: [['claypot', 2], ['roll', 2], ['bouquet', 1]], coins: 640, xp: 360, unlock: 'teabush',
      talk: [['pim', 'Duchess Splatt, delighted. I have come a very long way for a proper cup of tea.'],
        ['pim', 'Pots for the seedlings, rolls for the guests and flowers for the table, if you would be so kind.'],
        ['grandma', 'Finally, someone with manners.']],
      text: 'A tea bush takes root by the cottage. Duchess Splatt declares the meadow "almost civilised".' },
    { id: 'e19', name: 'The Lily Pond', who: 'timmy', needs: [['teapot', 1], ['urn', 1], ['fountain', 1]], coins: 700, xp: 380, unlock: 'lilypond',
      talk: [['timmy', 'I found a dry hollow behind the barn. It used to be a pond — Nana Gloop said so!'],
        ['timmy', 'If we fill it, the frogs come back. Frogs with THREE EYES.']],
      text: 'Water fills the hollow, lily pads open, and somewhere a three-eyed frog says hello.' },
    { id: 'e20', name: 'Toys for the Blinkies', who: 'bloop', needs: [['lotus', 1], ['teaset', 1], ['vegcrate', 1]], coins: 760, xp: 400, unlock: 'toychest', gift: 'chest',
      talk: [['bloop', 'The little Blinkies are bored. Bored Blinkies chew rockets.'],
        ['biscuit', 'They chewed my sash. My OFFICIAL sash.'],
        ['bloop', 'The Mayor agrees. A toy chest, please, before they find the fuel tank.']],
      text: 'A painted toy chest appears. The Blinkies have not chewed anything for an entire hour.' },
    { id: 'e21', name: 'The Toy Parade', who: 'pip', needs: [['toyrobot', 1], ['koipair', 1], ['buntower', 1]], coins: 820, xp: 420, gift: 'chest',
      talk: [['pip', 'Everyone is here: Chef Gubbo, Duchess Splatt, the Blinkies... let us have a parade before the launch!'],
        ['pip', 'A toy robot to lead it, koi for the pond float, and a bun tower for after.']],
      text: 'The best parade the meadow has ever seen. Then everyone turns to look at the rocket.' },
    { id: 'e22', name: 'The Launch Pad', who: 'bloop', launch: true, rocket: true, needs: [['cart', 1], ['telescope', 1], ['aqueduct', 1], ['toyrocket', 1]], coins: 560, xp: 360, gift: 'bigchest',
      talk: [['bloop', 'The rocket is nearly ready. It needs a pad that will not crack, and water to cool the engines.'],
        ['pip', 'A cart for the fuel, a telescope for the pilot, and an aqueduct for the water. We will miss you, Dr. Zonk.'],
        ['bloop', 'Miss? No. You are coming too.']],
      text: 'The pad holds, the rocket stands, the meadow is awake. Sunny Meadow is restored — and Luna is waiting.' },
  ],
  luna: [
    { id: 'l1', name: 'Light the Camp', who: 'luma', needs: [['mcrystal', 2], ['bulb', 1]], coins: 60, xp: 30,
      text: 'A little ring of glow around the tents. The dark is smaller already.' },
    { id: 'l2', name: 'Build a Dust Wall', who: 'rokk', needs: [['regolith', 2], ['iceshard', 1]], coins: 90, xp: 45,
      text: 'WALL: STANDING. WIND: BLOCKED. ROKK: PROUD.' },
    { id: 'l3', name: 'The Crystal Garden', who: 'nix', needs: [['prismcore', 1], ['glowflower', 1]], coins: 130, xp: 60, gift: 'chest',
      text: 'Nix has arranged the crystals by colour, then by size, then by mood.' },
    { id: 'l4', name: 'Lanterns for the Dark Side', who: 'rokk', needs: [['moonlamp', 1], ['silveringot', 1]], coins: 180, xp: 80,
      text: 'Rokk walks the far side at night now. Humming. Rokk does not hum. Rokk is humming.' },
    { id: 'l5', name: 'Catch a Comet', who: 'luma', needs: [['cometcore', 1], ['icecore', 1]], coins: 240, xp: 100, gift: 'chest',
      text: 'The comet\'s ice was full of old seeds. Luma planted every one.' },
    { id: 'l6', name: 'Moon Launch Pad', who: 'zib', launch: true, needs: [['moonbrick', 1], ['mstar', 1], ['beacon', 1]], coins: 320, xp: 140, gift: 'chest',
      text: 'Beep! Pad ready! Zib tested it. Zib only exploded a little. Ember Hollow is in range now!' },
    { id: 'l7', name: 'A Home for the Pups', who: 'nix', needs: [['moonpup', 1], ['lunamothi', 1]], coins: 380, xp: 170,
      text: 'The pups have a burrow with a view. They bounce off the walls. Literally.' },
    { id: 'l8', name: 'The Rover Garage', who: 'zib', needs: [['toyrover', 1], ['silvercup', 1]], coins: 460, xp: 210, gift: 'chest',
      text: 'Six wheels, one drill, zero brakes. Zib loves it.' },
    { id: 'l9', name: 'Fuel the Heaters', who: 'rokk', needs: [['gascan', 1], ['glacier', 1]], coins: 540, xp: 250,
      text: 'WARM. The whole crew slept through the night for the first time.' },
    { id: 'l10', name: 'Call Home', who: 'zib', needs: [['radar', 1], ['pallasite', 1], ['glowtree', 1]], coins: 700, xp: 340, gift: 'chest',
      text: 'The dish turns, the stars answer. Crater Camp is part of the sky again.' },
  ],
  cindra: [
    { id: 'c1', name: 'Rekindle the Forge', who: 'vulk', needs: [['cinder', 2], ['ashroom', 1]], coins: 80, xp: 35,
      text: 'The forge breathes. Vulk pretends it was nothing. It was not nothing.' },
    { id: 'c2', name: 'New Tools', who: 'vulk', needs: [['ironingot', 1], ['obshard', 2]], coins: 120, xp: 50,
      text: 'Hammers, tongs and one very large spoon. Vulk will not explain the spoon.' },
    { id: 'c3', name: 'The Glass Stall', who: 'ember', needs: [['glassbead', 2], ['bigshroom', 1]], coins: 170, xp: 70, gift: 'chest',
      text: 'Ember sells beads to travellers who have not arrived yet. She says they will.' },
    { id: 'c4', name: 'Stew for Everyone', who: 'ember', needs: [['spicejar', 1], ['forgefire', 1]], coins: 230, xp: 90,
      text: 'Very, very spicy. Nobody complained. Nobody could speak.' },
    { id: 'c5', name: 'The Bell Tower', who: 'vulk', needs: [['copperbell', 1], ['fireopal', 1]], coins: 300, xp: 120, gift: 'chest',
      text: 'The bell rings at sunset. The vents seem to quieten when it does.' },
    { id: 'c6', name: 'Heat-Proof Launch Pad', who: 'bloop', launch: true, needs: [['ironanvil', 1], ['obmirror', 1], ['bellows', 1]], coins: 380, xp: 160, gift: 'chest',
      text: 'It will not melt. Probably. Blorp. Tidal Shallows is next — pack a towel.' },
    { id: 'c7', name: 'Nests for the Salamanders', who: 'ember', needs: [['salamander', 1], ['emberegg', 1]], coins: 450, xp: 200,
      text: 'Tiny flames curled in warm stone. They follow Ember everywhere now.' },
    { id: 'c8', name: 'The Basalt Hall', who: 'vulk', needs: [['columnstack', 1], ['coppercog', 1]], coins: 540, xp: 240, gift: 'chest',
      text: 'A hall of stone columns, cool inside, warm outside. Meetings happen there now.' },
    { id: 'c9', name: 'Steam Power', who: 'rokk', needs: [['boiler', 1], ['sulfurcrystal', 2]], coins: 640, xp: 290,
      text: 'PRESSURE: NOMINAL. HOLLOW: POWERED. ROKK: ALSO NOMINAL.' },
    { id: 'c10', name: 'The Ember Orchard', who: 'ember', needs: [['fruitbasket', 1], ['greatforge', 1], ['rubyshard', 1]], coins: 800, xp: 380, gift: 'chest',
      text: 'Fire and garden at the same time, without either winning. Cindra is reborn.' },
  ],
  nerith: [
    { id: 'n1', name: 'Clean the Beach', who: 'kelpa', needs: [['seashell', 2], ['kelpfrond', 1]], coins: 100, xp: 40,
      text: 'Sand you can actually walk on. Kelpa made a sandcastle. Then another. Then eleven.' },
    { id: 'n2', name: 'Replant the Reef', who: 'kelpa', needs: [['coralsprig', 2], ['seedpearl', 1]], coins: 150, xp: 55,
      text: 'Little corals in neat rows. The first fish arrived an hour later.' },
    { id: 'n3', name: 'The Fish Market', who: 'marin', needs: [['silverfish', 2], ['seafoam', 1]], coins: 210, xp: 75, gift: 'chest',
      text: 'The market smells of salt and gossip. Exactly right.' },
    { id: 'n4', name: 'Salt the Catch', who: 'marin', needs: [['saltbrick', 1], ['kelpcoil', 1]], coins: 270, xp: 95,
      text: 'Enough stores for the whole winter. Marin counted twice.' },
    { id: 'n5', name: 'Raise the Wreck', who: 'marin', needs: [['driftboat', 1], ['pearl', 1]], coins: 340, xp: 125, gift: 'chest',
      text: 'The old skiff floats again. Sirra swears it is the same boat her grandmother sailed.' },
    { id: 'n6', name: 'The Floating Launch Pad', who: 'bloop', launch: true, needs: [['nautilus', 1], ['coralfan', 1], ['jellybell', 1]], coins: 420, xp: 170, gift: 'chest',
      text: 'It bobs a bit. The rocket does not mind. Aurora Reach — the last world — is in range.' },
    { id: 'n7', name: 'Guard the Hatchlings', who: 'kelpa', needs: [['hatchling', 1], ['tentapal', 1]], coins: 500, xp: 210,
      text: 'Every hatchling made it to the water. Kelpa counted every single one, out loud.' },
    { id: 'n8', name: 'The Harbour', who: 'marin', needs: [['anchor', 1], ['saltpillar', 1]], coins: 600, xp: 260, gift: 'chest',
      text: 'Boats come and go. Some of them from worlds you woke.' },
    { id: 'n9', name: 'Sea-Glass Lamps', who: 'sirra', needs: [['glasslamp', 1], ['pearlstrand', 1]], coins: 700, xp: 310,
      text: 'The shallows glow green at night. The humming is louder now.' },
    { id: 'n10', name: 'Wake the Drowned City', who: 'sirra', needs: [['sunkenidol', 1], ['coralpalace', 1], ['starurchin', 1]], coins: 880, xp: 400, gift: 'chest',
      text: 'The domes break the surface, glittering. Nerith breathes again.' },
  ],
  vela: [
    { id: 'v1', name: 'Solid Ground', who: 'zephyr', needs: [['cloudpuff', 1], ['aurorasilk', 1]], coins: 120, xp: 45,
      text: 'A cloud you can stand on. Zephyr has been jumping on it for an hour.' },
    { id: 'v2', name: 'Stitch the Sky', who: 'halo', needs: [['auroraveil', 1], ['starlet', 2]], coins: 180, xp: 60,
      text: 'One stripe of colour across the dark. Halo keeps looking up.' },
    { id: 'v3', name: 'The Sky Orchard', who: 'wren', needs: [['skyfruit', 1], ['windcoil', 1]], coins: 250, xp: 85, gift: 'chest',
      text: 'Golden fruit on floating branches. The birds found it before anyone.' },
    { id: 'v4', name: 'Tune the Chimes', who: 'wren', needs: [['chimeset', 1], ['prismlens', 1]], coins: 320, xp: 110,
      text: 'The chimes play a tune nobody taught them. Halo says it is the Vault singing back.' },
    { id: 'v5', name: 'Nests on the Wind', who: 'wren', needs: [['skyplume', 1], ['starcluster', 1]], coins: 400, xp: 140, gift: 'chest',
      text: 'Nests on every cloud. The sky birds are home.' },
    { id: 'v6', name: 'The Drift Yards', who: 'zephyr', needs: [['driftballoon', 1], ['windvane', 1], ['thundercloud', 1]], coins: 480, xp: 180, gift: 'chest',
      text: 'Balloons between the islands. Everyone can visit everyone now.' },
    { id: 'v7', name: 'A Den for the Star-Kits', who: 'halo', needs: [['starsprite', 1], ['auroracloak', 1]], coins: 560, xp: 220,
      text: 'The little star-kits have a den of their own. They glow brighter when you visit.' },
    { id: 'v8', name: 'The Orbital Station', who: 'zib', needs: [['commsat', 1], ['nebjar', 1]], coins: 660, xp: 270, gift: 'chest',
      text: 'Every camp on every world can talk to every other. Zib has not stopped beeping.' },
    { id: 'v9', name: 'The Celestial Garden', who: 'halo', needs: [['starpot', 1], ['ringplanet', 1]], coins: 760, xp: 320,
      text: 'Flowers that glow, planets that spin, a garden in the sky.' },
    { id: 'v10', name: 'The Bloom Returns', who: 'bloop', needs: [['skytreehouse', 1], ['prismarray', 1], ['boxkite', 1]], coins: 950, xp: 420, gift: 'chest',
      text: 'Five worlds, all lit. The Vault is empty and the galaxy is full. That was the whole idea.' },
  ],
};
