/* Turns MergeRocket.html into the body-only form the Artifact tool wants:
   the tool supplies the page skeleton, so doctype/html/head/body come off and
   the <title> is kept as a comment for whoever reads the file later. */
import { readFileSync, writeFileSync } from 'node:fs';

const html = readFileSync('MergeRocket.html', 'utf8');
/* The bundle contains the literal strings "</head>" and "</body>" (they are in
   the game's own DOM code), so a lazy regex stops at the wrong one and silently
   throws the whole script away. Cut on the outermost tags instead. */
const between = (open, close) => {
  const a = html.indexOf('>', html.indexOf(open)) + 1;
  const b = html.lastIndexOf(close);
  return a > 0 && b > a ? html.slice(a, b) : '';
};
const head = between('<head', '</head>');
const body = between('<body', '</body>');
if (!body) { console.error('artifact-body: no <body> in MergeRocket.html'); process.exit(1); }

// Vite hoists the module script into <head>, so the bundle usually lives there.
// Keep every <style> and <script> from the head and drop the meta/title/link
// chrome the Artifact skeleton owns; markup and styles first, code last.
const grab = (src, tag) => {
  const out = [];
  const open = new RegExp(`<${tag}[^>]*>`, 'gi');
  let m;
  while ((m = open.exec(src))) {
    const end = src.indexOf(`</${tag}>`, m.index);
    if (end < 0) break;
    out.push(src.slice(m.index, end + tag.length + 3));
    open.lastIndex = end;
  }
  return out;
};
const styles = grab(head, 'style').join('\n');
const scripts = [...grab(head, 'script'), ...grab(body, 'script')].join('\n');
if (!scripts) { console.error('artifact-body: the bundle did not survive the cut'); process.exit(1); }
const markup = grab(body, 'script').reduce((acc, s2) => acc.replace(s2, ''), body);
const out = `<!-- Merge Rocket — generated by scripts/artifact-body.mjs, do not edit -->\n`
  + `${styles}\n${markup}\n${scripts}\n`;
writeFileSync('artifact-body.html', out);
console.log('artifact body ->', (out.length / 1024).toFixed(0) + ' kB');
